feat(:ui ligatures): use ligature.el for Emacs28+
doomemacs/doomemacs pull request #5082
Opened 2021-05-23 09:36 UTC by gagbo

As discussed briefly on Discord + Discourse, use https://github.com/mickeynp/ligature.el to handle the composition table for ligatures if using Emacs28+ with Harfbuzz.

This gives an easier API to handle per-user/per-mode configuration (potentially dealing with #4922 ), and all potential fixes can be targeted upstream instead of maintaining the code here (See #5053 ).

All example configuration values is coming from suggestions in upstream package, not much has been changed to enable discussion :

- Should we keep the "all-prog-mode" `defvar` as is ?
- Should extra ligatures go in their `:lang` modules ? (If so, this PR will _not_ make it, better have other contributions to their respective modules)
- Should the `defvar` keep track of all the ligatures available for each font, in a `+fira/+iosevka...` way ? (If so, this PR will _not_ make the per font change, but I'll try to find a minimal set for the `defvar`)
- Should there be a "all-text-mode" `defvar` as well ? (looking at you, `markdown-mode` and `org-mode`)
- Should there be a "t" `defvar as well ?

PS: thanks @mickeynp for that package, it's been a good relief when we found out about it

2021-05-23 14:50 UTC, gagbo commented
Added `ligature.el` manipulation in `set-ligatures!` function so that users keep a single entrypoint.

As discussed, it’s pretty hard to handle inheritance of derived modes, so I think the best way to do it is to allow users to override the only configuration that writes to "high priority" modes through `+ligatures-all-modes-list` and `+ligatures-prog-mode-list` and then only use `set-ligatures!` if they want.

2021-05-26 09:59 UTC, gagbo commented
Maybe the `defvar` could be a plist or an alist, so that instead of having multiple variable for `t`, `prog-mode`, `text-mode` etc., we’d have a single list on which we could mapcar `ligature-set-ligatures (car elt) (cdr elt)`.

Not sure if that’s the better API, but I guess it unclutters the namespace

2021-09-30 12:01 UTC, gagbo commented
(pong ; don't stale me bot)

I don't remember the blocker, it was something around the API of `set-ligatures!` that didn't integrate `ligatures.el` and `prettify-symbols-mode` seamlessly enough, but I don't remember what

2023-03-15 07:05 UTC, VitalyAnkh commented
I have been using this branch for a few days. Emacs runs well and some ligature bugs(like ligature characters took more width than they actually need) seem to disappear. Looking forward to this get merged!

2023-09-10 20:23 UTC, hlissner approved these changes

2023-09-11 22:31 UTC, hlissner requested changes
Looks good! Just a few minor changes and I think it's good to go.

2023-09-11 22:31 UTC, hlissner commented on modules/ui/ligatures/README.org
> +  (ligature-set-ligatures '(haskell-mode clojure-mode) '(">>=" ">>-")))
Please remove `ligature-set-ligatures` from the examples; I consider it an implementation detail. No harm mentioning that `set-font-ligatures!` is a thin wrapper around it though.

2023-09-11 22:31 UTC, hlissner commented on modules/ui/ligatures/autoload/ligatures.el
> +                (setq ligature-ignored-major-modes (delete mode ligature-ignored-major-modes)))
Use `delq` here, considering `mode` will always be a symbol.

2023-09-11 22:31 UTC, hlissner commented on modules/ui/ligatures/autoload/ligatures.el
> +              (ligature-set-ligatures (ensure-list modes) font-ligatures))))
Please reindent this region; it's hanging quite a bit.

2023-09-11 22:31 UTC, hlissner commented on modules/ui/ligatures/autoload/ligatures.el
> +    (with-eval-after-load 'ligature
Use `after!` here, instead of with-eval-after-load (since it does a little magic to avoid eager byte-compilation of the block, as well as to handle the case where `ligature` is disabled by the user (however unlikely that may be).

```diff
-(with-eval-after-load 'ligature
+(after! ligature
```

2023-09-11 22:31 UTC, hlissner commented on modules/ui/ligatures/README.org
>    (ligature-set-ligatures 'eww-mode '("ff" "fi" "ffi")))
Same as above (re: `ligature-set-ligatures`)

2023-09-11 22:36 UTC, hlissner requested changes
Ah, forgot one other request: could you reword 63cb3d621afb7de4ef267e23548ffcc1c402858a and dd0ebe087f159e7c56d13ffe2cbfe6931ed87c3b to include a `BREAKING CHANGE:` in their body? Mainly to comment on what will break and how to work around it (if at all).

2023-09-12 06:52 UTC, gagbo commented on modules/ui/ligatures/autoload/ligatures.el
> +              (ligature-set-ligatures (ensure-list modes) font-ligatures))))
I'll do this manually as I can, parinfer-rust-mode still has this outstanding bug where having parens in a docstring will demolish your code.

2023-09-12 07:01 UTC, gagbo commented
> Ah, forgot one other request: could you reword [63cb3d6](https://github.com/doomemacs/doomemacs/commit/63cb3d621afb7de4ef267e23548ffcc1c402858a) and [dd0ebe0](https://github.com/doomemacs/doomemacs/commit/dd0ebe087f159e7c56d13ffe2cbfe6931ed87c3b) to include a `BREAKING CHANGE:` in their body? Mainly to comment on what will break and how to work around it (if at all).

I just squashed everything, I mostly left the commits like that to remember and revert parts of it if necessary. I don't think it makes a lot of sense to let this be multiple commits on master.

2023-09-12 13:29 UTC, hlissner approved these changes

2023-09-12 19:19 UTC, merged

2023-09-12 19:20 UTC, hlissner commented
LGTM! Thanks again for your help!