Adding Treesitter support to doom
doomemacs/doomemacs pull request #5401
Opened 2021-08-20 00:38 UTC by jeetelongname

This PR adds tree sitter support to doom. 
currently it adds:
- syntax highlighting to the languages that support it.
- structural text objects using [evil-textobj-treesitter](https://github.com/meain/evil-textobj-treesitter)

With plans to add: 
- better code folding using tree sitter (package needs to be found or written)
- a better tree visualization mode (similar to the [playground on tree sitters website](https://tree-sitter.github.io/tree-sitter/playground) or `TSplayground` in neovim (package needs to be found or written) 
- functions and query's that leverage tree sitter for statistics and other useful purposes. 

PR's and patches are welcome as well as pointers and suggestions! feel free to ping me on discord if you have any questions.

(Please also go contribute to 
 related issues:
 - #4151

2021-08-20 00:38 UTC, jeetelongname commented
cc: @iyefrat

2021-08-20 09:08 UTC, ymarco commented
Don't forget to add an entry to modules.org

2021-08-20 10:08 UTC, iyefrat commented
And a `doctor.el` check for module support

2021-08-20 20:32 UTC, ymarco commented
Would be nice to list the new textobject keybinds in README.org too

2021-08-20 22:33 UTC, petr-tik commented
a lurker really keen to see this and LSP work together nicely.

Would it make sense to disable lsp semantic highlighting with `(setq lsp-semantic-tokens-enable nil)` when tree-sitter is enabled ?

2021-08-21 03:09 UTC, daanturo commented on modules/tools/treesitter/config.el
> +         (signal (car e) (cadr e)))))))
This advice isn't needed anymore, we can verify that `turn-on-tree-sitter-mode` & `global-tree-sitter-mode` won't signal errors:
[tree-sitter.el](https://github.com/emacs-tree-sitter/elisp-tree-sitter/blob/c7a1c34549cad41a3618c6f17e0e9dabd3e98fe1/lisp/tree-sitter.el#L209)
I have opened a PR: [Remove doom-tree-sitter-fail-gracefully-a](https://github.com/jeetelongname/doom-emacs/pull/1)

2021-08-21 14:05 UTC, jeetelongname commented on modules/tools/treesitter/config.el
> +         (signal (car e) (cadr e)))))))
It would still make sense to hook tree sitter on prog-modes as thats where a lot of the usecases come from. we should try and load it late as possible to improve performace.

2021-08-21 14:10 UTC, jeetelongname commented
yeah that makes sense

Regards,
– *Jeetaditya Chatterjee* 
/Sent using my text editor/

2021-08-21 14:10 UTC, jeetelongname commented
> a lurker really keen to see this and LSP work together nicely.
> 
> Would it make sense to disable lsp semantic highlighting with `(setq lsp-semantic-tokens-enable nil)` when tree-sitter is enabled ?
Yeah that would make sense. Ill look into it

2021-08-21 15:10 UTC, Mic92 commented on modules/tools/treesitter/README.org
> +Tree-sitter is a parser generator tool and an incremental parsing library. It
For the nix folks, you can use this snippet for testing:

https://github.com/Mic92/dotfiles/blob/07273b7f57b9c78eaa98eddff2fc52335f7a7ed0/nixpkgs-config/modules/emacs/default.nix#L49
combined with:
https://github.com/Mic92/dotfiles/blob/f52d35be19c16cc166040ab5c7cdbb4686f8434f/home/.doom.d/config.el#L187

2021-08-21 15:13 UTC, Mic92 commented on modules/tools/treesitter/README.org
> +Tree-sitter is a parser generator tool and an incremental parsing library. It
It's not ideal because it installs all grammars rather than the supported by doom, but it pays the bills for me...

2021-08-21 16:50 UTC, jeetelongname commented on modules/tools/treesitter/config.el
> +         (signal (car e) (cadr e)))))))
Also could you rebase your commit so that it conforms to the [commit conventions](https://gist.github.com/hlissner/4d78e396acb897d9b2d8be07a103a854)

2021-08-30 15:46 UTC, meain commented
@jeetelongname Just wanted to give you a heads up on the name change of the `evil-textobj-treesitter` package to `evil-textobj-tree-sitter`(extra `-` between tree and sitter). This is done so as to keep it consistent with the other repos ([ref](https://github.com/meain/evil-textobj-tree-sitter/issues/3)). The change will be complete as soon as https://github.com/melpa/melpa/pull/7698 is merged in.

2021-08-30 21:38 UTC, jeetelongname commented
@meain I have been following that and am thankful for the change! 

thanks for this!

2021-09-01 19:11 UTC, Mic92 commented on docs/modules.org
> ++ [[file:~/.config/emacs.doom/modules/tools/treesitter/README.org][treesitter]]  - TODO
```suggestion
+ [[file:~/.config/emacs.doom/modules/tools/treesitter/README.org][treesitter]]  - Fast & precise incremental parsing library for syntax highlighting
```

2021-09-01 20:13 UTC, jeetelongname commented
While its a good tag line its not /witty/ I have come up with “Syntax and Parsing
sitting in a tree…” but I am yet to add it to the init.example and modules.org
as I want that to be one of the last commits a sign off if you will

Regards,
– *Jeetaditya Chatterjee* 
/Sent using my text editor/

2021-09-01 20:16 UTC, jeetelongname commented
to add to my lower comment it not only does syntax highlighting but a bunch of
other stuff as well (even if those come from plugins)

Regards,
– *Jeetaditya Chatterjee* 
/Sent using my text editor/

2021-09-02 18:13 UTC, marcbowes commented on docs/modules.org
> ++ [[file:~/.config/emacs.doom/modules/tools/treesitter/README.org][treesitter]]  - TODO
This looks like an absolute path while all the other links are relative.

2021-09-02 20:53 UTC, jeetelongname commented on docs/modules.org
> ++ [[file:~/.config/emacs.doom/modules/tools/treesitter/README.org][treesitter]]  - TODO
Yes thank you! Will fix

2021-09-17 20:55 UTC, sei40kr commented on modules/tools/tree-sitter/README.org
> +| =l=   | loop        |
```suggestion
| =f= | function    |
| =C= | class       |
| =c= | comment     |
| =i= | conditional |
| =l= | loop        |
```

2021-09-17 20:55 UTC, sei40kr commented on modules/tools/tree-sitter/config.el
> +;;; ui/tree-sitter/config.el -*- lexical-binding: t; -*-
```suggestion
;;; tools/tree-sitter/config.el -*- lexical-binding: t; -*-
```

2021-09-17 20:55 UTC, sei40kr commented on modules/tools/tree-sitter/packages.el
> +;;; ui/tree-sitter/packages.el
```suggestion
;;; tools/tree-sitter/packages.el
```

2021-09-17 20:55 UTC, sei40kr commented on modules/tools/tree-sitter/packages.el
> +(when (featurep! :editor evil +everywhere)
I don't think +everywhere is needed here.

```suggestion
(when (featurep! :editor evil)
```

2021-09-17 20:55 UTC, sei40kr commented on modules/tools/tree-sitter/README.org
> ++ [[https://github.com/meain/evil-textobj-tree-sitter][evil-textobj-tree-sitter]]* (=:editor evil +everywhere=)
```suggestion
+ [[https://github.com/meain/evil-textobj-tree-sitter][evil-textobj-tree-sitter]]* (=:editor evil=)
```

2021-09-17 20:55 UTC, sei40kr commented on modules/tools/tree-sitter/config.el
> +  ;; This makes every node a link to a section of code
```suggestion
  ;; This makes every node a link to a section of code
```

2021-09-17 20:55 UTC, sei40kr commented on modules/tools/tree-sitter/config.el
> +
```suggestion

(use-package! tree-sitter-langs
  :after tree-sitter)

```

2021-09-18 02:19 UTC, jeetelongname commented on modules/tools/tree-sitter/README.org
> +| =l=   | loop        |
While this looks like a problem from a plain text perspective when rendered using org mode (or turned into html) it becomes a non issue (or in the case of org it makes the table look wonky)

2021-09-18 02:38 UTC, jeetelongname commented on modules/tools/tree-sitter/config.el
> +
Is there any advantage to doing it this way? they seem to be doing the same thing except your one makes a second call to `eval-after-load`.

2021-09-18 02:54 UTC, jeetelongname commented on modules/tools/tree-sitter/config.el
> +
Is there any advatage to adding a dedicated use-package declaration? the only thing I see it doing is calling `eval-after-load` a second time

2021-09-18 03:06 UTC, jeetelongname commented on modules/tools/tree-sitter/config.el
> +(when (featurep! :editor evil +everywhere)
as this is adding evil support to tree-sitter I will say that it does need it. for a similar example look at the `:lang latex` module where `evil-tex` is only installed if `+everywhere` is true

2021-09-21 19:49 UTC, jeetelongname commented on modules/tools/tree-sitter/README.org
> +| =l=   | loop        |
My mistake (had fortifications on ). This should be fixed now

2021-09-23 16:24 UTC, sei40kr commented on modules/tools/tree-sitter/config.el
> +(when (featurep! :editor evil +everywhere)
@jeetelongname 
From my understanding, `evil +everywhere` is a flag to enable evil keybinds in **tool buffers** like Magit, Treemacs.

I don't know why `evil-tex` is only installed where `+everywhere` is true, but I think we don't need `+everywhere` here.

2021-09-23 16:28 UTC, sei40kr commented on modules/tools/tree-sitter/config.el
> +
@jeetelongname
The advantage to use `use-package!` is the code looks more declarative.
Current implementation seem to be using `use-package!` as much as possible.

2021-09-23 23:42 UTC, jeetelongname commented on modules/tools/tree-sitter/config.el
> +(when (featurep! :editor evil +everywhere)
I will discuss this with Henrik when i get the chance to as he is the final call here. But I did discuss this in the discord server and the consensus I got was that `+everywhere` is needed here

2021-09-24 17:24 UTC, jeetelongname commented on modules/tools/tree-sitter/config.el
> +
Yeah after looking at the code base more I will tend to agree with you. Its been added. Thanks for your help!

2021-09-28 06:50 UTC, dit7ya commented
Hi, thank you so much for this PR - really excited about Emacs tree-sitter ecosystem grow. I am not sure if it is already covered in the commits, but if not, would it be possible to add something like this [eckon/treesitter-current-functions: Quickly search through and jump to function definitions in the current neovim buffer](https://github.com/eckon/treesitter-current-functions) maybe not just for functions but all text-objects via a selection framework?

2021-09-28 12:34 UTC, jeetelongname commented
@dit7ya  Currently I have not written anything like that and don't plan to. I use lsp for jumping to definitions (or just regular isearch) but that all being said I would not mind adding it if one exists and people find it useful. 

If you do get around to writing one (or end up finding one) just ping me a link and ill get onto integrating it

2021-10-15 21:27 UTC, jeetelongname commented
Yes that was mentioned in the [discord server](https://doomemacs.org/discord). I was actually writing my own when this came around and stole my thunder :sweat_smile:. The only real problem I have is the non idiomatic way to get ranges so I am discussing a refactor with them. 

As for the goto functionality thats honestly sounds awesome! do let me know when that is merged and I will defiantly be making it in!

2021-10-19 05:31 UTC, ckruse commented
`typescript-tsx-mode-hook` is derived from `web-mode`, but `tree-sitter` doesn't play well with web-mode: <https://github.com/emacs-tree-sitter/tree-sitter-langs/issues/23>

2021-10-30 15:16 UTC, jeetelongname commented
Hey,

Yes so as people have said tsx mode derives from web mode which is known to not
work with tree-sitter. If there is another way to work with tsx and it has
similar features what I can do is make the module swap out the mode if tree
sitter is enabled though this will come with the caviet of losing all the
niceties web mode provides.

Regards,
– *Jeetaditya Chatterjee* 
/Sent using my text editor/

2021-11-29 17:40 UTC, steven-lang commented
Any updates on this? Is this module working as is or are there any conflicts with lsp?

2021-11-29 20:45 UTC, jeetelongname commented
This module as is is really usable (I use it everyday as well as many other ~~guinea pigs~~ brave pioneers) as for conflicts with lsp there have never been any. they work on very different parts of emacs and the only real conflict that *may* arise is semantic highlighting and even that is disabled by default in doom. (I remember doing some testing but don't remember if it actually caused a conflict (the fact I can't remember suggests that it did not)) If you do encounter any bugs though then do let me know. 

I have a few more things that I need to do (mostly around language support) and I am working on a playground like plugin which is nearly there (ill probably add it into the module in the coming days).

TLDR, the module is very usable, please report bugs

2021-11-30 18:22 UTC, danilevy1212 commented
Install instructions while this is being developed? @jeetelongname

2021-11-30 18:26 UTC, jeetelongname commented
for the most part pull this branch and doom sync, the only dependency is modules support in emacs and that can't be pulled.

2021-12-24 16:34 UTC, jeetelongname commented
My Christmas gift is getting this PR ready to be merged! everything is technically correct but that does not mean I have not made mistakes, please continue to report bugs or taze me on my grammar in the docs.

I would like to thank everyone who has helped and tested this module! you have been invaluable!

2021-12-25 18:20 UTC, otavioschwanck commented
Hi, thanks for your PR.

Tested on ruby mode and got:

```
Contacting host: github.com:443
Wrote /Users/otavio/.emacs.d/.local/straight/build-27.2/tsc/tsc-dyn.dylib
Eager macro-expansion failure: (file-missing "Cannot open load file" "No such file or directory" "tsc-dyn")
Downloading https://github.com/emacs-tree-sitter/elisp-tree-sitter/releases/download/0.16.0/tsc-dyn.dylib
Wrote /Users/otavio/.emacs.d/.local/straight/build-27.2/tsc/tsc-dyn.dylib
File mode specification error: (doom-hook-error ruby-mode-hook turn-on-tree-sitter-mode (file-missing Cannot open load file No such file or directory tsc-dyn))
```

OS: Mac
Installed gem tree-sitter and tree-sitter on brew.

2021-12-25 18:22 UTC, otavioschwanck requested changes
Ruby tree-sitter not working

2021-12-25 19:22 UTC, otavioschwanck approved these changes

2021-12-26 01:30 UTC, jeetelongname commented
@otavioschwanck I can&rsquo;t repro, I have been testing this module on a ruby project and its been working fine, does the same error appear on other languages?

Have you tried doom syncing again?

also are you using the m1 macbooks as that is known not to work due to the grammars being built for x86 computers.

and finally this module does not depend on any tree sitter executable as all the grammars are prebuilt, Its only needed if you plan on building the grammars for yourself which is only needed if you use m1 macbooks

- Jeet

2021-12-26 03:31 UTC, otavioschwanck commented
> @otavioschwanck I can’t repro, I have been testing this module on a ruby project and its been working fine, does the same error appear on other languages?
> 
> Have you tried doom syncing again?
> 
> also are you using the m1 macbooks as that is known not to work due to the grammars being built for x86 computers.
> 
> and finally this module does not depend on any tree sitter executable as all the grammars are prebuilt, Its only needed if you plan on building the grammars for yourself which is only needed if you use m1 macbooks
> 
> * Jeet

i'm using m1.   I hope to have a way to use on m1 any time soon.

2021-12-26 15:53 UTC, jeetelongname commented
there is some work to make some self build infrastructure but its not done, I may start working on some simple alternatives in the interum tho as there are a few m1 users, (I should probably add a warning to the readme as well

2021-12-28 14:48 UTC, aisamu commented
Just tested it on typescript & json: works _beautifully_, thanks a lot for taking the time to make this happen!

I was also able to use "parameter.inner" on javascript, overwriting the existing `evil-inner-arg`:

```diff
modified   modules/tools/tree-sitter/config.el
@@ -32,2 +32,3 @@
   (map! (:map +tree-sitter-inner-text-objects-map
+         "a" (evil-textobj-tree-sitter-get-textobj "parameter.inner")
          "f" (evil-textobj-tree-sitter-get-textobj "function.inner")
```
Would it possible to enable it on a per-lang basis? [(some languages don't have that implemented)](https://github.com/nvim-treesitter/nvim-treesitter-textobjects#built-in-textobjects)

2021-12-28 15:08 UTC, jeetelongname commented
if langs don't implemenet a text object I see that as an excuse to add the queries to said languages, I have been meaning to add more but have not mainly due to fear of conflicts, but I don't mind adding more

2022-01-03 06:50 UTC, amosbird commented
Do we have ways to inspect the object under the cursor which tree-sitter faces should be applied? I'm trying to debug why the returning type of some methods in c++ are not rendered properly.

![image](https://user-images.githubusercontent.com/5085485/147905353-f6215d0f-3915-4ec4-aab9-4ba914280d91.png)

2022-01-03 14:57 UTC, meain commented
@amosbird This is what I usually do. Call `customize-face` with the cursor on top and that will give me the name of the face. You can also run `tree-sitter-debug-mode` which will open up the parsed tree for the current buffer in a separate buffer which you can use to check what the node is and then if necessary add custom highlighting. https://emacs-tree-sitter.github.io/syntax-highlighting/customization/ (not sure if there is a doom specific way of doing this).

2022-01-03 17:12 UTC, meain commented
That message is supposed to happen the second time(toggling it off) you call `tree-sitter-debug-mode`. Make sure there is no buffer getting created in between

https://user-images.githubusercontent.com/14259816/147959228-d17df285-faef-4680-9597-834dd7f4b591.mp4

.

2022-01-04 01:35 UTC, jeetelongname commented
@amosbird I use `SPC h '` to inspect the faces, it should tell you what faces are being applied to the character, You can also inspect the tree with `tree-sitter-debug-mode` as meain has mentioned, I have been using it with this module for pretty much its entire development and its worked fine so if this problem persists let me know

2022-01-12 03:52 UTC, yqrashawn commented
Hi , I find some minor issues with ts-fold integration.

At this line https://github.com/MetaMask/metamask-extension/blob/88faef7e19228652e2bfb339ffc3392926ee985d/app/scripts/controllers/transactions/tx-gas-utils.js#L34

when tree-sitter-mode is enabled, I can only fold/unfold at the open bracket
![image](https://user-images.githubusercontent.com/15090582/149060198-29421d26-3287-495d-8e24-4d52cf4bacbf.png)
when tree-sitter-mode is disabled, I can fold/unfold at any point of this line

Another issue is I use `hs-level-hide` a lot since there's no doom `+fold/.*` functions for that. the `(+fold--ts-fold-p)` cond in `+fold/.*` functions brakes them after `hs-level-hide`

2022-01-12 20:13 UTC, jeetelongname commented
ts-fold needs some work which I need to get to. It does not bother me because my folding is quite simple but can be easily disabled with a `(package! ts-fold :disable t)`

As for your second point I am not sure I understand. Does it break hs-level-hide? Or does it break one of the fold functions?

2022-01-13 02:22 UTC, yqrashawn commented
> As for your second point I am not sure I understand. Does it break hs-level-hide? Or does it break one of the fold functions?

The behavior is folds created with `hs-hide-level` can't unfold by `+fold/toggle`
This might caused by the overlay.

The fold (created with `hs-hide-level`) behave this when I `(setq hs-set-up-overlay 'ignore)`

![Screenshot-2022-01-13-10 19 48](https://user-images.githubusercontent.com/15090582/149254369-dca44bcf-d33a-4a69-98a6-b8e408aa0bd5.gif)

2022-01-13 15:25 UTC, jeetelongname commented
thats because `+fold/toggle` will just run the first folder that returns true and not fall through, I am not really sure if this is a bug as mixing folders usually does not go all to well and adding that ability to `+fold/toggle` will probably add in more bugs than it solves, Still `hs-toggle-hiding` works if you want to unfold that and if you disable `ts-fold` then `+fold/toggle` will revert back to using hideshow

2022-01-18 02:48 UTC, amosbird commented
When tree-sitter is enabled, sometimes `C-s` key gets mapped to an action which leads to `font-lock-fontify-keywords-region: No match 1 in highlight (1 'font-lock-constant-face prepend)` .

2022-01-18 14:07 UTC, jeetelongname commented
@amosbird I will need more information, What language are you using, is `C-s` bound to isearch-forward? in what language? a better backtrace would also be helpful. From the little infomation I have gotten I can't reproduce, It may be a user error but I have too little information to speculate

2022-01-19 04:36 UTC, the-moriarty commented
About the problem with m1:

On vim, tree-sitter works perfectly.  Maybe it is a problem with emacs package of tree-sitter?

2022-01-19 06:24 UTC, ckruse commented
Tree-sitter support for M1 is blocked by elisp-tree-sitter. The code just doesn't fully support m1 yet, you can track it at [issue #197](https://github.com/emacs-tree-sitter/elisp-tree-sitter/issues/197) at the elisp-tree-sitter repo.

2022-01-19 10:41 UTC, jeetelongname commented
@the-moriarty thats because nvim compiles all of the grammers on your system while emacs will pull down prebuilt bins, as ckruse mentioned work is being done for this tho and hopefully soon m1 users will get support on this

2022-01-23 20:20 UTC, sei40kr commented
@jeetelongname 
I added the following snippet and got TypeScript TSX syntax highlighting working.

```emacs-lisp
(add-to-list 'tree-sitter-major-mode-language-alist '(typescript-tsx-mode . tsx))
```

2022-01-23 20:23 UTC, jeetelongname commented
@sei40kr what about text object support? I will need to spin up a dummy tsx project to test it (so a link to one would be nice) if that works Ill add it and consider tsx supported

2022-01-23 20:25 UTC, sei40kr commented
@jeetelongname 
> what about text object support?

Sorry I didn't test it. I'm going to test it tomorrow if I have time.

Here is my Typescript (TSX) project:
https://github.com/sei40kr/yong-ju.me

2022-01-23 21:22 UTC, jeetelongname commented
@sei40kr Thats cool ill also give it a test tomorrow and if all goes well then ill add support and keep an eye on it. Ill have to see why thats the case and if there are some underlying problems that may be blockers but hopefully all goes well

2022-01-24 13:27 UTC, sei40kr commented
@jeetelongname 
None of Treesitter text objects did work...

Here is my diff:

```diff
diff --git a/modules/lang/javascript/config.el b/modules/lang/javascript/config.el
index 35fe81182..54a483dae 100644
--- a/modules/lang/javascript/config.el
+++ b/modules/lang/javascript/config.el
@@ -125,7 +125,16 @@
     (define-derived-mode typescript-tsx-mode web-mode "TypeScript-TSX")
     (when (featurep! +lsp)
       (after! lsp-mode
-        (add-to-list 'lsp--formatting-indent-alist '(typescript-tsx-mode . typescript-indent-level)))))
+        (add-to-list 'lsp--formatting-indent-alist '(typescript-tsx-mode . typescript-indent-level))))
+    (when (featurep! +tree-sitter)
+      (after! tree-sitter
+        (add-to-list 'tree-sitter-major-mode-language-alist '(typescript-tsx-mode . tsx))
+
+        ;; tsx grammer doesn't work with the highlighting provided by
+        ;; font-lock-keywords.
+        ;; https://github.com/emacs-tree-sitter/tree-sitter-langs/issues/23
+        (setq-hook! 'typescript-tsx-mode-hook
+          tree-sitter-hl-use-font-lock-keywords nil))))
 
   (set-docsets! '(typescript-mode typescript-tsx-mode)
     :add "TypeScript" "AngularTS")
@@ -317,6 +326,7 @@ to tide."
                js2-mode-hook
                js3-mode-hook
                typescript-mode-hook
+               typescript-tsx-mode-hook
                rjsx-mode)
              #'turn-on-tree-sitter-mode
              #'+tree-sitter-keys-mode))
```

2022-01-24 15:54 UTC, meain commented
@sei40kr I don't have a doom setup, but adding something like below should work for `evil-textobj-tree-sitter`. I can maybe add this to the default list as well.

```emacs-lisp
(add-to-list 'evil-textobj-tree-sitter-major-mode-language-alist '(typescript-tsx-mode . "tsx"))
```

2022-01-24 19:12 UTC, jeetelongname commented
I am also not sure where typescript-tsx-mode is coming from. looking into it there is no real associated file or anything

2022-01-24 19:14 UTC, sei40kr commented
@jeetelongname 
I stole typescript-tsx-mode from Spacemacs, and it’s actually web-mode.

It’s defined in modules/lang/javascript/config.el.

2022-01-25 19:32 UTC, jeetelongname commented
Yep sounds good Ill push the changes for this, Ill also see if web mode can be supported with a similar trick

2022-02-02 14:10 UTC, the-moriarty commented
Hi, can you bump tree-sitter to 258eaa98c95b0afce12bfc1a87e6e9d23b13ba8c and remove the M1 mac comments ?  They fixed!

2022-02-02 23:39 UTC, jeetelongname commented
Will do!

2022-02-03 01:31 UTC, jeetelongname commented
@the-moriarty I have bumped the module, if you could give it a test (it also looks like that the CI is set up for arm) you will need the rust tool chain if you do need to compile the dynamic module. CC @otavioschwanck @elken

2022-02-03 02:27 UTC, the-moriarty commented
The text objects are not working in ruby-mode:

![image](https://user-images.githubusercontent.com/97059083/152271255-b2ad36ee-b43e-4595-a8d7-1ab9bab7b91c.png)

The text-objects are disabled by default?

2022-02-03 03:52 UTC, the-moriarty commented
Some throughs about how its configured:

the `i` text object is very important.   The tree-sitter version of it is very different (conditional), maybe another key for it?

the `a` text object is different on tree-sitter.  On tree-sitter is only for parameters in definition.  The arguments from functions call are excluded.  Here we can three options:

1. Bring back old behaviour
2. On tree-sitter-mode, push a function to detect parameters AND arguments. (that is what `a` does now)
3. Create or own function to do number 2.

2022-02-03 04:23 UTC, meain commented
Regarding 2, not sure if that is what you want to do by default, but in `evil-textobj-tree-sitter` you can specify multiple textobjects and we will match the first one that we can find in the buffer.

```emacs-lisp
(define-key evil-outer-text-objects-map "a" (evil-textobj-tree-sitter-get-textobj ("conditional.outer" "loop.outer")))
```

2022-02-03 04:41 UTC, the-moriarty commented
> Regarding 2, not sure if that is what you want to do by default, but in `evil-textobj-tree-sitter` you can specify multiple textobjects and we will match the first one that we can find in the buffer.
> 
> ```emacs-lisp
> (define-key evil-outer-text-objects-map "a" (evil-textobj-tree-sitter-get-textobj ("conditional.outer" "loop.outer")))
> ```

the current `a` looks for argument_list and parameters.   In this case it should be each argument item list, that can be anything.  dont know how to do it

2022-02-03 11:51 UTC, jeetelongname commented
@the-moriarty if there is another key for it then I am happy to replace it (forgive me as I don't use i) 
@meain I have bound a to parameter but do not mind adding another, at the moment there is also the `F` text object for funcion calls but I can add that to the param object as well (or remove `F`

2022-02-03 14:18 UTC, meain commented
I'll leave the keybindings and everything up to you. Just wanted to let you know that there is an option to provide multiple textobjects in the function.

2022-02-03 15:03 UTC, jeetelongname commented
I did not know that, it should be helpful in sorting some defaults

2022-02-03 16:21 UTC, the-moriarty commented
> @the-moriarty if there is another key for it then I am happy to replace it (forgive me as I don't use i) @meain I have bound a to parameter but do not mind adding another, at the moment there is also the `F` text object for funcion calls but I can add that to the param object as well (or remove `F`

move the parameter from `a` to `A` or make it works like the old `a` (working with argument_list (it would be 10/10)).

move the conditional from `i` to `v`, is free to use.

2022-02-15 19:56 UTC, jeetelongname commented
@the-moriarty those text objects hve been rebound now, if you have any more suggestions lemme know

2022-02-22 16:12 UTC, shaunsingh commented
Hi, this module errors out if you aren't using the `evil` module, due to the following lines: https://github.com/jeetelongname/doom-emacs/blob/4662722bbb88e1c038c3734db0c5bd1b4f9aa3f1/modules/tools/tree-sitter/config.el#L17-L28

Should this only run if you have `evil` enabled?

2022-02-22 17:59 UTC, jeetelongname commented
Thanks! Sorry for that bit of oversight

2022-03-10 12:38 UTC, sei40kr commented
FYI I've created a PR that just maps `terraform-mode` to `hcl` syntax in [tree-sitter-langs](https://github.com/emacs-tree-sitter/tree-sitter-langs). ( https://github.com/emacs-tree-sitter/tree-sitter-langs/pull/85 )

2022-03-28 07:15 UTC, peterhoeg commented
FYI, `tree-sitter-langs` also has queries for `hcl`, ie the terraform language.

2022-03-28 13:48 UTC, jeetelongname commented
I shall add support for that in a bit, I will need to bump the module as well. (there are also some load order issues I need to deal with) 

Thanks for letting me know!

2022-03-31 04:09 UTC, otavioschwanck commented
Solidity released a tree-sitter parser, can you add ?

2022-03-31 04:16 UTC, meain commented
@otavioschwanck Adding new languages is to be done in https://github.com/emacs-tree-sitter/tree-sitter-langs

2022-04-01 17:37 UTC, jeetelongname commented
Yes what meain said, for the moement I am just depending on tree sitter langs but am happy to bump the module when it supports it

2022-04-01 19:20 UTC, hlissner requested changes
Looking good! Besides the smaller nitpicks I've pointed out in my review, here are three larger-scale issues I'd like to see resolved:

1. Adding `turn-on-tree-sitter-mode` and `+tree-sitter-keys-mode` to mode hooks is repeated across many modes. Like the `:tools lsp` module, this would be better wrapped up in [an autodef's hook function](https://github.com/hlissner/doom-emacs/blob/master/modules/tools/lsp/autoload/common.el#L4-L10). For example:

   ```lisp
   ;; in modules/tools/tree-sitter/autoload.el

   ;;;###autodef
   (defun tree-sitter! ()
     (turn-on-tree-sitter-mode)
     (+tree-sitter-keys-mode +1))
   ```

   This would give us more freedom to modify/refactor this later.

2. Instead of adding `tree-sitter!` to `MAJOR-MODE-hook`, add it to `MAJOR-MODE-local-vars-hook` instead. This hook won't trigger for trivial cases (e.g. when org exports src blocks, or packages turn on a major mode in a temp buffer for parsing, etc). 

3. Please move changes to module documentation (except for the tree sitter module's README.org and `docs/modules.org`) to the `rewrite-docs` branch, in another PR. Or at the very least, revert them for now, and they can be done later, once that branch has been merged (won't be long now).

2022-04-01 19:20 UTC, hlissner commented on modules/editor/fold/README.org
> ++ [[https://github.com/jcs090218/ts-fold][ts-fold]]* (=:tools tree-sitter=)
Please move this to the `rewrite-docs` branch (in another PR).

2022-04-01 19:20 UTC, hlissner commented on modules/editor/fold/autoload/fold.el
> +  (and tree-sitter-mode
```diff
-(and tree-sitter-mode
+(and (bound-and-true-p tree-sitter-mode)
```

Otherwise, this will throw an error when the tree-sitter module is disabled/before tree-sitter is loaded.

2022-04-01 19:20 UTC, hlissner commented on modules/editor/fold/autoload/fold.el
> +                 (outline-show-all)))))))
Get rid of the leading `t`, as it serves no purpose. E.g.

```diff
-        (t (save-excursion
+        ((save-excursion
```

And re-indent the rest of the block.

2022-04-01 19:20 UTC, hlissner commented on modules/editor/fold/autoload/fold.el
> +                (hs-hide-all)))))))
Use `if` for cases with only two branches. E.g.

```lisp
(if (+fold--ts-fold-p)
    (ts-fold-close-all)
  (when (featurep 'vimish-fold)
    ...)
  ...)
```

2022-04-01 19:20 UTC, hlissner commented on modules/editor/fold/autoload/fold.el
> +                               (ovs (seq-filter
`seq` is not guaranteed to be loaded in interactive sessions, but `cl-lib` is, so `s/seq-filter/cl-remove-if-not`.

2022-04-01 19:20 UTC, hlissner commented on modules/lang/javascript/config.el
> +        ;; https://github.com/emacs-tree-sitter/tree-sitter-langs/issues/23
Use short form references:

```diff
        ;; HACK: the tsx grammer doesn't work with the hightlighting provided by
-       ;; font-lock-keywords.
-       ;; https://github.com/emacs-tree-sitter/tree-sitter-langs/issues/23
+       ;; font-lock-keywords. See emacs-tree-sitter/tree-sitter-langs#23
```

2022-04-01 19:20 UTC, hlissner commented on modules/lang/javascript/config.el
> +               js3-mode-hook
Remove `js3-mode-hook` and `javascript-mode-hook` from this list. 

- js3-mode is not our jurisdiction (none of our modules install it), so best we don't enforce our opinions on it in case the user installs it.
- javascript-mode is an alias for js-mode.

2022-04-01 19:20 UTC, hlissner commented on modules/lang/sh/config.el
> +                  :dot "." :dot "source")
Unwarranted formatting. Please revert this.

2022-04-01 19:20 UTC, hlissner commented on modules/tools/tree-sitter/config.el
> +    :keymap +tree-sitter-keys-mode-map))
There's a level of indirection here I'm not sure is necessary. Please bind these onto `tree-sitter-mode-map` instead. If this was done to make it easier to disable, the `:editor evil +everywhere` check is enough for now. Plus, these few keybinds are already easily reversed if not desired.

2022-04-01 19:20 UTC, hlissner commented on modules/tools/tree-sitter/config.el
> +    :keymap +tree-sitter-keys-mode-map))
As these are part of the module's evil configuration, can they be moved into the `:config` of `evil-textobj-tree-sitter`?

2022-04-02 00:52 UTC, jeetelongname commented on modules/tools/tree-sitter/README.org
> +implement that predicate the elisp tree sitter core
This should actually be redundent now, ill remove it.

2022-04-03 17:56 UTC, jeetelongname commented
Now all I need to do is figure out these load order issues and probably some other stuff

2022-04-19 02:33 UTC, jackmac92 commented
I'm eager to start working with tree-sitter, and planning to merge this PR in my local doom. I understand it's not done released yet, but can provide a backtrace if I run into a bug

let me know if there's any particular area where testing would be helpful!

2022-04-19 18:29 UTC, jeetelongname commented
Please do! I am currently working on figuring out how its being eagar loaded (which it should not) so if you do find out whats causing that it would be a great help!

2022-05-01 12:53 UTC, bhankas commented
I only skimmed the code so forgive me if I missed something obvious, but at tree-sitter grammar exists for couple of languages that I use and I see it missing from changes namely:

1. Nix: https://github.com/cstrahan/tree-sitter-nix
2. Beancount: https://github.com/polarmutex/tree-sitter-beancount

We already have LSP flags for both of these modules, and tree-sitter will be nice addition. Will it be possible to include them in this PR?

2022-05-03 01:09 UTC, jeetelongname commented
At the moment grammers are only installed through tree sitter langs, I have not added in my own grammers tho it is possible, I would recommend adding them to tree sitter langs instead of doom installing them directly.

That being said I will mess with it and write up some instructions on how to do so for people

2022-05-03 02:27 UTC, bhankas commented
If you mean this repo: https://github.com/emacs-tree-sitter/tree-sitter-langs/tree/master/repos

It does not have beancount, but does have Nix.

Either way, instructions will be fine too. Thanks for taking time to implement this!

2022-05-03 13:28 UTC, jeetelongname commented
if it does and it comes in the next bump ill add nix into the fold. then again I might have missed something so I will check

2022-05-07 08:53 UTC, VitalyAnkh commented
There is a [feature/tree-sitter](https://git.savannah.gnu.org/cgit/emacs.git/log/?h=feature/tree-sitter) branch in the emacs repository and Doom could make use of this in the future.

2022-05-08 02:33 UTC, jeetelongname commented
I am aware, I am waiting for it to mature and or the ecosystem to begin to move over before I even consider moving over the module

2022-05-22 20:36 UTC, jeetelongname commented
That should be the final thing, Lets see, I hope to get this merged in the next couple of days / weeks. thanks again to everyone who has helped and commented. Your awesome!

2022-05-24 11:33 UTC, gagbo commented on modules/tools/tree-sitter/config.el
> +         "l" (+tree-sitter-goto-textobj "loop.outer")))
The navigation bindings aren't mentioned in the README in a nice table like the text-objects. Just marking this quickly not to forget, we can PR it later anyway (especially if you want to change those)

2022-05-24 15:29 UTC, meain commented on modules/tools/tree-sitter/config.el
> +         "v" (+tree-sitter-get-textobj "conditional.outer")
Just a small nitpick. As of now `conditional.outer` uses `v` as mapping when selecting a textobj and `i` in case of goto. It would be better if they were consistent.

2022-05-24 17:45 UTC, jeetelongname commented on modules/tools/tree-sitter/config.el
> +         "v" (+tree-sitter-get-textobj "conditional.outer")
I was thinking that, I did not change it now mainly because I set it a while ago and did not feel like making a breaking change without some kind of discussion. 

If I were to make a case for keeping it. in practice the usage is so different it would not matter if they have slightly different semantics. I think being closer to mnemonics where I can (I can't use `i` as a text object but can for navigation) takes precedent over consistency but I can also see the other side.

2022-05-25 09:12 UTC, meain commented on modules/tools/tree-sitter/config.el
> +         "v" (+tree-sitter-get-textobj "conditional.outer")
I think it would be a good idea to have a discussion around it since we are in the last stages. Plus as this is not yet merged in, I don't think it would be that bad to change the defaults. The way I see it, a specific key is bound to a textobj, for example `f` for `function` and now any operation that you want to do on a `function` uses that key.

I might be missing something here, but why exactly can't we use `i` for nav?

*In any case I don't use doom, so I'll let the final decision up to you*

2022-05-25 15:30 UTC, jeetelongname commented on modules/tools/tree-sitter/config.el
> +         "v" (+tree-sitter-get-textobj "conditional.outer")
Yes I agree, I am but one man and my defaults may not represent sane defaults.

I can see the way you think, and for the most part I don&rsquo;t want to break that convention, its why I have tried to keep them both mnemonic and consistent, but (and this is my opinion) trying to keep them mnemonic is more important, its why I did use `i` for nav instead of `v`. I can&rsquo;t use `i` for the text object because *apparently* its a very important and useful text object (I have genuinely never used it). I can use it for nav as its a blank slate and as I have mentioned I find that navigation and text object use very different so I am not sure the semantics carry.

That being said I can also see it the other way in so far that you said, all operations with some kind of structure should use the same key.

2022-05-26 20:32 UTC, hpfr commented on modules/tools/tree-sitter/config.el
> +         "v" (+tree-sitter-get-textobj "conditional.outer")
The way I see it, users will have to internalize the anti-mnemonic `v` binding anyway, so using `i` only when available only increases complexity and isn't worth the mnemonic benefit.  If you're choosing between learning two bindings and one of the two, I think you should go with the one, even if it's the more difficult of the two, since you still come out ahead of learning two.

2022-05-26 22:43 UTC, jeetelongname commented on modules/tools/tree-sitter/config.el
> +         "v" (+tree-sitter-get-textobj "conditional.outer")
thats a good point, one final breaking change for the road then I guess.

2022-06-17 20:53 UTC, hlissner approved these changes

2022-06-17 20:55 UTC, merged

2022-06-17 21:16 UTC, hlissner commented
And done! Great work @jeetelongname. And thank you to everyone for your help shaping this module with your input and reviews (and putting up with my delays). I'm happy with how it turned out, and look forward to putting it through its paces!

2022-07-12 16:34 UTC, jeetelongname commented
tsx mode should be supported (and I have not heard any complaints in that regard). The reason I did not enable it for web mode was because while the same method would work, its a worse experience overall imo, both enabling ts in web-mode or defaulting to html-mode that is. It should be trivial to switch over though.

2022-07-17 21:50 UTC, mohammedzeglam-pg commented
> * playground on tree sitters website

i said i was use this hack and maybe the experience not perfect because tree-sitter not support injection so you do not get highlight for style  or  script tag but but i love the coloring from tree-sitter and it was the reason number one to use neovim back, but it think about writing new package to support this work