feat(eshell,vterm): add with-editor support
doomemacs/doomemacs pull request #5551
Opened 2021-10-02 10:32 UTC by iyefrat

This sets $EDITOR to emacsclient automatically from terminal sessions.
Even though with-editor supports term and shell, it's not added for
those by default because the exporting of the environmental variables is
visible when first opening the terminals for them (this is not the case
for eshell and vterm).

Ref magit/with-editor#101

-------

I think this is a very sensible default, however there are some things to consider:

For vterm, due to the way that `with-editor` clears the terminal after exporting the variables, they stay on the screen after opening the vterm for the first time for a fraction of a second (no such problem in eshell). Due to this, it may be desired to not have this on by default, in that case there are basically two other options:

1. have a `:term with-editor` module that turns this on for activated `:term` modules (or just `eshell` and `vterm` if on)
2. give each module a `+with-editor` flag that turns this on, with a warning in the `shell` and `term` readme's about the output.

On top of that, there is also the following recommended setup:
``` emacs-lisp
(define-key (current-global-map)
  [remap async-shell-command] 'with-editor-async-shell-command)
(define-key (current-global-map)
  [remap shell-command] 'with-editor-shell-command)
```
however it doesn't really neatly fit within `:term eshell` or `:term vterm`, so perhaps `:term with-editor` is the better way to go.

As for why to have this and not just have users set `$EDITOR` to `emacsclient`, from the [magit wiki](https://github.com/magit/magit/wiki/Emacsclient) it seems that in some cases this isn't a robust fix (it anecdotally works for me, but I have Emacs installed through nix). Also, people might not want `emacsclient` as their editor when they are in a standalone terminal, but when using a terminal inside Emacs the chances of that are slim to none imo.

2021-10-02 10:35 UTC, tecosaur commented
This looks nice!

2021-11-22 00:11 UTC, hlissner requested changes
The syntax for all your `add-hook!`'s are invalid. They need to be one of:

1. `(add-hook! 'X-mode-hook #'with-editor-export-editor #'with-editor-export-git-editor)`
2. `(add-hook! 'X-mode-hook '(with-editor-export-editor with-editor-export-git-editor))`

As they are now, you're adding the whole list as a single hook.

2021-11-22 22:56 UTC, iyefrat commented
Fixed. I've also updated the demo where I got the `#'(foo bar)` form from. What do you think about the other points raised in the top post?

2022-03-19 18:52 UTC, iyefrat commented
boop

2022-06-18 05:37 UTC, hlissner requested changes
Could you rebase the README changes out of this PR (so I can add them to the rewrite-docs branch instead)?

Also, I think this warrants a `:term with-editor`, since I'm not entirely willing to trust with-editor as a default. It introduces a couple fatal failure states that neither we nor with-editor handles gracefully. For example, if [`with-editor-emacsclient-executable`](https://github.com/magit/with-editor/blob/master/lisp/with-editor.el#L725) were nil (i.e. it fails to automatically find the emacsclient executable, for whatever reason).

> Also, people might not want emacsclient as their editor when they are in a standalone terminal

This could be worked around by checking for an envvar the user sets in their config. E.g. `(setenv "INEMACS" "1")` in `$DOOMDIR/config.el` and in their shell dotfiles:

```sh
[ -n "$INEMACS" ] && EDITOR=emacsclient
```

I'm inclined to treat this as the best option, but I suppose it's best left it to the user.

2022-06-18 05:40 UTC, hlissner requested changes
Oh, sidenote: git trailers should be separated with a colon, i.e.

```diff
-Ref magit/with-editor#101
+Ref: magit/with-editor#101
```

2022-07-09 16:39 UTC, iyefrat commented
I've pushed an update that adds a `+with-editor` flag, fixes the commit message, and removes the README updates (to be added in a PR to `docs-rewrite` after this gets merged).

There is an issue with the current implementation, it doesn't seem to play super nice with having the terminal in a popup window. for whatever reason the behavior is different for `vterm` and `eshell`: in `vterm` the git commit edit buffer gets opened in the popup window, and the git info in the main window. in eshell, both of them seem to be opened in the popup window. works fine when the terminal isn't a popup window though. this might be too big a QoL issue to merge at the moment, I'll look in to fixing it nonetheless.

2022-08-02 18:28 UTC, hlissner approved these changes

2022-08-02 18:34 UTC, hlissner commented
> in vterm the git commit edit buffer gets opened in the popup window, and the git info in the main window.

Perhaps this can be considered a more general bug with the popup module. See if this fixes the issue:

```elisp
(add-hook! 'server-switch-hook
  (when (+popup-window-p)
    (other-window)))
```

2022-10-29 20:08 UTC, iyefrat commented
> ```emacs-lisp
> (add-hook! 'server-switch-hook
>   (when (+popup-window-p)
>     (other-window 1)))
> ```
This doesn't really fix it: in `vterm` only the commit window seems to open (and still in the popup), in `eshell it opens a new window for the diff and opens the commit in the popup. Also, I'm getting errors when trying to run `$EDITOR foo` in a regular terminal, and when trying to run the command via `with-editor-shell-command` it tries and fails to open `nvim` for some reason. Overall I'm not really sure what's the cause of all these weird behaviors (or what was the state last time I looked in to this, it's been a while), it's unlikely that I'll manage to get this in good shape by the splitting deadline, so I'll close this for now. Once I work out all the kinks I'll just open a new version in the split repo.

2022-10-29 20:08 UTC, closed without merging