feat(vc): add next conflict in project to +vc/smerge-hydra
doomemacs/doomemacs pull request #5743
Opened 2021-11-07 04:35 UTC by daanturo

New hydra head:
`"n"` (subject to change) `(progn (smerge-vc-next-conflict) (recenter-top-bottom 0))`

Allow us to conveniently jump to the next merge conflict in current project without leaving the hydra and opening `magit`.

Alternative to #5431.

2022-05-03 04:31 UTC, daanturo commented
This PR still valid.

2022-05-03 23:46 UTC, hlissner requested changes
Sorry for the late response. Would you mind retargeting this PR onto `master` (and rebasing it)?

2022-05-04 07:19 UTC, tecosaur commented
@dangirsh what on earth does this have to do with Org, LaTeX, Vertico, or emacs-everywhere?

2022-05-04 07:29 UTC, daanturo commented
> @dangirsh what on earth does this have to do with Org, LaTeX, Vertico, or emacs-everywhere?

Ah... no, I don't remember requesting reviews from them, even if I did click, excuse me in that case.

> Sorry for the late response. Would you mind retargeting this PR onto `master` (and rebasing it)?

Done. But also I changed `(recenter-top-bottom 0)` to `(recenter-top-bottom (/ (window-height) 8))`, because the former doesn't let us view a little context above the conflict.

2022-05-04 08:58 UTC, dangirsh commented
> @dangirsh what on earth does this have to do with Org, LaTeX, Vertico, or emacs-everywhere?

No idea. Was this intended to be directed towards me?

2022-05-04 09:06 UTC, tecosaur commented
Ooops, sorry dangirsh I didn't notice GitHub autocompleted the wrong Dan 😅.

2022-08-02 18:27 UTC, hlissner approved these changes

2022-08-02 18:38 UTC, merged

2022-08-02 18:38 UTC, hlissner commented
Sorry for the _super_ late response. Thanks for your help!