feat(ruby): add new ruby plugins
doomemacs/doomemacs pull request #5821
Opened 2021-11-24 03:57 UTC by otavioschwanck

adding rails-routes, rails-i18n and ruby-json-to-hash.

Some awesome plugins to improve ruby on rails development workflow

2021-11-24 10:41 UTC, hlissner requested changes
For clarity's sake, please reword your commit to:

```
feat(ruby): add rails-routes, rails-i18n, & ruby-json-to-hash
```

2021-11-24 10:41 UTC, hlissner commented on modules/lang/ruby/config.el
> +  (rails-routes-global-mode))
By calling `rails-routes-global-mode` in `:init` you are eagerly loading `rails-route`. Please find a way to avoid this.

2021-11-24 10:41 UTC, hlissner commented on modules/lang/ruby/config.el
> +  (rails-i18n-global-mode))
By calling `rails-i18n-global-mode` in `:init` you are eagerly loading `rails-i18n`. Please find a way to avoid this.

2021-11-24 10:41 UTC, hlissner commented on modules/lang/ruby/config.el
> +        :map (ruby-mode-map web-mode-map)
`:after (ruby-mode web-mode)` means these keybinds won't be available until _both_ are loaded. You'll need two separate `map!`s for each map.

2021-11-24 10:41 UTC, hlissner commented on modules/lang/ruby/config.el
> +  (map! :after (ruby-mode web-mode)
`:after (ruby-mode web-mode)` means these keybinds won't be available until _both_ are loaded. You'll need two separate `map!`s for each map.

2021-11-24 10:41 UTC, hlissner commented on modules/lang/ruby/config.el
> -
2 blank lines are required between top-level use-package blocks.

2021-11-24 10:41 UTC, hlissner commented on modules/lang/ruby/config.el
2 blank lines are required between top-level use-package blocks.

2021-11-24 10:41 UTC, hlissner commented on modules/lang/ruby/config.el
> +
2 blank lines are required between top-level use-package blocks.

2021-11-24 10:41 UTC, hlissner commented on modules/lang/ruby/config.el
> +
2 blank lines are required between top-level use-package blocks.

2021-11-24 10:41 UTC, hlissner commented on modules/lang/ruby/config.el
> +
2 blank lines are required between top-level use-package blocks.

2021-11-24 14:06 UTC, otavioschwanck commented on modules/lang/ruby/config.el
> +  (rails-i18n-global-mode))
How can i change this?

(add-hook! 'doom-first-buffer-hook #'rails-i18n-global-mode) is enough?

2021-11-24 14:06 UTC, otavioschwanck commented on modules/lang/ruby/config.el
> +  (rails-routes-global-mode))
Any ideas?

(add-hook! 'doom-first-buffer-hook #'rails-routes-global-mode) is enough?

2021-12-26 21:59 UTC, gagbo commented on modules/lang/ruby/autoload.el
> +(add-hook 'doom-after-init-modules-hook '+ruby-tools-hooks-h)
Pretty sure this will break if the `+rails` feature is absent. Also, i’m a little afraid of eagerly loading ruby specific globalized minor modes unconditionally; but I don’t have the ruby module enabled so I don’t really mind anyway

2021-12-26 22:42 UTC, otavioschwanck commented on modules/lang/ruby/autoload.el
> +(add-hook 'doom-after-init-modules-hook '+ruby-tools-hooks-h)
i added a featurep.  Without this, the routes and i18n will not be saved on savehist and not gonna be loaded on next emacs start.

2022-01-07 03:51 UTC, jeetelongname commented on modules/lang/ruby/autoload.el
> +(add-hook 'doom-after-init-modules-hook '+ruby-tools-hooks-h)
Why can't they be loaded on `ruby-mode-hook`? That way they are only loaded when you actually are coding in some kind of ruby project.

2022-01-11 04:32 UTC, the-moriarty commented on modules/lang/ruby/autoload.el
> +(add-hook 'doom-after-init-modules-hook '+ruby-tools-hooks-h)
Just removed the modes and fixed in the package (found a better way to save)

2022-04-17 16:10 UTC, otavioschwanck commented
> ⚠️ **This pull request has been automatically marked stale due to 60 days of inactivity.** If this PR is still valid, please reply to it or it will be closed in 7 days.

reope

2024-09-11 23:46 UTC, closed without merging

2024-09-11 23:47 UTC, hlissner commented
Sorry for the tremendously late response. I've resolved and merged these changes in fc35b3c. Thanks for bringing it to my attention!