New module: os/exwm
doomemacs/doomemacs pull request #5966
Opened 2022-01-07 03:06 UTC by LemonBreezes

Hello everyone, I have written an EXWM module for Doom Emacs, which I hope you will all enjoy. 

Some features of note from this module are:
- Full Evil support for all EXWM buffers, with the entire suite of commands supported on Firefox-based and Chrome-based web browsers.
- The ability to edit any input field with Emacs using with language detection for selecting the appropriate major mode. 

I was going to include a feature for automatically creating/destroying workspaces for EXWM applications but decided not to include it in the initial pull request. This feature is a bit fiddly but has definitely made a strong positive impact on my workflow.

2022-01-07 03:21 UTC, jeetelongname requested changes
Hi! Thanks for your work, as mentioned "reasonable defaults" are up in the air for this module so it may be that this module does not get into doom core, that being said there is also the contrib repo coming for modules that are community maintained so this work will defo not go to waste.

anyway I have reviewed the module in so far and found some small things that need changing.

thanks for your work!

2022-01-07 03:21 UTC, jeetelongname commented on modules/os/exwm/README.org
> +#+TITLE:   private/exwm
Should this not be `os/exwm`?

2022-01-07 03:21 UTC, jeetelongname commented on modules/os/exwm/README.org
> +# A list of linked plugins
This should probably be removed

2022-01-07 03:21 UTC, jeetelongname commented on modules/os/exwm/README.org
> +:PROPERTIES:
Don't think this property tag is meant to be here

2022-01-07 03:21 UTC, jeetelongname commented on modules/os/exwm/README.org
> +:PROPERTIES:
Same here

2022-01-07 03:21 UTC, jeetelongname commented on modules/os/exwm/README.org
> +# Common issues and their solution, or places to look for help.
Remove this

2022-01-07 03:21 UTC, jeetelongname commented on modules/os/exwm/config.el
> +(use-package! exwm
You should not nest use-package! calls, instead use the `:after` keyword, they are functionally the same but the second is cleaner and more importantly doom convention

2022-01-07 03:21 UTC, jeetelongname commented on modules/os/exwm/packages.el
> +(when (featurep! :editor evil)
Should probably be `evil +everywhere`

2022-01-07 03:21 UTC, jeetelongname commented on modules/os/exwm/packages.el
> +;;; private/exwm/packages.el
again change to `os/exwm`

2022-01-07 03:21 UTC, jeetelongname commented on modules/os/exwm/config.el
> +;;; private/exwm/config.el -*- lexical-binding: t; -*-
Change to `os/exwm`

2022-01-07 03:21 UTC, jeetelongname commented on modules/os/exwm/autoload/exwm.el
> +;;; private/exwm/autoload/exwm.el -*- lexical-binding: t; -*-
change to `os/exwm`

2022-01-07 03:21 UTC, jeetelongname commented on modules/os/exwm/autoload/exwm-firefox.el
> +;;; private/exwm/autoload/exwm-firefox.el -*- lexical-binding: t; -*-
change to `os/exwm`

2022-01-07 03:21 UTC, jeetelongname commented on modules/os/exwm/autoload/exwm-edit.el
> +;;; private/exwm/autoload/exwm-edit.el -*- lexical-binding: t; -*-
change to `os/exwm`

2022-01-07 03:23 UTC, jeetelongname commented
also can you please rebase your branch to conform to our [git conventions](https://gist.github.com/hlissner/4d78e396acb897d9b2d8be07a103a854) I would also split this out into many commits detailing individual changes

2022-01-07 03:32 UTC, LemonBreezes commented
Thank you. I have just implemented the fixes you stated. I will work on splitting this into several commits following the Git conventions.

2022-01-07 03:38 UTC, jeetelongname commented
You don't need to close the PR you should be able to turn it into a draft which keeps it open but makes it clear its incomplete (it can't be merged until you put it up for review)

2022-01-07 03:53 UTC, LemonBreezes commented
> You don't need to close the PR you should be able to turn it into a draft which keeps it open but makes it clear its incomplete (it can't be merged until you put it up for review)

Ahh, thank you. I finally found that button. I am not very familiar with Git so it's going to take me a bit of time to figure this out.

2022-04-19 15:44 UTC, maikol-solis commented
Hi @LemonBreezes   

I work mostly with R projects, and I'm starting using [ESS](https://github.com/hlissner/doom-emacs/tree/master/modules/lang/ess). 

I would be super nice to have plots embedded inside doom-emacs using exwm. I just stumble upon with [this post ](https://emacs.stackexchange.com/a/42479/21501) and I'm wondering if this fits in your module. WDYT?

Thanks.

2022-04-20 15:57 UTC, LemonBreezes commented
> Hi @LemonBreezes
> 
> I work mostly with R projects, and I'm starting using [ESS](https://github.com/hlissner/doom-emacs/tree/master/modules/lang/ess).
> 
> I would be super nice to have plots embedded inside doom-emacs using exwm. I just stumble upon with [this post ](https://emacs.stackexchange.com/a/42479/21501) and I'm wondering if this fits in your module. WDYT?
> 
> Thanks.

Sure. That seems like an interesting alternative to using temporary files with `auto-revert-mode`. I am definitely interested in having interesting uses of EXWM added to this module. The module is currently living in [exwm-module-for-doom-emacs](https://github.com/LemonBreezes/exwm-module-for-doom-emacs). Soon I will close this pull request and redo this module for the master branch.

2022-05-15 04:33 UTC, LemonBreezes commented
So here is my status update: I have been working on this module privately. I plan to release it when Doom gets a public repository for modules. I've dropped support for non-Evil keybindings currently because I am using Evil again. The module is currently here https://github.com/LemonBreezes/exwm-module-for-doom-emacs, though if you want the latest updates, you can go directly to my private config https://github.com/LemonBreezes/.doom.d/tree/master/modules/private/exwm. I regularly have been making major changes so don't expect this module to be stable yet. That being said, this is a really cool project and I use it every day as my daily driver so I work on it regularly.

2022-08-04 14:50 UTC, oatmealm commented
Looking forward to this feature added. Thanks!

2022-11-01 16:00 UTC, closed without merging

2023-03-14 22:55 UTC, iT-Boyer commented
when run `M-x` or `recenterf file`：
```
Error in post-command-hook (ivy--queue-exhibit): (wrong-type-argument numberp t) 
```

2023-03-17 16:13 UTC, LemonBreezes commented
This module is outdated and needs to be rewritten.

2026-06-09 20:34 UTC, hlissner commented
As of v2.2, modules have been moved out of core, so module development has moved to [doomemacs/modules](https://github.com/doomemacs/modules) and [doomemacs/modules-contrib](https://github.com/doomemacs/modules-contrib). If you're still interested, the modules-contrib repo is ready to receive PRs like this one, given two small changes:

- The two commits be squashed into one, 
- The first line of the commit message be `module: add :os exwm` (to conform to our git conventions).

If you're not interested, that's fine too. Sorry for the trouble and thanks your for your interest!