feat(terraform): support terragrunt
doomemacs/doomemacs pull request #6247
Opened 2022-04-05 07:16 UTC by peterhoeg

Introduce a variable for the terraform executable and as terragrunt supports everything terraform does, use that instead of terraform if found on the path. 

We should probably also set `compile-command` - comments?

This doesn't touch the formatter in any way (ref https://github.com/hlissner/doom-emacs/issues/3921)

2022-06-12 14:12 UTC, peterhoeg commented
This should be relatively safe to merge. Any concerns?

2022-06-18 12:06 UTC, hlissner requested changes
Sorry for the delay; I've just been preoccupied. There's only one issue I have with this (mentioned below), otherwise it looks good to me.

2022-06-18 12:06 UTC, hlissner commented on modules/tools/terraform/config.el
> +        :desc (format "%s plan"  +terraform-runner) "p" (cmd! (compile (format "%s plan" +terraform-runner)))))
I'd recommend removing the prefix for these keys' labels (e.g. `:desc "apply"`, `:desc "init"`, etc), since it introduces a load order constraint for folks who change `+terraform-runner`. I.e. if they set the variable like in an `(after! terraform-mode ...)` block in their `$DOOMDIR/config.el` (which I recommend across the board), it'll be too late for these keybinds to see the change. They'd have to set it at top-level or in `$DOOMDIR/init.el`.

As shame we can't pass which-key a lambda to generate the label when they're read.

2022-07-13 09:28 UTC, peterhoeg commented on modules/tools/terraform/config.el
> +        :desc (format "%s plan"  +terraform-runner) "p" (cmd! (compile (format "%s plan" +terraform-runner)))))
That's a very good point. If we set `compile-command`, we will have the same problem (it not being reset if +terraform-runner is changed) - what's the proper way to deal with that?

2022-08-02 19:24 UTC, hlissner requested changes
Some commit history snuck into this PR. Would you mind rebasing it back onto master?

2022-08-03 01:35 UTC, peterhoeg commented
> Some commit history snuck into this PR. Would you mind rebasing it back onto master?

My bad - it’s the branch I’m running off. I will need to create a separate branch to avoid all the noise. Apologies.

2022-08-03 16:25 UTC, hlissner requested changes

2022-08-03 16:25 UTC, hlissner commented on modules/tools/terraform/config.el
> +  (setq-local compile-command +terraform-runner)
`setq-local` sets `compile-command` buffer-locally, but there's no telling what buffer will be "current" when this line gets evaluated. Please replace it with:

`(setq-hook! 'terraform-mode-hook compile-command +terraform-runner)`

2022-08-04 19:38 UTC, hlissner requested changes

2022-08-04 19:38 UTC, hlissner commented on modules/tools/terraform/config.el
> +  (setq-hook! terraform-mode-hook compile-command +terraform-runner)
`terraform-mode-hook` needs to be quoted:

```diff
-  (setq-hook! terraform-mode-hook compile-command +terraform-runner)
+  (setq-hook! 'terraform-mode-hook compile-command +terraform-runner)
```

2022-08-08 01:53 UTC, peterhoeg commented on modules/tools/terraform/config.el
> +  (setq-hook! terraform-mode-hook compile-command +terraform-runner)
Fixed

2022-08-08 16:35 UTC, hlissner approved these changes

2022-08-08 16:35 UTC, merged

2022-08-08 16:35 UTC, hlissner commented
LGTM. Thanks again for your help!