Add consult-tramp
doomemacs/doomemacs pull request #6260
Opened 2022-04-06 15:36 UTC by elken

Closes #6258

2022-04-06 16:43 UTC, hlissner requested changes

2022-04-06 16:43 UTC, hlissner commented on modules/completion/vertico/packages.el
> +        :pin "befa62baca768caa457b167e773b91f1bc7d661f")
Correct indentation (should be 2 spaces).

2022-04-06 16:43 UTC, hlissner commented on modules/completion/vertico/config.el
> +        :desc "Select TRAMP target" "f t" #'consult-tramp))
Move to `config/default/+evil-bindings.el` and mirror to `config/default/+emacs-bindings.el`

2022-04-06 16:43 UTC, hlissner commented on modules/completion/vertico/config.el
> +  :init
`s/:init/:config`.

2022-04-06 16:43 UTC, hlissner commented on modules/completion/vertico/config.el
> +  :after consult
Replace `:after consult` with `:defer t`. This package's sole entry point [is autoloaded](https://github.com/Ladicle/consult-tramp/blob/main/consult-tramp.el#L114), so it doesn't need to be loaded early.

2022-04-06 17:55 UTC, minad commented
Hey @elken, I think consult-tramp should actually be completion-tramp (see https://github.com/Ladicle/consult-tramp/issues/1), since in principle this works with arbitrary completion packages. Or are there plans to take advantage of actual Consult functionality (async, preview, narrowing)?

2022-04-07 06:58 UTC, elken commented
> Hey @elken, I think consult-tramp should actually be completion-tramp (see [Ladicle/consult-tramp#1](https://github.com/Ladicle/consult-tramp/issues/1)), since in principle this works with arbitrary completion packages. Or are there plans to take advantage of actual Consult functionality (async, preview, narrowing)?

I see your point and I actually do agree, the package isn't mine but it definitely seems like there's scope for improvement.

I'll amend Henrik's review (it was quite a rushed PR, in hindsight) and mull over other consult features to add in.

2022-04-08 07:09 UTC, elken commented
I think once [this](https://github.com/Ladicle/consult-tramp/pull/2) has been merged this should also be fine to merge (pending another Henrik review)

2022-04-08 08:17 UTC, elken commented
Converted to draft for now until the future of these changes is decided

2022-04-12 16:04 UTC, elken commented
Once https://github.com/karthink/consult-dir/pull/16 is merged, `consult-dir` will need a bump; making this PR redundant.

Would it be worth amending this to have `SPC f t` open a pre-filtered version of `consult-dir` or just closing this?

2022-05-06 13:15 UTC, iyefrat requested changes
Looks good, just a few requests:

1. the bump commit summary should be `bump: consult-dir`, since it just bumps that package.
2. The readme changes should be in a separate PR to the rewrite docs branch

2022-05-06 13:19 UTC, elken commented
> Looks good, just a few requests:
> 
>     1. the bump commit summary should be `bump: consult-dir`, since it just bumps that package.

That's what `doom/commit-bumps` filled out, but sure no worries

>     2. The readme changes should be in a separate PR to the rewrite docs branch

Yeah you're right, they're not strictly needed for this so I'll move them out

2022-05-06 13:48 UTC, iyefrat approved these changes

2022-06-03 16:59 UTC, iyefrat requested changes

2022-06-03 16:59 UTC, iyefrat commented on modules/completion/vertico/config.el
> +    (defvar consult-dir--source-tramp-docker
These don't follow the doom naming conventions

2022-06-03 17:00 UTC, elken commented on modules/completion/vertico/config.el
> +    (defvar consult-dir--source-tramp-docker
You're right, I verbatim copied them from my README changes

2022-06-03 17:13 UTC, elken commented on modules/completion/vertico/config.el
> +    (defvar consult-dir--source-tramp-docker
How's that?

2022-06-03 17:19 UTC, iyefrat commented on modules/completion/vertico/config.el
> +    (defvar consult-dir--source-tramp-docker
:+1:

2022-06-03 17:19 UTC, iyefrat commented on modules/completion/vertico/config.el
> +                        ("u" doom/help-package-homepage))
Just fix this bit (you need to load embark before you format)

2022-06-03 17:22 UTC, elken commented on modules/completion/vertico/config.el
> +                        ("u" doom/help-package-homepage))
Ah yeah, skimmed that my bad

2022-06-03 17:24 UTC, iyefrat approved these changes

2022-06-17 17:54 UTC, hlissner approved these changes

2022-06-17 17:57 UTC, merged