feat(dart): improve keybindings for better Flutter control
doomemacs/doomemacs pull request #6364
Opened 2022-05-05 00:57 UTC by victorblq

Improving the keybinds for Flutter control on a dart file buffer.

### Checklist
- [x] I've searched the issue tracker to ensure this was not PRed before.
- [x] My PR is not on [the do-not-PR list](https://doomemacs.org/d/do-not-pr) for this project.
- [x] My commits conform to [the git conventions](https://doomemacs.org/d/git-conventions).

2022-05-05 01:18 UTC, ericdallo reviewed
LGTM

2022-05-05 01:38 UTC, hlissner requested changes

2022-05-05 01:38 UTC, hlissner commented on modules/lang/dart/config.el
> +          "R" #'flutter-hot-restart))))
It's a mote busier than it needs to be, and is inconsistent with other uses of `map!` across Doom's codebase. Could you inline these and remove a level of parentheses?

I.e.
```lisp
  (map! :after dart-mode
        :map dart-mode-map
        :localleader
        (:prefix ("f" . "Flutter")
         :desc "Flutter run"         "f" #'flutter-run
         :desc "Flutter quit"        "q" #'flutter-quit
         :desc "Flutter hot reload"  "r" #'flutter-hot-reload
         :desc "Flutter hot restart" "R" #'flutter-hot-restart)))
```

(Side note: I'm not sure we _really_ need these descriptions, considering they (practically) match their command's names, but I'll revisit that when I get around to rethinking how Doom uses which-key)

2022-05-05 12:44 UTC, ericdallo commented on modules/lang/dart/config.el
> +          "R" #'flutter-hot-restart))))
Agreed, the command names are pretty clear and easier if user wants to debug a command

2022-07-22 21:02 UTC, hlissner approved these changes

2022-07-23 13:55 UTC, merged

2022-07-23 13:55 UTC, hlissner commented
Thanks for your help!