refactor(format): replace with apheleia
doomemacs/doomemacs pull request #6369
Opened 2022-05-05 14:48 UTC by elken

Replace format-all with apheleia to grealy simplify the formatting setup.

For the most part, this is a low degree of ready the only thing missing is documentation and more granular testing on each module.

I've also had a recent thought on how to handle LSP formatters, previously I ignored them in favour of apheleia but I might forward-port the same logic here for the new module.

2022-09-08 06:34 UTC, iyefrat commented
psst, your last commit is missing a scope

2022-09-08 06:36 UTC, elken commented
> psst, your last commit is missing a scope

shoo you

2022-09-25 16:45 UTC, VitalyAnkh commented
Could this module have an "only format changed region" function? Like the `clang-format+-context` in [clang-format-plust](https://github.com/SavchenkoValeriy/emacs-clang-format-plus) offers.

2022-09-25 18:13 UTC, elken commented
> Could this module have an "only format changed region" function? Like the `clang-format+-context` in [clang-format-plust](https://github.com/SavchenkoValeriy/emacs-clang-format-plus) offers.

The discourse post is the place for discussion

2022-11-16 16:19 UTC, offbyone reviewed
It looks like a whole bunch of these formatters depend on startup-time detection of formatting tools. At least for my workflow, I usually note the absence of the formatter, and install it, without restarting Emacs.

2022-11-16 16:19 UTC, offbyone commented on modules/lang/cc/config.el
> +  (when (executable-find "clang-format")
Does this mean that if I install `clang-format` while Emacs is running, I'll need to re-start it in order to enable formatting?

2022-11-16 16:23 UTC, elken commented on modules/lang/cc/config.el
> +  (when (executable-find "clang-format")
Maybe, but I'll just remove these now since apheleia just ignores if the exe is missing

2022-11-20 03:02 UTC, daanturo commented on modules/editor/format/config.el
> +  (setq-local apheleia-inhibit (or (eq major-mode 'fundamental-mode)
This may endup reverting `apheleia-inhibit` to nil if it was set to a non-nil value somewhere before.

We may do something like this instead?

```lisp

(defun +format-inhibit-maybe-h ()
  "Enable formatting on save in certain major modes.
This is controlled by `+format-on-save-disabled-modes'."
  (or (eq major-mode 'fundamental-mode)
      (string-empty-p (string-trim (buffer-name)))
      (not (null (memq major-mode +format-on-save-disabled-modes)))))

(when (modulep! +onsave)
  (add-hook 'apheleia-inhibit-functions #'+format-inhibit-maybe-h))

```

2022-11-20 08:43 UTC, elken commented on modules/editor/format/config.el
> +  (setq-local apheleia-inhibit (or (eq major-mode 'fundamental-mode)
Only if the user has specified to do so, so probably not.

2022-11-21 01:57 UTC, fosskers commented on modules/lang/fortran/config.el
> +    (set-formatter! 'fprettify '("fprettify" "-") :modes '(f90-mode fortran-mode)))
Since this module defines two `after!` blocks, I suspect this `set-formatter!` should be split into two as well.

2022-11-21 07:03 UTC, elken commented on modules/lang/fortran/config.el
> +    (set-formatter! 'fprettify '("fprettify" "-") :modes '(f90-mode fortran-mode)))
Okay, also reminded me to remove the now-redundant executable-find check

2022-12-02 15:27 UTC, daanturo commented on modules/editor/format/config.el
> +  (setq-local apheleia-inhibit (or (eq major-mode 'fundamental-mode)
> Only if the user has specified to do so, so probably not.

If anyone sets `apheleia-inhibit` to t in their `.dir-locals.el`
`.dir-locals-2.el` to disable auto-formatting for some reasons, then this will
surely revert it to nil when the conditions are met. I don't think we should
trigger surprising unwanted formats against the user's expected setting here.

As an alternative to using `apheleia-inhibit-functions`, we can check
`apheleia-inhibit` first

```emacs-lisp
(setq-local apheleia-inhibit (or  (bound-and-true-p apheleia-inhibit) ;; HERE, don't revert it from t to nil
                                  (eq major-mode 'fundamental-mode)
                                  (string-empty-p (string-trim (buffer-name)))
                                  (not (null (memq major-mode +format-on-save-disabled-modes)))))
```

But of course utilizing the above `-functions` hook just looks simpler, and even
when compared the original code.

2022-12-03 09:39 UTC, elken commented on modules/editor/format/config.el
> +  (setq-local apheleia-inhibit (or (eq major-mode 'fundamental-mode)
Still think this is quite an edge case but I've made the change anyway. Thanks :D

2023-03-27 01:44 UTC, peterhoeg commented
How far from completion is this? The existing format-all based module isn't that great and I would much prefer not having to work around it's warts locally since this will all be an non-issue in our new, glorious apheleia future.

2023-04-12 04:09 UTC, peterhoeg commented on modules/editor/format/autoload/settings.el
> +  (after! apheleia
I couldn't get this to trigger without changing `(after! apheleia` to `(after! apheleia-core`

2023-04-12 04:12 UTC, peterhoeg commented
Maybe I'm reading the documentation the wrong way but simply passing a string with the command like this 

```elisp
(set-formatter! 'nixpkgs-fmt "nixpkgs-fmt" :modes '(nix-mode))
```
fails with `apheleia--run-formatters: Formatter must be a shell command or a Lisp function: nixpkgs-fmt`.

Whereas passing a list works:

```elisp
(set-formatter! 'nixpkgs-fmt '("nixpkgs-fmt") :modes '(nix-mode))
```

2023-04-14 20:10 UTC, elken commented on modules/editor/format/autoload/settings.el
> +  (after! apheleia
Looks like this has recently been changed

2023-05-11 04:23 UTC, peterhoeg commented on modules/editor/format/config.el
> +             (+vc-gutter-init-maybe-h)))
This function is not defined if `(modulep! :ui vc-gutter +diff-hl)`

2023-05-26 06:37 UTC, peterhoeg commented on modules/editor/format/config.el
> +             (+vc-gutter-init-maybe-h)))
My workaround:
```elisp
(after! apheleia
  (unless (fboundp '+vc-gutter-init-maybe-h)
    (defsubst +vc-gutter-init-maybe-h () "Dummy to avoid apheleia dumping errors" nil)))
```

2023-07-24 17:57 UTC, hlissner requested changes
Is this ready to merge? There are a couple small issues, mainly to do with formatting and conventions, but rather than delay this any longer (this module has been the source of a lot of issues for quite some time now), I'd like to merge this now and polish it going forward.

2023-07-24 17:57 UTC, hlissner commented on modules/editor/format/packages.el
> +(package! apheleia)
Would you mind pinning this now?

2023-07-24 18:38 UTC, elken commented
> Is this ready to merge? 

Looks like there's some merge conflicts to resolve too but yeah it can be

> There are a couple small issues, mainly to do with formatting and conventions

Yeah, these should be standardised so that the elisp formatter can also accommodate them thus the project formats itself :stuck_out_tongue: 

> I'd like to merge this now and polish it going forward.

If you're sure :)

2023-07-24 18:39 UTC, elken commented on modules/editor/format/packages.el
> +(package! apheleia)
Yeah I'll add this in too

2023-08-21 16:19 UTC, offbyone commented
Where is this change sitting? It'd be great to get a path forward on formatting, as the existing format-all-the-code model is not serving my needs for Ruby development.

2023-09-06 11:32 UTC, peterhoeg commented
I've added this PR to my local fork and am very happily using it. Until there is official progress, that might be a workaround for you too.

2023-09-12 21:04 UTC, hlissner requested changes

2023-09-12 21:04 UTC, hlissner commented on modules/editor/format/config.el
> +             (+vc-gutter-init-maybe-h)))
1. Please fix the indentation (should be indented by 2 spaces).
2. Like @peterhoeg mentioned, this puts a hard dependency on git-gutter. Add a `(fboundp '+vc-gutter-init-maybe-h)` check to `+format--refresh-git-gutter-h`.

2023-09-12 21:04 UTC, hlissner commented on modules/editor/format/config.el
> +    (add-to-list 'apheleia-inhibit-functions #'+format-inhibit-maybe-h)))
Move the `modulep!` check outside the `after!` block.

2023-09-12 21:04 UTC, hlissner commented on modules/editor/format/autoload/settings.el
> +(cl-defun set-formatter! (name args &key modes filter)
Remove the `filter` argument, as it is unused.

2023-09-13 06:18 UTC, elken commented on modules/ui/vc-gutter/config.el
> +  (advice-remove #'switch-to-buffer #'git-gutter:switch-to-buffer)
No there is a conflict between apheleia and git-gutter [here](https://github.com/radian-software/apheleia/issues/115) so I also copied that from radon's config

2023-09-13 06:18 UTC, elken commented on modules/ui/vc-gutter/config.el
> +  (add-hook 'after-revert-hook #'+vc-gutter-update-h)
See above

2023-09-13 06:21 UTC, elken commented on modules/lang/common-lisp/config.el
> +    (after! sly (sly-lisp-indent-compatibility-mode)))
I don't remember writing this, but yeah I agree it's not good

2023-09-13 06:22 UTC, elken commented on modules/lang/clojure/config.el
> +    (set-formatter! 'cljfmt '("cljfmt" "fix" "-") :modes '(clojure-mode clojurec-mode clojurescript-mode)))
I definitely already have, must have snuck back in during rebasing

2023-09-13 09:04 UTC, elken commented on modules/editor/format/autoload/settings.el
> +(cl-defun set-formatter! (name args &key modes filter)
I left it in in case you wanted me to refactor it to add it in, but happy to just ignore it then

2023-09-13 09:04 UTC, elken commented on modules/editor/format/config.el
> +    (add-to-list 'apheleia-inhibit-functions #'+format-inhibit-maybe-h)))
Sure

2023-09-13 09:04 UTC, elken commented on modules/editor/format/config.el
> +             (+vc-gutter-init-maybe-h)))
Will do

2023-09-13 09:10 UTC, elken commented on modules/lang/zig/doctor.el
> +    (warn! "Formatting will be disabled")))
I imagine I wanted `unless` here yeah

2023-09-13 09:11 UTC, elken commented on modules/lang/sh/config.el
> +  :defer t)
Will it still be loaded correctly?

2023-09-13 09:13 UTC, elken commented on modules/lang/dhall/config.el
> +    (set-formatter! 'dhall-format '("dhall" "lint" "-") :modes '(dhall-mode)))
I wasn't sure how best to handle this, but okay I'll revert it to how it was for now

2023-09-13 19:11 UTC, hlissner commented on modules/lang/sh/config.el
> +  :defer t)
Yes. `fish-mode` [autoloads its entry points](https://github.com/wwwjfy/emacs-fish/blob/master/fish-mode.el#L703-L708).

2023-09-13 19:13 UTC, elken commented on modules/lang/sh/config.el
> +  :defer t)
Cool, I'll rebase that commit now then

2023-09-13 19:13 UTC, hlissner submitted a review, later dismissed

2023-09-13 23:18 UTC, hlissner approved these changes

2023-09-13 23:19 UTC, merged

2023-09-13 23:20 UTC, hlissner commented
Sorry for taking so long to get to this; this has been overdue a merge for a *long* time. Thanks again for your hard work and help!

2023-09-15 02:33 UTC, yufengwang commented
I got this error when using format/region, `Symbol’s function definition is void: apheleia--get-formatter-command`

2023-09-15 02:38 UTC, fosskers commented
@yufengwang As mentioned in the new documentation for the `format` module, region formatting is not currently supported by Apheleia.

2023-09-15 02:57 UTC, yufengwang commented
okay, is there any workaround? because i highly depend on ` format/region` on a very old codebase

2023-09-15 05:55 UTC, liaowang11 commented
> okay, is there any workaround? because i highly depend on ` format/region` on a very old codebase @fosskers

With this tweaks, it seems to be working for me.
```diff
@@ -8,7 +8,7 @@
 
 (defun +format-region (start end &optional callback)
   "Format from START to END with `apheleia'."
-  (when-let* ((command (apheleia--get-formatter-command
+  (when-let* ((command (apheleia--get-formatters
                         (if current-prefix-arg
                             'prompt
                           'interactive)))
@@ -23,7 +23,7 @@
       ;; Ensure this temp buffer seems as much like the origin buffer as
       ;; possible, in case the formatter is an elisp function, like `gofmt'.
       (cl-loop for (var . val)
-               in (cl-remove-if-not #'listp (buffer-local-variables origin-buffer))
+               in (cl-remove-if-not #'listp (buffer-local-variables cur-buffer))
                ;; Making enable-multibyte-characters buffer-local causes an
                ;; error.
                unless (eq var 'enable-multibyte-characters)
@@ -45,7 +45,9 @@
              ;; restore indentation without affecting new
              ;; indentation
              (indent-rigidly (point-min) (point-max)
-                             (max 0 (- indent (+format--current-indentation))))))
+                             (max 0 (- indent (+format--current-indentation)))))
+           (set-buffer-modified-p nil)
+           )
          (with-current-buffer cur-buffer
            (delete-region start end)
            (insert-buffer-substring-no-properties formatted-buffer)
```

2023-09-15 06:22 UTC, elken commented
In future, please use issues when reporting issues.

As for this change, I've tested it locally and it seems to "kind of" work but since as pointed out it's not supported upstream, if you're happy with this fix I'll PR it in.

2023-09-15 06:25 UTC, offbyone commented
@elken thank you for the work on this; it's working well for me, and I'm glad to have it in main.

2023-09-17 09:29 UTC, yufengwang commented
@elken  thanks for your hard work

2023-09-22 17:02 UTC, johalun commented
@yufengwang 

Hey! Please tell me how you got region formatting working. If I don't modify any settings `SPC c f` formats incorrectly (not using my .clang-format).

If I add `(setq +format-with-lsp nil)` I get the error `Symbol’s function definition is void: apheleia--get-formatter-command` for region formatting but full buffer formatting works.

I'm on latest master and the doom code does contain the changes above.

2023-09-23 06:34 UTC, elken commented
a) if you're having issues, report them through the proper channels
b) if you were using the latest master, you'd have #7427 which resolves that error so please update to the latest master

2023-09-24 08:53 UTC, yufengwang commented
@johalun I have submit a new issue, it still has bugs, https://github.com/doomemacs/doomemacs/issues/7438

2024-01-04 04:18 UTC, lroolle commented on modules/editor/format/autoload/format.el
> -(defun +format--org-region (beg end)
@elken You may have removed the `+format--org-region` for some reason, but this is quite handy and, as far as I am concerned, I use it every day. Can i add it back in this module?