feat(dired): add +dirvish option
doomemacs/doomemacs pull request #6407
Opened 2022-05-19 05:20 UTC by zrquan

Add `dirvish` package to dired module.

Regarding the main difference with `renger.el`, please see this [discussion](https://github.com/alexluigit/dirvish/issues/10).

Fixes #6397

2022-05-19 13:58 UTC, numkem commented
This is working great but it seems to be missing shortcuts. Maybe pair them to what ranger uses?

2022-05-19 14:53 UTC, zrquan commented
> This is working great but it seems to be missing shortcuts. Maybe pair them to what ranger uses?

Dirvish is a improved version of Dired (not ranger), it respect all your existing Dired keybindings. So I think there should be as few shortcuts as possible here.

2022-05-25 20:37 UTC, numkem commented
I meant more about a shortcut to start dirvish.

2022-05-26 04:57 UTC, ckruse commented
Dirvish is an enhancement to dired, you start it by starting dired

2022-06-17 14:56 UTC, iyefrat commented
dirvish seems to have an icon extension, it should probably be hooked into the `+icons` flag, both with turning it on and not using `dired-all-the-icons`

2022-06-17 14:58 UTC, iyefrat commented
same with `dirvish-vc` to mirror the `dired-git-info` behavior, which is on by default in the module

2022-06-17 14:59 UTC, iyefrat commented
Also, thanks for submitting this PR! dirvish looks very promising :)

2022-06-18 12:42 UTC, hlissner requested changes

2022-06-18 12:42 UTC, hlissner commented on modules/emacs/dired/config.el
> +              (featurep! +ranger))
Please replace with:

```elisp
:unless (featurep! +dirvish)
:unless (featurep! +ranger)
```

2022-06-18 12:42 UTC, hlissner commented on modules/emacs/dired/config.el
> +        ))
Please move up hanging parentheses.

```diff
-        "h" #'dired-omit-mode
-        ))
+        "h" #'dired-omit-mode))
```

2022-06-18 12:42 UTC, hlissner commented on modules/emacs/dired/config.el
> +  :init (dirvish-override-dired-mode)
use-package's :after keyword has [some load-order implications](https://github.com/jwiegley/use-package/issues/829), and is best avoided. Please replace these two lines with:

```diff
-  :after dired
-  :init (dirvish-override-dired-mode)
+  :defer t
+  :init (after! dired (dirvish-override-dired-mode))
```

It's certainly not as elegant, but I plan to replace our internal uses of `use-package` later to address these issues.

2022-06-23 11:46 UTC, hlissner approved these changes

2022-06-23 11:47 UTC, merged

2022-06-23 11:47 UTC, hlissner commented
LGTM. Thanks for your help!

2022-06-23 15:15 UTC, edgar-vincent commented
The author of `dirvish` [advises against using `dired-rsync`](https://github.com/alexluigit/dirvish/blob/main/CUSTOMIZING.org#use-dirvish-yank-instead-of-dired-rsync) and suggests using `dirvish-yank` instead. Should `dired-rsync` be disabled when `+dirvish` is used?

2022-06-28 16:03 UTC, zrquan commented
> The author of `dirvish` [advises against using `dired-rsync`](https://github.com/alexluigit/dirvish/blob/main/CUSTOMIZING.org#use-dirvish-yank-instead-of-dired-rsync) and suggests using `dirvish-yank` instead. Should `dired-rsync` be disabled when `+dirvish` is used?

Maybe you can submit a new PR 😉

2022-06-28 23:58 UTC, edgar-vincent commented
I will when I have a moment. Thanks again for your PR! I think dirvish is a great match for Doom :)