refactor(ess): update ess module
doomemacs/doomemacs pull request #6455
Opened 2022-06-14 15:35 UTC by maikol-solis

For the moment, this is just a draft. Any contribution is welcome.  A list of initial ideas are [in this post](https://discourse.doomemacs.org/t/ess-module-refactor/2681?u=mklsls). 

Fixes #0000
References #0000
Replaces #0000

-----
- [X] I searched the issue tracker and this hasn't been PRed before.
- [X] My changes are not on [the do-not-PR list](https://doomemacs.org/d/do-not-pr) for this project.
- [X] My commits conform to [the git conventions](https://doomemacs.org/d/git-conventions).
- [ ] My changes are visual; I've included before and after screenshots.
- [ ] Any relevant issues or PRs have been linked to.
- [X] This a draft PR; I need more time to finish it.

2022-06-27 10:47 UTC, hlissner requested changes
Including the other review requests further below, please make the following changes to the commit history (to conform with our [git conventions](https://discourse.doomemacs.org/t/git-conventions/2407)):

- About 5175cf586de3a5037da2d6f7ee0dc681f01431ab, if `ess-view-data` is a drop-in replacement for `ess-R-data-view`, then it should be a `refactor`, not a `feat`. If it *isn't* a drop-in replacement, it should be a *breaking* refactor: `refactor!(ess): ...` (see <https://discourse.doomemacs.org/t/git-conventions/2407#breaking-changes-7>)
- Another thing about 5175cf586de3a5037da2d6f7ee0dc681f01431ab: since you are replacing a package, please add a package diff line to your commit message:
  ```
  feat(ess): deprecate ess-R-data-view

  myuhe/ess-R-data-view.el@d6e98d3ae1e2 -> ShuguangSun/ess-view-data@6277684e06d5

  Use `ess-view-data` given the extensive support for multiple backends
  like base, dplyr, DT, kable, etc. Also, it seems that `ess-R-data-view`
  is in an unmaintained/stale state.
  ```
- Reword 783641241985c48ebe2bb2b9b46fb95671c75e43 to `nit(ess): reformat keybinds`, to be more specific.
- Change cfae4b0bea6e9273ca2cd0249321e4e8398e7a23 to `perf(ess): ...`; if it is indeed a change made solely to improve performance.

2022-06-27 10:47 UTC, hlissner commented on modules/lang/ess/config.el
> +      :server-id 'lsp-r-remote)))
This `lsp-register-client` calls needs to be deferred. It will throw a void-function error if `lsp-mode` isn't (hopefully) loaded by the time `ess` is loaded.

You can also get rid of this convoluted `featurep!` check by wrapping the `lsp-register-client` call in:

```elisp
(after! lsp-mode
  (lsp-register-client ...))
```

2022-06-27 10:47 UTC, hlissner commented on modules/lang/ess/config.el
> +  (setq comint-move-point-for-output t)
This has global side-effects. I would much rather we limit its scope to the repl buffer in question. For example, if the repl buffer is in `ess-repl-buffer-mode` (this is a guess, I leave it to you to replace it with the current mode) then:

```lisp
(setq-hook! 'ess-repl-buffer-mode-hook
  comint-scroll-to-bottom-on-input t
  comint-scroll-to-bottom-on-output t
  comint-move-point-for-output t)
```

2022-06-27 10:47 UTC, hlissner commented on modules/lang/ess/config.el
> +        :i "RET" #'ess-indent-new-comment-line
Careful here. This unintentionally moves all the `:localleader` keybinds below to `ess-roxy-mode-map`, so move these *above* the `:map ess-mode-map` to limit the damage:

```diff
+        :map ess-roxy-mode-map
+        :i "RET" #'ess-indent-new-comment-line
         :map ess-mode-map
         :n [C-return] #'ess-eval-line
-        :map ess-roxy-mode-map
-        :i "RET" #'ess-indent-new-comment-line
```

2022-07-04 03:07 UTC, maikol-solis commented
Thanks @hlissner for all your suggestions. I fixed all the problems in the commits. 
In the next days, I will experiment with other fixes in the module.

2023-06-04 05:23 UTC, mschilli87 commented
@maikol-solis: Thank you for your ongoing work on this. If there is any way how I can support you, feel free to ping me here.

2023-06-08 21:46 UTC, maikol-solis commented
Hi @mschilli87. Thank you very much for offering the help. I do really need it to finish this PR (I'm not a skilled lisp programmer). 

The main ideas are here https://discourse.doomemacs.org/t/ess-module-refactor/2681

Now, I wish to create an interface similar to RStudio (code, plots, variables, and console). I started a discussion in [discord](https://discord.com/channels/406534637242810369/1082041027373842453), but I haven't worked on that too much, to be honest. 

Please use the feature branch as much as you want, and let me know if you experience any issues or if you would like to add anything else. 

Thanks again for your kind help.

2024-03-06 09:08 UTC, hlissner commented
Hey there! Sorry for the long delay, this PR fell off my radar (also because it's still a draft). What is it's status? Is this PR ready for review?

2024-03-06 12:46 UTC, maikol-solis commented
> Hey there! Sorry for the long delay, this PR fell off my radar (also because it's still a draft). What is it's status? Is this PR ready for review?

Don't worry Henrik. I have worked a lot recently on the module, this is my fault actually. 

The three things that I think are missing are: 

1. Bump the module
2. Review the company/corfu mechanism, given the Corfu module is near to be merged. 
3. Solve this problem in my wishlist to have a Rstudio-like interface inside Emacs 

For the moment, my best try is something like this. But it doesn't work (it doesn't show the xwidget windown as expected). And if you call it twice, it destroys completely the windows layout. 

```elisp 
(defun my-rstudio-layout2 () ""
       (interactive)
       (let ((ess-startup-directory 'default-directory)
             (ess-ask-for-ess-directory nil))
         (ess-switch-to-ESS t)
         (hide-mode-line-mode)
         (ess-eval-linewise "dummy<<-NULL\n")
         (let ((browse-url-browser-function 'xwidget-webkit-browse-url))
           (ess-eval-linewise (concat "source(\"" doom-emacs-dir "modules/lang/ess/helpers.R\")\n"))
           (ess-eval-linewise ".start_hgd()" t t t t 0.1 0.1)
           (xwidget-webkit-browse-url (replace-regexp-in-string "\"" "" (ess-string-command "dput(.get_hgd_server_url)\n")))
           (hide-mode-line-mode))
         (ess-switch-to-ESS t)
         (ess-rdired)
         (hide-mode-line-mode)
         (ess-help "help")
         (hide-mode-line-mode)
         (let* ((source-buf (car (match-buffers '(and (derived-mode . ess-mode) "\\.[Rr]$"))))
                (plot-buf (car (match-buffers '(and (derived-mode . xwidget-webkit-mode) "R\\ Plot\\*$"))))
                (repl-buf (ess-get-current-process-buffer))
                (rdired-buf (get-buffer ess-rdired-buffer))
                (help-buf (car (ess-help-get-local-help-buffers))))
           (if source-buf
               (progn
                 (pop-to-buffer source-buf)
                 (condition-case nil (delete-other-windows) (error t))
                 (display-buffer-in-atom-window
                  repl-buf
                  `((window        . ,(get-buffer-window source-buf))
                    (side          . below)
                    (window-height . 0.5)
                    ;; (window-width  . 0.5)
                    ;; (window-height . ,#'fit-window-to-buffer)
                    (dedicated     . t)))
                 (display-buffer-in-atom-window
                  rdired-buf
                  `((window        . ,(get-buffer-window source-buf))
                    (side          . right)
                    (window-width  . 0.5)
                    (window-height . 0.5)
                    ;; (window-width  . ,(lambda (win)
                    ;;                     (fit-window-to-buffer win
                    ;;                                           nil nil
                    ;;                                           (floor (frame-width) 3)
                    ;;                                           40)))
                    (dedicated     . t)))
                 (display-buffer-in-atom-window
                  plot-buf
                  `((window        . ,(get-buffer-window repl-buf))
                    (side          . right)
                    ;; (window-width  . ,(lambda (win)
                    ;;                     (fit-window-to-buffer win
                    ;;                                           nil nil
                    ;;                                           (floor (frame-width) 3)
                    ;;                                           40))))
                    ))

                 nil)))
         )



       )
```

This is the helper.R function used above. 
```r
.start_hgd <- function() {
  if (!requireNamespace("httpgd", quietly = TRUE)) {
    install.packages("httpgd",
      repos = c(
        "https://nx10.r-universe.dev",
        "https://cloud.r-project.org"
      )
    )
  }
  httpgd::hgd(silent = TRUE)
}

.get_hgd_server_url <- function() {
  tryCatch(
    {
      url <- httpgd:::hgd_url()
      return(url)
    },
    error = function(e) {
      message("httpgd server not running. Starting httpgd server...")
      .start_hgd()
      url <- httpgd:::hgd_url()
      return(url)
    }
  )
}

```

1 and 2 are easy enough to be done in the short term. For 3 I still don't know how to glue the Emacs windows mechanism, with R and xwdigets, but I'll keep searching.

2024-04-04 23:22 UTC, KaiAragaki commented
Great work on this as always.

A couple issues that have plagued me (which are honestly probably upstream issues):
- Near invisible printing to terminal (https://github.com/emacs-ess/ESS/issues/1193). Workaround listed in comments.
- corfu sends empty lines to iESS seemingly at random, and occasionally the session gets locked completely (https://github.com/emacs-ess/ESS/issues/1226). I haven't found a way to resume the session - I have to kill the iESS process and open it up a new one. Verrrrry irritating. Workaround is to set `corfu auto` to `nil` which is kind of a non-solution, tbh.

Obviously none of these issues should prevent this PR, just bringing them to your attention. 

Thanks again for your great work.

2024-04-19 08:40 UTC, edvinsyk commented
> Great work on this as always.
> 
> A couple issues that have plagued me (which are honestly probably upstream issues):
> 
>     * Near invisible printing to terminal ([Printing a tibble removes all text faces emacs-ess/ESS#1193](https://github.com/emacs-ess/ESS/issues/1193)). Workaround listed in comments.
> 
>     * corfu sends empty lines to iESS seemingly at random, and occasionally the session gets locked completely ([iESS entering extra lines and freezing emacs-ess/ESS#1226](https://github.com/emacs-ess/ESS/issues/1226)). I haven't found a way to resume the session - I have to kill the iESS process and open it up a new one. Verrrrry irritating. Workaround is to set `corfu auto` to `nil` which is kind of a non-solution, tbh.
> 
> 
> Obviously none of these issues should prevent this PR, just bringing them to your attention.
> 
> Thanks again for your great work.

For anyone with similar issues or trying to debug this

Applying the fix from #6235 and using leader + m + b/D/l commands to send code to the REPL (instead of c-c c-c) seems to make the corfu-issues less prevalent with corfu-auto on. 

This might give some indication of where the error occurs.

2024-05-13 16:22 UTC, edvinsyk commented
I’m not sure how to best implement it, but I wonder if ess-julia-mode should be deactivated when the other julia module has been activated. In order to avoid conflicts/confusion between the two.

2024-08-31 02:44 UTC, hlissner requested changes
Side question: how does ESS fair with Corfu, by the way?

2024-08-31 02:44 UTC, hlissner commented on modules/lang/ess/config.el
> +      :server-id 'lsp-r-remote)))
With `lsp-auto-register-remote-clients` added (and set to `t` by default) in https://github.com/emacs-lsp/lsp-mode/commit/d45aca026addb5d0fa59bf63317762f79822f027, is this needed anymore?

2024-08-31 02:44 UTC, hlissner commented on modules/lang/ess/config.el
> +         ("\\.[Jj][Mm][Dd]\\'" . ess-jags-mode))
Most of these shouldn't be needed. ESS already autoloads them:

![image](https://github.com/user-attachments/assets/59d2380b-5aa6-468f-b5b6-31974949bb84)

(from ess-autoloads.el)

2024-08-31 02:44 UTC, hlissner commented on modules/lang/ess/config.el
> +        company-R-library company-dabbrev-code :separate)))
The `modulep!` check isn't necessary. `set-company-backend!` is an [autodef](https://github.com/doomemacs/doomemacs/blob/master/modules/completion/company/autoload.el#L11), so the call will no-op if the module isn't enabled.

2024-08-31 02:53 UTC, KaiAragaki commented
@hlissner ESS with eglot is ok, but it does have some rather irritating bugs (that I THINK are corfu related) - see my previous comment:

https://github.com/doomemacs/doomemacs/pull/6455#issuecomment-2038434422

The console locking up and forcing a restart is pretty irritating, unfortunately. But I still daily drive it.

2024-08-31 03:31 UTC, hlissner commented
>     * Near invisible printing to terminal ([Printing a tibble removes all text faces emacs-ess/ESS#1193](https://github.com/emacs-ess/ESS/issues/1193)). Workaround listed in comments.

I suppose we could use the `xterm-color` suggestion. Here's a doomified version of the workaround from the linked issue:

```elisp
(use-package! xterm-color
  :defer t
  :init
  (add-hook! 'inferior-ess-mode-hook
    (setq-local ansi-color-for-comint-mode nil)
    (add-hook 'comint-preoutput-filter-functions #'xterm-color-filter nil t))
  :config
  (setq xterm-color-use-bold t))
```

>     * corfu sends empty lines to iESS seemingly at random, and occasionally the session gets locked completely ([iESS entering extra lines and freezing emacs-ess/ESS#1226](https://github.com/emacs-ess/ESS/issues/1226)). I haven't found a way to resume the session - I have to kill the iESS process and open it up a new one. Verrrrry irritating. Workaround is to set `corfu auto` to `nil` which is kind of a non-solution, tbh.

That is frustrating. And the ESS codebase is quite a lot to skim. Could you identify which function(s) in ESS's `completion-at-point-functions` are relevant to this issue? Or rather, just tell it's value in the buffer(s) you experience it in. It'd help me narrow down where to start looking.

2024-08-31 11:07 UTC, edvinsyk commented
> > *
> 
> That is frustrating. And the ESS codebase is quite a lot to skim. Could you identify which function(s) in ESS's `completion-at-point-functions` are relevant to this issue? Or rather, tell me what the variable's value is in the buffer(s) you experience it in (e.g. with `C-h v completion-at-point-functions`). It'd help me narrow down where to start looking.

Thank you for looking into this @hlissner! 

This is the value of completion-at-point-functions in a failing buffer for me: 

```
(ess-filename-completion
 ess-r-object-completion
 comint-c-a-p-replace-by-expanded-history
 t
 cape-dabbrev
 yasnippet-capf)
```

As a stopgap I was able to solve the crashing by using an approach from the Corfu examples:

```
(add-hook! 'ess-r-mode-hook
  (setq-local completion-at-point-functions
              (mapcar #'cape-company-to-capf
                      (list #'company-R-args #'company-R-objects #'company-R-library)))

  )

```

This provides completion and I have encountered much less freezing over the 3 days or so that I've used it. Might be helpful in debugging. 

Let me know what I can do to further dig into this.

2024-08-31 21:45 UTC, hlissner commented
@edvinsyk Here's a small experiment you can try (with `completion-at-point-function`'s original value) to solve the crashing:

```elisp
;;; add to $DOOMDIR/config.el
(defadvice! fixed-ess-r-get-rcompletions (fn &rest args)
  :around #'ess-r-get-rcompletions
  (letf! (defun ess-get-words-from-vector (command &optional no-prompt-check _wait proc timeout)
           (funcall ess-get-words-from-vector command no-prompt-check t proc timeout))
    (apply fn args)))
```

It will likely cause *more* freezing, though, but one problem at a time.

2024-09-01 12:32 UTC, edvinsyk commented
> @edvinsyk Here's a small experiment you can try (with `completion-at-point-function`'s original value) to solve the crashing:
> 
> ```emacs-lisp
> ;;; add to $DOOMDIR/config.el
> (defadvice! fixed-ess-r-get-rcompletions (fn &rest args)
>   :around #'ess-r-get-rcompletions
>   (letf! (defun ess-get-words-from-vector (command &optional no-prompt-check _wait proc timeout)
>            (funcall ess-get-words-from-vector command no-prompt-check t proc timeout))
>     (apply fn args)))
> ```
> 
> It will likely cause _more_ freezing, though, but one problem at a time.

Sorry, I don’t know why I wrote crashing above, its only freezing I have had any problems with

2024-09-02 02:52 UTC, maikol-solis commented
Hi @hlissnerand, @edvinsyk. I apologize because I haven't had so much time to work on this PR (you know, life). 

Please feel free to change or propose any change you consider appropriate, and I'll check it out as soon as possible.

2024-09-12 12:48 UTC, KaiAragaki commented
Linking #5332

2024-09-21 18:16 UTC, KaiAragaki commented
> > > 
> > 
> > 
> > That is frustrating. And the ESS codebase is quite a lot to skim. Could you identify which function(s) in ESS's `completion-at-point-functions` are relevant to this issue? Or rather, tell me what the variable's value is in the buffer(s) you experience it in (e.g. with `C-h v completion-at-point-functions`). It'd help me narrow down where to start looking.
> 
> Thank you for looking into this @hlissner!
> 
> This is the value of completion-at-point-functions in a failing buffer for me:
> 
> ```
> (ess-filename-completion
>  ess-r-object-completion
>  comint-c-a-p-replace-by-expanded-history
>  t
>  cape-dabbrev
>  yasnippet-capf)
> ```
> 
> As a stopgap I was able to solve the crashing by using an approach from the Corfu examples:
> 
> ```
> (add-hook! 'ess-r-mode-hook
>   (setq-local completion-at-point-functions
>               (mapcar #'cape-company-to-capf
>                       (list #'company-R-args #'company-R-objects #'company-R-library)))
> 
>   )
> ```
> 
> This provides completion and I have encountered much less freezing over the 3 days or so that I've used it. Might be helpful in debugging.
> 
> Let me know what I can do to further dig into this.


I didn't have this problem for a while, but just had it today. Here's the value:

```
(cape-file
 eglot-completion-at-point
 ess-roxy-complete-tag
 ess-filename-completion
 ess-r-package-completion
 ess-r-object-completion
 t
 cape-dabbrev
 yasnippet-capf)
```

2025-01-07 06:30 UTC, KaiAragaki commented
Something to keep on the lookout - posit is creating a LSP (air: https://github.com/posit-dev/air) that uses Rust (🚀 ) which may become the preferred language server in the future.

2025-04-17 03:20 UTC, closed without merging

2025-04-17 03:21 UTC, hlissner commented
This PR has been open for quite a while, so I thought it was time to resolve it. As of these commits, I've merged most of the changes thereins and then some, but I've omitted the additions of ess-r-insert-obj and ess-smart-equals because I don't see any entry points, keybinds, or autoloading mechanisms for them in the module. Am I missing something?

There's still the corfu issue to deal with, and you clearly have more plans for these changes, but this is happening now because I'm nearing the point where I'll be moving modules out into a separate repo and wanted to close/resolve all module PRs. If there's anything else you want to squeeze into the ESS module, feel free to follow up here or in additional PRs though. 

Thanks for your help, in any case!

2025-04-17 19:29 UTC, maikol-solis commented
> This PR has been open for quite a while, so I thought it was time to resolve it. As of [these commits](https://github.com/doomemacs/doomemacs/compare/b4276f41f434...baf680f9c8dc)

Thanks, @hlissner. 

> I've merged most of the changes therein and then some, but I've omitted the additions of ess-r-insert-obj and ess-smart-equals because I don't see any entry points, keybinds, or autoloading mechanisms for them in the module. Am I missing something?

I just added these packages because the alternatives are obsoletes, but I didn't know how to make it work properly. Maybe in the new repo, the community could help to make this work as intended. 

> There's still the corfu issue to deal with, and you clearly have more plans for the module, but this is happening now because I'm nearing the point where I'll be moving modules out into a separate repo and wanted to close/resolve all module PRs. If there's anything else you want to squeeze into the ESS module, feel free to follow up here or in additional PRs though.

Yes, one point on my wish list was to create a nice UI to have the source code,  plots, and variables (similar to RStudio). However, the windows' mechanism in Emacs is still a mystery to me, and some packages aren't getting updates recently. 

The biggest example is `quarto-mode`, which is [right now unmaintained](https://github.com/quarto-dev/quarto-emacs/issues/26#issuecomment-2668762979.). I am trying Neovim to develop my [R](https://github.com/R-nvim/R.nvim) and [quarto](https://github.com/quarto-dev/quarto-nvim) stuff, and for the moment everything is nice. 

> Thanks for your help, in any case!

You're welcome. Thanks to you for the hard work with Doom.