Improve chinese module
doomemacs/doomemacs pull request #6482
Opened 2022-06-21 03:33 UTC by merrickluo

I've made some improvements to the Chinese module and has been using it for years, here is what I add

- added a `+childframe` feature flag to make `pyim` show candidates in a childframe (using posframe).
- added a `+rime` feature flag to make pyim use [librime](https://github.com/rime/librime) as input method engine (new package [liberime](https://github.com/merrickluo/liberime)).
- use `pyim-cregexp-build` to make chinese characters can be searched with pinyin, similar to #6356 but without adding new package.
- disable `evil-snipe` when input method is activated, it intercepts key event that can mess up the input method.

-----
- [x] I searched the issue tracker and this hasn't been PRed before.
- [x] My changes are not on [the do-not-PR list](https://doomemacs.org/d/do-not-pr) for this project.
- [x] My commits conform to [the git conventions](https://doomemacs.org/d/git-conventions).
- [x] Any relevant issues or PRs have been linked to.

2022-07-22 20:50 UTC, hlissner requested changes

2022-07-22 20:50 UTC, hlissner commented on modules/input/chinese/config.el
> +  (setq pyim-default-scheme 'rime))
Please separate top-level `use-package` blocks with two blank lines.

2022-07-22 20:50 UTC, hlissner commented on modules/input/chinese/config.el
> +  :when (featurep! +childframe))
Lazy-load posframe. If pyim is expected to use it, use `:after pyim`.

2022-07-22 20:50 UTC, hlissner commented on modules/input/chinese/packages.el
> +  (package! posframe))
Packages shouldn't be unpinned. Use `(package! posframe :pin "0d23bc5f7cfac00277d83ae7ba52c48685bcbc68")`

2022-07-22 20:50 UTC, hlissner commented on modules/input/chinese/config.el
> +    current-input-method)
Move this inside the `(after! evil-escape ...)` block, as it isn't used anywhere else.

2022-07-22 20:50 UTC, hlissner commented on modules/input/chinese/config.el
> +             (pyim-cregexp-build result))))
1. Use a `:filter-return` advice here instead.
2. Rename advice to `+pinyin-orderless-regexp-a` to conform to [naming conventions](https://docs.doomemacs.org/latest/#/developers/conventions/emacs-lisp/naming-conventions/doom-conventions).
3. Sharp quote function symbols (`#'orderless-regexp`).

```diff
  (cond ((featurep! :completion vertico)
-         (defadvice! +pinyin-orderless-regexp (orig-fn component)
-           :around 'orderless-regexp
-           (let ((result (funcall orig-fn component)))
-             (pyim-cregexp-build result))))
+         (defadvice! +pinyin-orderless-regexp-a (result)
+           :filter-return #'orderless-regexp
+           (pyim-cregexp-build result)))
         ((featurep! :completion ivy)
```

2022-07-22 20:58 UTC, hlissner commented
Can this PR salvage anything from #6482? I'd like to merge them into one, if possible. 

cc @merrickluo

2022-07-25 12:31 UTC, merrickluo commented on modules/input/chinese/packages.el
> +  (package! posframe))
pinded to latest commit. I see that multiple module has `(package! posframe :pin "")`, what would happen if they pin different versions?

2022-07-25 12:37 UTC, merrickluo commented
Thanks, @hlissner, I updated the PR addressing your comments, in your comments you mentioned #6382 which is the link to this PR, do you mean #6356 ?  
I see they use `pinyinlib` to achieve the same functionality as `pyim-cregexp-build`, so it's not needed, I'll try out the `evil-pinyin` package.

2022-08-02 18:35 UTC, hlissner commented on modules/input/chinese/packages.el
> +  (package! posframe))
Then the module that loads last will win. It's not ideal, but it's all we got at the moment.

2022-08-16 14:18 UTC, merrickluo commented on modules/input/chinese/packages.el
> +  (package! posframe))
I see, thanks for clarifying.

2022-08-16 15:39 UTC, merrickluo commented
I tried `evil-pinyin` and it's working great, so I copied the code from #6356 and made it only on with `evil +everywhere`.
Also, I see that the doc rewrite is now done, so I added some documentation about the new flags/packages.
cc @ErnestDong

2022-08-17 01:26 UTC, ErnestDong commented
thanks for your hard working

2023-02-23 07:40 UTC, closed without merging

2023-02-23 07:41 UTC, hlissner commented
Sorry for the late response. I've merged this in separate parts to make few minor refactors, conformed the commit messages to our git conventions, and resolve some merge conflicts. Let me know if it gives you any trouble. Thanks for your help, in any case!

2023-02-23 10:20 UTC, sdvcrx commented
@hlissner  Hi! `doom sync` error if enable `chinese` module after pulling latest Doom Emacs config:

init.el:

```elisp
(doom! :input
       ;;bidi              ; (tfel ot) thgir etirw uoy gnipleh
       chinese
       ;;japanese
       ;;layout            ; auie,ctsrnm is the superior home row
;; ..........
```

First run `doom sync`: 

```
> Synchronizing "default" profile...
  > Regenerating envvars file
    ✓ Generated ~/.emacs.d/.local/env
  > Installing packages...
    > Updating recipe repos...
    > Cloning evil-pinyin... emacsmirror-mirror...
    - Checked out evil-pinyin: 3e9e501ded86f88e01a4edec5d526ab0fab879d7
    > Building evil-pinyin...
    ! Script was abruptly aborted, leaving Doom in an incomplete state!
    - Run 'doom sync' to repair it.
    ✓ Finished in 9.71810s
```

And run `doom sync` again:

```
> Synchronizing "default" profile...
  > Regenerating envvars file
    ✓ Generated ~/.emacs.d/.local/env
  x There was an unexpected runtime error
    Message: Symbol's function definition is void
    Details: (define-namespace)
    Backtrace:
      (define-namespace evil-pinyin- (defvar with-search-rule 'custom "Enabl...
      (load-with-code-conversion "/Users/sdvcrx/.emacs.d/.local/straight/bui...
      (load "/Users/sdvcrx/.emacs.d/.local/straight/build-29.0.60/evil-pinyi...
      (progn (load autoloads-file nil 'nomessage))
      (if (file-exists-p autoloads-file) (progn (load autoloads-file nil 'no...
      (let ((autoloads-file (straight--autoloads-file package))) (if (file-e...
      (straight--load-package-autoloads "evil-pinyin")
      (let ((name (symbol-name package))) (add-to-list 'load-path (directory...
      (let ((package (car tail))) (straight-register-package package) (let (...
      (while tail (let ((package (car tail))) (straight-register-package pac...
      (let ((tail (cl-delete-duplicates packages :test #'equal))) (while tai...
      (let (packages) (let ((tail doom-packages)) (while tail (let ((package...
    ! Wrote extended backtrace to ~/.emacs.d/.local/logs/cli.doom.230223180637.48268.error
  ! Script was abruptly aborted, leaving Doom in an incomplete state!
  - Run 'doom sync' to repair it.
```

My emacs version is 29 and with `native-comp`.

System Information: https://pastebin.com/smwcG0vc

2023-02-23 10:53 UTC, merrickluo commented
Thanks @hlissner ! I'm having the same issue as @sdvcrx, seems like `evil-pinyin` can't load `names` when compile. I didn't have this issue previously.

2023-02-23 23:44 UTC, hlissner commented
After looking into this, the issue runs deep. Possibly to do with Emacs 29's new loaddefs-gen library (which replaces autoload.el); a new library for generating autoloads files. In any case, since they aren't needed, I've disabled generation of evil-pinyin's autoloads file, which seems to work around this. Give it a try and let me know if that works.

2023-02-24 01:47 UTC, merrickluo commented
yeah, it syncs without a problem now,  `evil-pinyin`'s function works great as well. thanks @hlissner :bow:

2023-02-24 03:37 UTC, sdvcrx commented
Working perfectly, thanks @hlissner @merrickluo !

2023-03-09 17:14 UTC, yangsheng6810 commented
The following addition causes problem for users who enable both ivy and Chinese module. The command `pyim-cregexp-ivy` is defined in feature `pyim-cregexp-utils.el`, which [needs to be manually required](https://github.com/tumashu/pyim/blob/f70c4227752dfa53cd3922584624da2484346d53/README.org#%E8%AE%A9-ivy-%E6%94%AF%E6%8C%81%E6%8B%BC%E9%9F%B3%E6%90%9C%E7%B4%A2%E5%80%99%E9%80%89%E9%A1%B9%E5%8A%9F%E8%83%BD). If not required, ivy will try to use `pyim-cregexp-ivy` for all selection commands, which ends in error and makes Emacs almost unusable (try think of doing something without invoking any command that requires selection).

```emacs-lisp
(setq ivy-re-builders-alist
               '((t . pyim-cregexp-ivy)))
```
I currently workaround the issue with the following in my config file:
```emacs-lisp
(use-package pyim-cregexp-utils
  :defer t
  :commands (pyim-cregexp-ivy))
```
Unfortunately I am not familiar with how autoloading works in Doom Emacs, and it would be great if someone could make a fix in Doom itself.