docs(tree-sitter): improve README formatting
doomemacs/doomemacs pull request #6490
Opened 2022-06-21 19:41 UTC by fosskers

This PR fixes up the formatting of the new Tree Sitter README. There were some spacing and punctuation issues.

- [x] I searched the issue tracker and this hasn't been PRed before.
- [ ] My changes are not on [the do-not-PR list](https://doomemacs.org/d/do-not-pr) for this project.
- [ ] My commits conform to [the git conventions](https://doomemacs.org/d/git-conventions).
- [ ] My changes are visual; I've included before and after screenshots.
- [ ] I am blindly checking these off.
- [ ] Any relevant issues or PRs have been linked to.

2022-07-22 20:29 UTC, hlissner approved these changes

2022-07-23 14:28 UTC, hlissner requested changes
It seems that merging #6569 first has created a conflict. Did I misunderstand https://github.com/doomemacs/doomemacs/pull/6569#issuecomment-1188066941, or did you mean that #6490 should'be been merged first?

In any case, would you mind resolving the conflict?

2022-07-23 22:13 UTC, jeetelongname commented
I did mean this PR should be merged first (at least then the person dealing with the conflict is me) I can work on a patch that should resolve this (mainly to avoid the PR to PR dance but whatever works)

2022-07-24 11:08 UTC, hlissner approved these changes

2022-07-24 11:09 UTC, merged

2022-07-24 11:09 UTC, hlissner commented
Ah, my bad! I'm glad it was an easy fix, at least. Thanks again for your help!