fix(evil): evil-collection-replace
doomemacs/doomemacs pull request #6524
Opened 2022-06-30 09:01 UTC by DeesonGao

evil-collection-occur.el have been moved to evil-collection-replace.el by
upstream.

Fixes #6495 

-----
- [ ] I searched the issue tracker and this hasn't been PRed before.
- [ ] My changes are not on [the do-not-PR list](https://doomemacs.org/d/do-not-pr) for this project.
- [ ] My commits conform to [the git conventions](https://doomemacs.org/d/git-conventions).
- [ ] My changes are visual; I've included before and after screenshots.
- [ ] I am blindly checking these off.
- [ ] Any relevant issues or PRs have been linked to.

2022-07-04 23:41 UTC, hlissner approved these changes

2022-07-04 23:47 UTC, hlissner requested changes
Sorry for the conflict. Could you rebase this onto the `HEAD` of `master` to resolve it?

2022-07-05 03:12 UTC, DeesonGao commented
I just follow the instruction on the web page, is it right?

2022-07-05 12:16 UTC, closed without merging

2022-07-05 12:19 UTC, hlissner commented
Close! I was asking that it be rebased, but that's alright. While looking into this further I realized that `+evil-collection-disabled-list` hadn't been updated, so I did so (and merged your changed) in 9ec60d9 with credit. Thanks for bringing it to my attention!