bump: :core projectile
doomemacs/doomemacs pull request #6535
Opened 2022-07-05 13:16 UTC by acristoffers

The referenced commit incorporates https://github.com/bbatsov/projectile/pull/1784 to fix #6504.

Fixes #0001
References #0001
Replaces #0000

-----
- [X] I searched the issue tracker and this hasn't been PRed before.
- [X] My changes are not on [the do-not-PR list](https://doomemacs.org/d/do-not-pr) for this project.
- [X] My commits conform to [the git conventions](https://doomemacs.org/d/git-conventions).
- [X] Any relevant issues or PRs have been linked to.

2022-07-05 15:24 UTC, hlissner requested changes
Bumping projectile won't actually fix the issue because Doom has [its own default for projectile-generic-command](https://github.com/doomemacs/doomemacs/blob/master/core/core-projects.el#L166-L184).

Would you mind rebasing this by replacing your bump commit with a bugfix that adds `--strip-cwd-prefix` to [this line?](https://github.com/doomemacs/doomemacs/blob/master/core/core-projects.el#L177)

Also, please change the commit message to the following (to conform to [our commit conventions](https://discourse.doomemacs.org/t/git-conventions/2407)):

```
fix: strip './' from projectile file list produced by fd

Fix: #6504
```

Side note: I'd rather it be a bugfix than a bump because I have a larger bump commit in the pipeline that would render this bump redundant.

2022-07-05 15:42 UTC, acristoffers commented
When squashing with GitHub Desktop App I have two fields for a commit message, so I split your message into two, hoping that GitHub actually merges them into one -m option. Is that correct or do I have to amend the commit message?

2022-07-22 20:23 UTC, hlissner approved these changes

2022-07-23 13:57 UTC, merged

2022-07-23 13:57 UTC, hlissner commented
> Is that correct or do I have to amend the commit message?

It seems to be correct. Thanks for your help!