fix(pass): enable evil-collection bindings
doomemacs/doomemacs pull request #6536
Opened 2022-07-05 16:13 UTC by edgar-vincent

This enables `evil-collection` support for `tools/pass`, making sure the bindings are displayed properly in the `pass` header.
Originally, `pass` was launched in `emacs-state` because `evil-collection` didn't support `pass` when the module was written, but it does now.
It also removes stale code relative to the `PASSWORD_STORE_DIR` environment variable, since the password store path is not hardcoded in `pass.el` anymore.

-----
- [x] I searched the issue tracker and this hasn't been PRed before.
- [x] My changes are not on [the do-not-PR list](https://doomemacs.org/d/do-not-pr) for this project.
- [x] My commits conform to [the git conventions](https://doomemacs.org/d/git-conventions).
- [ ] I am blindly checking these off.
- [x] Any relevant issues or PRs have been linked to.

2022-07-05 18:20 UTC, hlissner requested changes

2022-07-05 18:20 UTC, hlissner commented on modules/tools/pass/config.el
> +    :n "C-k" #'pass-prev-directory))
1. Please correct the indentation. `:n` should be aligned with `:map`
2. Please align the sharp quotes as well.

2022-07-05 18:20 UTC, hlissner commented on modules/tools/pass/config.el
> +  (add-to-list  'evil-collection-pass-command-to-label '(pass-update-buffer . "gr"))
1. Remove redundant spacing:

```diff
-  (add-to-list  'evil-collection-pass-command-to-label '(pass-update-buffer . "gr"))
+  (add-to-list 'evil-collection-pass-command-to-label '(pass-update-buffer . "gr"))
```

2022-07-05 18:20 UTC, hlissner commented on modules/tools/pass/config.el
> +  (add-to-list  'evil-collection-pass-command-to-label '(pass-update-buffer . "gr"))
2. This will throw an error if `evil-collection` (or evil) is disabled/unavailable.

   Please move it out of the `(after! pass ...)` block and put it in a `(after! evil-collection-pass ...)` block at top level.

2022-07-22 20:18 UTC, hlissner approved these changes

2022-07-23 13:59 UTC, merged

2022-07-23 13:59 UTC, hlissner commented
Sorry for the wait. This LGTM. Thanks for your help!

2022-07-23 14:02 UTC, edgar-vincent commented
No problem at all. Thanks a lot for all your great work!

23 Jul 2022 16:00:07 Henrik Lissner ***@***.***>:

> Sorry for the wait. This LGTM. Thanks for your help!
> 
> —
> Reply to this email directly, view it on GitHub[https://github.com/doomemacs/doomemacs/pull/6536#issuecomment-1193130150], or unsubscribe[https://github.com/notifications/unsubscribe-auth/APDLASTTHRGJLJZSYDRQOTDVVP3GLANCNFSM52WYBQFA].
> You are receiving this because you authored the thread.[Tracking image][https://github.com/notifications/beacon/APDLASUOP636JHKY2UB3RQTVVP3GLA5CNFSM52WYBQFKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOI4O3RJQ.gif]
>