feat(default): bind 'SPC b I' to ibuffer/workspace
doomemacs/doomemacs pull request #6543
Opened 2022-07-07 11:13 UTC by teeann

As `SPC b i` is already bound to `ibuffer`, this new binding is really convenient and consistent with Doom's current default binding.

2022-07-22 23:07 UTC, hlissner requested changes

2022-07-22 23:07 UTC, hlissner commented on modules/config/default/+evil-bindings.el
> +        :desc "ibuffer workspace"       "i" #'+ibuffer/open-for-current-workspace)
This binds `+ibuffer/open-for-current-workspace` to `i` (lowercase). I think you meant to bind it to `I` (uppercase). If not, then the later `i` keybinding (to `ibuffer`) will always override this. If so, please change it.

2022-07-23 14:25 UTC, teeann commented on modules/config/default/+evil-bindings.el
> +        :desc "ibuffer workspace"       "i" #'+ibuffer/open-for-current-workspace)
Yes, I've fixed the typo binding as you mentioned

2022-07-23 22:07 UTC, hlissner approved these changes

2022-07-23 22:07 UTC, merged

2022-07-23 22:07 UTC, hlissner commented
Thanks for your help!