bump: :lang scala
doomemacs/doomemacs pull request #6545
Opened 2022-07-08 16:46 UTC by rvarago

This PR bumps the [lsp-metals](https://github.com/emacs-lsp/lsp-metals) to the latest commit up to this date. Namely to support server updates to the latest versions - when Emacs manage such. 

References https://github.com/emacs-lsp/lsp-metals/pull/73

-----
- [x] I searched the issue tracker and this hasn't been PRed before.
- [x] My changes are not on [the do-not-PR list](https://doomemacs.org/d/do-not-pr) for this project.
- [x] My commits conform to [the git conventions](https://doomemacs.org/d/git-conventions).
- [ ] My changes are visual; I've included before and after screenshots.
- [ ] I am blindly checking these off.
- [x] Any relevant issues or PRs have been linked to.
- [ ] This a draft PR; I need more time to finish it.

(I believe I have covered all the points, but please let me know if I'd missed anything)

2022-07-22 20:14 UTC, hlissner requested changes
Sorry for getting to this so late. `lsp-metals` has seen two additional commits in the time since this was posted; would you mind rebumping it (and updating the commit message)?

Also, please append the following to the commit message:

```

Ref: emacs-lsp/lsp-metals#73
```

2022-07-23 08:45 UTC, rvarago commented
> Sorry for getting to this so late. `lsp-metals` has seen two additional commits in the time since this was posted; would you mind rebumping it (and updating the commit message)?
> 
> Also, please append the following to the commit message:
> 
> ```
> 
> Ref: emacs-lsp/lsp-metals#73
> ```

No problem at all.

Absolutely! It's done.

2022-07-23 11:42 UTC, hlissner approved these changes

2022-07-23 12:04 UTC, merged

2022-07-23 12:04 UTC, hlissner commented
Good work. Thanks again for your help!