bump: :completion vertico
doomemacs/doomemacs pull request #6550
Opened 2022-07-09 22:40 UTC by iyefrat

minad/consult@b15c81f7766a -> minad/consult@df3dbe1174e7
minad/marginalia@26f2bd9ee7b6 -> minad/marginalia@4fe73f5724d1
minad/vertico@e5935b5bbfc0 -> minad/vertico@229229047969
oantolin/embark@97270d725761 -> oantolin/embark@5d0459d27aa7
oantolin/orderless@75eeae21971d -> oantolin/orderless@8b9af2796fa0

---

I checked the commits in the bumped packages, there don't seem to be any doom-facing changes, or any obvious breakages in my sanity checks beyond that

2022-07-22 20:11 UTC, hlissner requested changes
Sorry for getting to this so late. A few packages have seen a few more updates; could you rebump this?

2022-07-22 21:43 UTC, iyefrat commented
Done, I've looked over the new commits, no breaking changes there

2022-07-22 22:56 UTC, hlissner approved these changes

2022-07-23 12:04 UTC, merged

2022-07-23 12:04 UTC, hlissner commented
LGTM. Thanks again!