bump: :tools biblio
doomemacs/doomemacs pull request #6628
Opened 2022-08-03 22:34 UTC by bdarcus

I'm opening this as a draft for now, just so people don't do the same.

I'm just waiting for a commit or two on the below before marking it for review.

-----------------------

Bump the biblio module, which also requires adding `citar-embark`, which now contains the embark functionality in a separate minor mode package.

2022-08-04 15:47 UTC, hlissner requested changes
Looks good to me so far. Just two minor nits:

1. Please remove the redundant `tmalsburg/helm-bibtex@aa775340ba69 -> tmalsburg/helm-bibtex@ce8c17690dda` line in the commit.
2. Please add `citar-embark` and `parsebib` to the module's README (might have to rebase the module back onto `master`, since I updated it to the new format in 304774cf393d79c75842ab05ad1796d66eea48fd).

2022-08-04 16:40 UTC, bdarcus commented
> * Please remove the redundant `tmalsburg/helm-bibtex@aa775340ba69 -> tmalsburg/helm-bibtex@ce8c17690dda` line in the commit.
> * Please add `citar-embark` and `parsebib` to the module's README (might have to rebase the module back onto `master`, since I updated it to the new format in [304774c](https://github.com/doomemacs/doomemacs/commit/304774cf393d79c75842ab05ad1796d66eea48fd)).

Done, though I have a stupid merge conflict still to figure out (I thought I'd earlier properly updated my repo, but I guess not).

Is it OK if we wait a couple/few days for me to mark this for review? The commits I'm waiting for are from parsebib and citar, which should address a performance issue with very large files.

2022-08-05 18:15 UTC, hlissner commented
> Is it OK if we wait a couple/few days for me to mark this for review?

Certainly. Take your time. I don't generally merge draft PRs.

2022-08-08 17:43 UTC, bdarcus commented
@hlissner - the performance optimizations I was waiting on will take a bit more time, and I think it's better to merge this now, since it does also fix #6464. It's also really only a problem for the rare user who has a single very large bib file, which change frequently.

https://github.com/emacs-citar/citar/issues/659

2022-08-08 21:40 UTC, hlissner approved these changes

2022-08-08 21:41 UTC, merged

2022-08-08 21:41 UTC, hlissner commented
Understood. And everything else looks good. Thanks again!