`:tools tree-sitter` syntax highlighting
doomemacs/doomemacs pull request #6629
Opened 2022-08-03 22:37 UTC by jeetelongname

as well as documentation updates to reflect this update
this is still a work in progress as there is also a lazy load bug in this change as well as update for the latest docs

-----
- [X] I searched the issue tracker and this hasn't been PRed before.
- [X] My changes are not on [the do-not-PR list](https://doomemacs.org/d/do-not-pr) for this project.
- [X] My commits conform to [the git conventions](https://doomemacs.org/d/git-conventions).
- [ ] My changes are visual; I've included before and after screenshots.
- [ ] I am blindly checking these off.
- [X] Any relevant issues or PRs have been linked to.
- [X] This a draft PR; I need more time to finish it.

2022-08-03 23:59 UTC, jeetelongname commented
Ok found the lazy loading bug, forgot that `:hook` added an implict `:defer` which I needed to add back

2022-08-04 16:00 UTC, hlissner requested changes

2022-08-04 16:00 UTC, hlissner commented on modules/tools/tree-sitter/config.el
> -
Could you restore this blank line? It's a Doom convention that top-level `use-package!` blocks should be separated by two blank lines.

2022-08-04 16:00 UTC, hlissner commented on modules/tools/tree-sitter/config.el
> +
For consistency with other modules, please insert:

```diff
 If nil, it is disabled in all modes")

+
+;;
+;;; Packages
+
 (use-package! tree-sitter
```

2022-08-04 16:00 UTC, hlissner commented on modules/tools/tree-sitter/autoload.el
> +                         -1)))
Is there any reason we can't merge `+tree-sitter--hl-enable-maybe` and `tree-sitter!`? I'd like to avoid autoloading private/internal functions, and it doesn't seem to be used anywhere else.

2022-08-04 16:00 UTC, hlissner commented on modules/tools/tree-sitter/autoload.el
> +                         -1)))
Also, this `tree-sitter-hl-mode` call should be guarded. Even if called only to disable it, we'd be autoloading it and performing some shut-down logic (which will likely be inexpensive, but it's a potential point of failure).

Something like:

```lisp
(when-let* ((mode (bound-and-true-p tree-sitter-hl-mode))
            (mode (if (pcase +tree-sitter-hl-enabled-modes
                        (`(not . ,modes) (not (memq major-mode modes)))
                        ((and `(,_ . ,_) modes) (memq major-mode modes))
                        (bool bool))
                      (unless mode +1)
                    (if mode -1))))
  (tree-sitter-hl-mode mode))
```

2022-08-04 20:50 UTC, jeetelongname commented on modules/tools/tree-sitter/autoload.el
> +                         -1)))
If this is meant to be a toggle then we also need to change the line `turn-on-tree-sitter-mode` to a toggle

2022-08-04 20:54 UTC, jeetelongname commented on modules/tools/tree-sitter/autoload.el
> +                         -1)))
```lisp
(if (bound-and-true-p tree-sitter-mode)
    (ignore-errors
      (tree-sitter-mode +1))
  (tree-sitter-mode -1))
```

something like this

2022-08-04 22:42 UTC, hlissner commented on modules/tools/tree-sitter/autoload.el
> +                         -1)))
Ah, `tree-sitter!` is not supposed to be a toggle (or an interactive command, for that matter). It's only intended to be a hook. Can you remove the `(interactive)` in it?

2022-08-04 22:52 UTC, jeetelongname commented on modules/tools/tree-sitter/autoload.el
> +                         -1)))
I think i was mirroring `lsp!` in so far as it is also an "interactive" hook function,
In any case that makes sense, Ill remove it, I am guessing we also will not need the toggle logic you have come up with

2022-08-05 11:22 UTC, hlissner commented on modules/tools/tree-sitter/autoload.el
> +                         -1)))
> I am guessing we also will not need the toggle logic you have come up with

We still do, actually. The problem is that `tree-sitter-hl.el` is lazy loaded. By calling `tree-sitter-hl-mode` (even to turn it off when it isn't enabled in the first place), we're loading it, so I'd like it guarded.

2022-08-05 14:00 UTC, jeetelongname commented on modules/tools/tree-sitter/autoload.el
> +                         -1)))
Ah I understand now, makes sense, in any case that has been pushed, thanks for the help!

2022-08-05 18:55 UTC, hlissner requested changes

2022-08-05 18:55 UTC, hlissner commented on modules/tools/tree-sitter/autoload.el
> +    (tree-sitter-hl-mode mode)))
Ack, sorry to keep doing this to you, but I've noticed a bug in this guard (if `tree-sitter-hl-mode` isn't enabled already, it won't be enabled). Can you replace it with:

```diff
(defun tree-sitter! ()
  (interactive)
  (turn-on-tree-sitter-mode)
  ;; conditionally enable `tree-sitter-hl-mode'
- (when-let* ((mode (bound-and-true-p tree-sitter-hl-mode))
-             (mode (if (pcase +tree-sitter-hl-enabled-modes
-                         (`(not . ,modes) (not (memq major-mode modes)))
-                         ((and `(,_ . ,_) modes) (memq major-mode modes))
-                         (bool bool))
-                       (unless mode +1)
-                     (if mode -1))))
-   (tree-sitter-hl-mode mode)))
+(let ((mode (bound-and-true-p tree-sitter-hl-mode)))
+  (when-let (mode (if (pcase +tree-sitter-hl-enabled-modes
+                        (`(not . ,modes) (not (memq major-mode modes)))
+                        ((and `(,_ . ,_) modes) (memq major-mode modes))
+                        (bool bool))
+                      (unless mode +1)
+                    (if mode -1)))
+    (tree-sitter-hl-mode mode))))
```

2022-08-06 14:47 UTC, jeetelongname commented on modules/tools/tree-sitter/autoload.el
> +    (tree-sitter-hl-mode mode)))
No worries, I should be checking these things more thoroughly myself as well. Ill give this a test and after that we should be good to go

2022-08-06 17:05 UTC, jeetelongname commented on modules/tools/tree-sitter/autoload.el
> +    (tree-sitter-hl-mode mode)))
With a little testing all seems to be good now, seems to work (when entering a non supported mode nothing is loaded, but it does enable for modes that are supported) 

thanks for workshopping this (and bareing with me)

2022-08-08 16:36 UTC, hlissner approved these changes

2022-08-08 16:37 UTC, merged

2022-08-08 16:37 UTC, hlissner commented
Great work (as usual)! Thanks again!