adding `flymake` to `:checkers syntax`
doomemacs/doomemacs pull request #6660
Opened 2022-08-10 22:47 UTC by jeetelongname

There is more to come, most of it finding checkers, but there should be a point
(very soon) where if you use lsp with all of your langs this is a drop in
replacement.
I need to also write an alternative too `+emacs-lisp-reduce-flycheck-errors-in-emacs-config-h` but that shall come in due course 

-----
- [ ] I searched the issue tracker and this hasn't been PRed before.
- [ ] My changes are not on [the do-not-PR list](https://doomemacs.org/d/do-not-pr) for this project.
- [ ] My commits conform to [the git conventions](https://doomemacs.org/d/git-conventions).
- [ ] My changes are visual; I've included before and after screenshots.
- [ ] I am blindly checking these off.
- [ ] Any relevant issues or PRs have been linked to.
- [ ] This a draft PR; I need more time to finish it.

2022-08-11 06:44 UTC, gagbo reviewed
Small nitpicks and general warning: I know that when I touched lsp-mode and eglot checkers I always worked under the assumption that `:checkers syntax` is equivalent to using flycheck (necessary and sufficient). So you might need to make a pass there to make sure that flycheck stuff is correctly inactive when `(featurep! :checkers syntax +flymake)`

2022-08-11 06:44 UTC, gagbo commented on modules/checkers/syntax/config.el
>  ;;; TODO Flymake
Might as well remove the TODO item

2022-08-11 06:44 UTC, gagbo commented on modules/checkers/syntax/config.el
> +(use-package flymake-popon
Do we want to hide that behind the childframe feature ?

2022-08-11 06:44 UTC, gagbo commented on modules/checkers/syntax/packages.el
>  ;; TODO flymake?
Might as well remove the TODO item

2022-08-11 10:41 UTC, jeetelongname commented
I wanted to get the stub up but I am aware of that, I would need to do a pass over a lot of the modules to make them more generic. But that is on the agenda.

2022-08-11 10:42 UTC, jeetelongname commented on modules/checkers/syntax/config.el
> +(use-package flymake-popon
Thats the thing. Its not using childframes. I guess it depends on the spirit of what `+childframe` means.

2022-08-16 20:30 UTC, jeetelongname commented on modules/checkers/syntax/config.el
> +(use-package flymake-popon
Nevermind I just feature gated it properly, postframes will be used when `+childframe` is enabled

2022-08-16 20:49 UTC, gagbo commented on modules/checkers/syntax/packages.el
> +  (package! flymake-popon :recipe (:repo "https://codeberg.org/akib/emacs-flymake-popon")))
With straight.el having added support for NonGNU ELPA you shouldn't need to specify the recipes anymore. Is current straight.el pin too old ?

2022-08-16 22:25 UTC, jeetelongname commented on modules/checkers/syntax/packages.el
> +  (package! flymake-popon :recipe (:repo "https://codeberg.org/akib/emacs-flymake-popon")))
I think so, I am getting an error still, I can add a NOTE to it though that I can remove the recipe when its bumped

2023-03-02 00:48 UTC, peterhoeg commented
This might be slightly off-topic but how does flymake compare to flycheck?

2023-03-02 01:35 UTC, jeetelongname commented
- flymake is built in first of all. Thats its biggest advantage, 
- It also does not need as much configuration as well with its defaults 
- It composes well with emacs systems (with diagnostic functions just being added to a hook as one example) 
- From what i am seeing, its the way the community is going.

atm both are usable, I have been using this branch for a while now (other than a small break for a large bump of the tree sitter module) there are some loose ends, I need to replace a lot of the flycheckers I disabled but other than that, especially if you use lsp for most things it just works:tm:

2023-04-12 04:47 UTC, peterhoeg commented
`eglot` is still pulling in `flycheck-eglot`

I'm not sure what the official position is on narrowly used helpers, but I end up with a fair bit of `(and (modulep! :checkers syntax) (not (modulep! :checkers syntax +flymake)))`. It would be very nice to have a helper defined to avoid that.

2023-07-24 19:27 UTC, hlissner requested changes
Is there something holding up this PR?

> It would be very nice to have a helper defined to avoid that.

Will do. In v3, `modulep!` will understand negated flags as an implicit `(not ...)`, e.g. `(modulep! :checkers syntax -flymake)` => returns `t` only if the module is enabled _and_ lacks `+flymake`.

2023-07-24 19:27 UTC, hlissner commented on modules/lang/cc/config.el
> +                  :yield "#require")
Please revert

2023-07-24 19:27 UTC, hlissner commented on modules/lang/clojure/config.el
> +         :i "U"  #'cider-repl-history-undo-other-window)))
Please revert

2023-07-24 19:27 UTC, hlissner commented on modules/lang/clojure/packages.el
> +(package! cider :pin "92c1b6de20805a9caa556cc671ac39080e4e89cc")
Please revert (or are specific versions needed for flymake support?)

2023-07-24 19:27 UTC, hlissner commented on modules/tools/lsp/+eglot.el
> +
This seems outdated with https://github.com/doomemacs/doomemacs/blob/master/modules/tools/lsp/+eglot.el#L64-L66

2023-07-24 22:39 UTC, jeetelongname commented
I wanted to add flymake support for a few more modules but everything works if you use lsp (like I do). Ill see if I can revert these changes within the next couple of days

2023-07-24 23:18 UTC, jeetelongname commented on modules/tools/lsp/+eglot.el
> +
Looks like it. Ill remove that and properly feat gate flycheck eglot in that case

2023-07-24 23:25 UTC, jeetelongname commented
that should be all done. if there is anything more let me know.

2023-07-24 23:30 UTC, jeetelongname commented
Also I have not completed this. 
> I need to also write an alternative too +emacs-lisp-reduce-flycheck-errors-in-emacs-config-h but that shall come in due course

I may be able to have a go at it over the next couple of days but feel free to merge this PR and or tackle this yourself.

2023-07-25 01:11 UTC, hlissner approved these changes

2023-07-25 20:11 UTC, merged

2023-07-25 20:12 UTC, hlissner commented
LGTM! Thanks again for your help!

> I may be able to have a go at it over the next couple of days but feel free to merge this PR and or tackle this yourself.

Will do!

2025-09-29 08:31 UTC, artpelling commented
I can't find this feature in the docs. Is it fully functional with `eglot`? I have some issues getting `flymake` plugins to work.

2025-09-29 18:45 UTC, hlissner commented
@artpelling https://github.com/doomemacs/doomemacs/blob/master/modules/checkers/syntax/README.org#module-flags

Works fine with Eglot. Please open a new issue (or [discussion](https://doomemacs.org/discuss) if you're uncertain about the cause).