fix(dart): enable rainbow-delimiters in dart-mode
doomemacs/doomemacs pull request #6713
Opened 2022-08-22 08:00 UTC by elken

2022-08-22 08:58 UTC, hlissner requested changes

2022-08-22 08:58 UTC, hlissner commented on modules/lang/dart/config.el
> +  :hook (dart-mode . rainbow-delimiters-mode)
The order of keys actually breaks `:config`. Plus, `:hook` makes `:defer t` redundant. Please change this to:

```diff
-  :defer t
+  :hook (dart-mode . rainbow-delimiters-mode)
   :config
-  :hook (dart-mode . rainbow-delimiters-mode)

2022-08-22 09:01 UTC, elken commented on modules/lang/dart/config.el
> +  :hook (dart-mode . rainbow-delimiters-mode)
You're right, I can't read...

I started adding it then panic pushed it because it was 9am. Noted to myself to _not_ do that again

2022-09-06 22:16 UTC, merged

2022-09-06 22:16 UTC, hlissner commented
LGTM. Thanks again!