feat(biblio): add citar-org-roam
doomemacs/doomemacs pull request #6728
Opened 2022-08-26 16:49 UTC by bdarcus

Per https://discourse.doomemacs.org/t/citar-org-roam-for-biblio-module, this adds tighter integration between citar and org-roam.

I have elected not to add a specific flag, and install and configure it for org-roam users. I can't see any downside to that.

----------------

- [X] I searched the issue tracker and this hasn't been PRed before.
- [X] My changes are not on [the do-not-PR list](https://doomemacs.org/d/do-not-pr) for this project.
- [X] My commits conform to [the git conventions](https://doomemacs.org/d/git-conventions).

2022-09-03 15:41 UTC, bdarcus commented
Ran into an issue; converting this to draft.

2022-09-06 23:38 UTC, hlissner requested changes

2022-09-06 23:38 UTC, hlissner commented on modules/tools/biblio/packages.el
> +      (package! citar-org-roam :pin "4325e648c228269e519c322d696846a6c1f42f99")))
Please correct the indentation (should align with the `(package!` above it).

2022-09-06 23:38 UTC, hlissner commented on modules/tools/biblio/packages.el
> +      (package! citar-org-roam :pin "4325e648c228269e519c322d696846a6c1f42f99")))
And replace `featurep!` with `modulep!`.

2022-09-06 23:38 UTC, hlissner commented on modules/tools/biblio/config.el
> +             (featurep! :lang org +roam2))
Replace `featurep!` with `modulep!` (see https://github.com/doomemacs/doomemacs/commit/ad6a3d0f33eed9e08f88f1913f2e10fc7e9bdffb)

2022-09-06 23:38 UTC, hlissner commented on modules/tools/biblio/config.el
> +  :config (citar-org-roam-mode))
Should this be added to `org-roam-mode-hook` instead?

2022-09-13 11:36 UTC, bdarcus commented on modules/tools/biblio/config.el
> +  :config (citar-org-roam-mode))
I made this change, but I don't think it will work in retrospect.

We need to turn on this mode, and hence also load org-roam, when citar is loaded, or the citar display will be wrong if the user hasn't already opened an org-roam buffer.

2022-10-28 00:53 UTC, hlissner commented on modules/tools/biblio/config.el
> +  :config (citar-org-roam-mode))
> I made this change

What did your attempt look like? I was thinking of:

```elisp
(use-package! citar-org-roam
  :when (modulep! :completion vertico)
  :hook (org-roam-mode . citar-org-roam-mode))
```

But if that doesn't work, I'll go with what you've already done in this PR.

2022-10-28 00:55 UTC, hlissner requested changes
Sorry for the late response. Would you mind:

1. Rebumping the bump commit,
2. Resolving the README.org conflict,
3. Reword the summary line of [fix: bind "n b" to citar-open-notes](https://github.com/doomemacs/doomemacs/pull/6728/commits/8e7353052c56dc1b7abcfbfc90882ac16417468a) to `tweak(default): bind "n b" to citar-open-notes`.
 
Then this should be good to merge.

2022-10-28 14:43 UTC, bdarcus commented
> Sorry for the late response. Would you mind:
> 
> 1. Rebumping the bump commit,
> 2. Resolving the README.org conflict,
> 3. Reword the summary line of [fix: bind "n b" to citar-open-notes](https://github.com/doomemacs/doomemacs/pull/6728/commits/8e7353052c56dc1b7abcfbfc90882ac16417468a) to `tweak(default): bind "n b" to citar-open-notes`.
> 
> Then this should be good to merge.

I always seem to run into some git issue or another on these PRs.

So I used the github conflict resolve UI for the README, which caused the following problem: it used a merge commit, and now I don't now how to edit the history to squash it with the citar-org-roam commit.

Otherwise, I've fixed the other issues.

2022-10-28 14:44 UTC, bdarcus commented on modules/tools/biblio/config.el
> +  :config (citar-org-roam-mode))
Yeah, it doesn't work, so I've left it as is.

2022-10-28 16:46 UTC, closed without merging

2022-10-28 16:48 UTC, hlissner commented
It would probably have been easiest to rebase everything onto `master` before amending those commits, but I've cherry-picked the commits onto master directly to save you the trouble, so we can consider this merged. Thanks again for your help!

2022-10-28 16:54 UTC, bdarcus commented
Thank you!