feat: add back relevant removed org-contribs
doomemacs/doomemacs pull request #6751
Opened 2022-09-06 16:08 UTC by elken

A recent commit of org-contrib removed a number of packages.

Closes #6740

2022-09-08 21:43 UTC, gf3 commented
Thank you for re-adding these @elken!

2022-09-15 23:30 UTC, hlissner approved these changes

2022-09-15 23:35 UTC, hlissner requested changes
Please reword the commit to:

```
feat(org): restore org-contrib packages removed upstream

org-contrib is slowly removing packages (most of which have moved or
will move to their own repos or into Org proper).

Ref: emacsmirror/org-contrib@3dd984152258
Ref: emacsmirror/org-contrib@c555d8d48967
Ref: emacsmirror/org-contrib@0740bd3fe69c
Close: #6740
```

2022-09-30 21:02 UTC, merged

2022-09-30 21:02 UTC, hlissner commented
Thanks again!