fix: ensure flx is loaded with (ivy +fuzzy)
doomemacs/doomemacs pull request #6768
Opened 2022-09-10 16:58 UTC by theschmocker

Overriding `ivy--flx-featurep` here would always prevent flx from being loaded and enabled---even if it were `t`---because ivy `require`s it in `ivy--flx-featurep`'s initvalue. So instead, this sets the variable if and only if it should be disabled. Because flx isn't installed when +prescient is enabled, I've included that in the condition for disabling ivy--flx-featurep as well

Fix: https://github.com/doomemacs/doomemacs/issues/6034
Amend: https://github.com/doomemacs/doomemacs/commit/bae7ab0d8dbb2ace3fb54692f3525826b69ed60a

-----
- [x] I searched the issue tracker and this hasn't been PRed before.
- [x] My changes are not on [the do-not-PR list](https://doomemacs.org/d/do-not-pr) for this project.
- [ ] My commits conform to [the git conventions](https://doomemacs.org/d/git-conventions).
  I tried to scope this as fix(ivy), but I was getting a lint error that ivy was not a valid scope. I may have misunderstood the scoping rules
- [x] Any relevant issues or PRs have been linked to.

2022-09-10 17:05 UTC, hlissner requested changes
LGTM. Though, could you reword the commit to include the scope? I.e.

```
fix(ivy): ensure flx is loaded with +fuzzy

Overriding `ivy--flx-featurep` here would always prevent flx from being
loaded and enabled---even if it were `t`---because ivy `require`s it in
`ivy--flx-featurep`'s initvalue. So instead, this sets the variable if
and only if it should be disabled. Because flx isn't installed when
+prescient is enabled, I've included that in the condition for disabling
ivy--flx-featurep as well

Fix: #6034
Amend: bae7ab0d8dbb
```

2022-09-10 17:11 UTC, theschmocker commented
> LGTM. Though, could you reword the commit to include the scope? I.e.
> 
> ```
> fix(ivy): ensure flx is loaded with +fuzzy
> 
> Overriding `ivy--flx-featurep` here would always prevent flx from being
> loaded and enabled---even if it were `t`---because ivy `require`s it in
> `ivy--flx-featurep`'s initvalue. So instead, this sets the variable if
> and only if it should be disabled. Because flx isn't installed when
> +prescient is enabled, I've included that in the condition for disabling
> ivy--flx-featurep as well
> 
> Fix: #6034
> Amend: bae7ab0d8dbb
> ```

I tried that in my initial commit message and just attempted to reword, but I get the following lint error:
```
> Linting 1 commits
  > CURRENT fix(ivy): ensure flx is loaded with (ivy +fuzzy)
    x Invalid scope: ivy
! Failures: 1
```

2022-09-10 18:44 UTC, theschmocker commented
@hlissner I did some digging into that lint error and found that `ci-check-module-scope` in .doomrc was looking a directory too high for modules ie. `~/modules` instead of the correct `~/.emacs.d/modules`

```elisp
(cl-defun ci-check-module-scope (scope (&key type &allow-other-keys))
  "Only allow :CATEGORY or MODULE scopes if they actually exist."
  (seq-find (doom-rpartial
             #'doom-glob (if (string-prefix-p ":" scope)
                             (format "%s" (substring scope 1))
                           (format "*/%s" scope)))
            (list (doom-path (dir!) "../modules/") ; <--------------
                  (doom-path doom-user-dir "modules/"))))

```

Changing "../modules" to "modules/" made it resolve to the correct path and identify ivy as a valid scope. It looks like this path has been used for quite a while, so I wonder if something happened with the recent changes do `dir!` and related. 

Results of `doom info`, in case this is an issue with my local setup:
```
generated  Sep 10, 2022 13:39:52
system     MacOS 12.5.1 Darwin 21.6.0 arm64
emacs      28.1 ~/.emacs.d/ -> ~/.emacs.d/
doom       3.0.0-dev HEAD -> ivy-flx-fix 2eb77b3ad 2022-09-10 13:23:34 -0500
           ~/.doom.d/ -> ~/dotfiles/emacs/.doom.d/
shell      /bin/zsh
features   ACL GIF GLIB GMP GNUTLS JPEG JSON LCMS2 LIBXML2 MODULES NATIVE_COMP
           NOTIFY KQUEUE NS PDUMPER PNG RSVG THREADS TIFF TOOLKIT_SCROLL_BARS
           XIM ZLIB
traits     batch server-running envvar-file custom-file
modules    :completion (company +childframe) (ivy +fuzzy) :ui doom
           doom-dashboard doom-quit hl-todo (modeline +light) ophints (popup
           +defaults) treemacs (vc-gutter +pretty) vi-tilde-fringe window-select
           workspaces :editor (evil +everywhere) file-templates fold snippets
           :emacs (dired +icons) electric undo vc :term eshell vterm :checkers
           syntax :tools (docker +lsp) editorconfig ein (eval +overlay) (lookup
           +dictionary) lsp magit pdf rgb :os macos :lang clojure common-lisp
           (csharp +lsp) emacs-lisp (go +lsp) (haskell +lsp) json (javascript
           +lsp) (lua +lsp +fennel) (markdown +grip) (org +pretty +roam2) (php
           +lsp) (python +lsp +pyright) rest (rust +lsp) (scheme +guile
           +chicken) sh (web +lsp +html) yaml :config (default +bindings
           +smartparens)
packages   (evil-cleverparens)
unpin      lsp-mode lsp-ui
```

I can go ahead and push the reworded commit if you have no objection to me (lightly) hacking around the linter 🙂

2022-09-10 21:40 UTC, hlissner commented
> I can go ahead and push the reworded commit if you have no objection to me (lightly) hacking around the linter slightly_smiling_face

That's perfectly fine. The doomrc is just outdated; I'm sitting on an update, but they're blocked by some other unpushed CLI changes. I'll deal with that separately.

2022-09-15 23:26 UTC, hlissner approved these changes

2022-09-15 23:26 UTC, merged

2022-09-15 23:27 UTC, hlissner commented
Thanks for your help!

Side-note: as of https://github.com/doomemacs/doomemacs/commit/cf1c6e9a68d744420302b50961d49114b60def44, the issue with scopes and the commit linter should be fixed. Thanks for bringing it to my attention!