fix: only use trash on local hosts
doomemacs/doomemacs pull request #6805
Opened 2022-09-18 05:51 UTC by elken

Might be worth introducing a "remote trash command", but for now this seems to work.

Closes #6804

2022-09-20 23:00 UTC, hlissner requested changes

2022-09-20 23:00 UTC, hlissner commented on modules/os/macos/config.el
> +                 (not (string= (string-trim (shell-command-to-string "uname")) "Linux")))
Any reason you're not using `(not IS-LINUX)` here? In fact, why is this check necessary at all with `IS-MAC` already in the condition?

2022-09-20 23:01 UTC, hlissner requested changes
Could you also add the `macos` module scope and Fix: trailer to the commit message? I.e.

```
fix(macos): only use trash on local hosts

Fix: #6804
```

2022-09-21 05:24 UTC, elken commented on modules/os/macos/config.el
> +                 (not (string= (string-trim (shell-command-to-string "uname")) "Linux")))
It didn't work for me when remote

2022-09-21 09:09 UTC, hlissner commented on modules/os/macos/config.el
> +                 (not (string= (string-trim (shell-command-to-string "uname")) "Linux")))
But why would the condition get past `(not (file-remote-p default-directory))` when remote?

2022-09-21 09:22 UTC, elken commented on modules/os/macos/config.el
> +                 (not (string= (string-trim (shell-command-to-string "uname")) "Linux")))
Hm I see your point, I think I overthought it

2022-09-30 20:42 UTC, hlissner approved these changes

2022-09-30 20:42 UTC, merged

2022-09-30 20:42 UTC, hlissner commented
LGTM. Thanks again for your help!