fix(treemacs): pin latest release
doomemacs/doomemacs pull request #6812
Opened 2022-09-18 20:25 UTC by logc

A new major version of treemacs was released some days ago. The currently pinned version is from February 2022, and it stops LSP servers from starting with message "cannot load treemacs-lib" via lsp-treemacs.

Updates also lsp-treemacs to a commit that uses the latest release of treemacs.

-----
- [X] I searched the issue tracker and this hasn't been PRed before.
- [X] My changes are not on [the do-not-PR list](https://doomemacs.org/d/do-not-pr) for this project.
- [X] My commits conform to [the git conventions](https://doomemacs.org/d/git-conventions).
- [ ] ~My changes are visual; I've included before and after screenshots.~
- [ ] ~I am blindly checking these off.~
- [ ] ~Any relevant issues or PRs have been linked to.~
- [ ] ~This a draft PR; I need more time to finish it.~

2022-09-18 21:35 UTC, hlissner requested changes
To conform to [our git conventions](https://discourse.doomemacs.org/t/git-conventions/2407), please reword the commit to:

```
bump: :ui treemacs

Alexander-Miller/treemacs@b18a05b1f620 -> Alexander-Miller/treemacs@861418d9d11b
emacs-lsp/lsp-treemacs@355e468b7fa9 -> emacs-lsp/lsp-treemacs@f7ae97560cfb

A new major version of treemacs was released some days ago. The
currently pinned version is from February 2022, and it stops LSP servers
from starting with message "cannot load treemacs-lib" via lsp-treemacs.
```

2022-09-19 06:24 UTC, nqminhuit commented
Hello, I have this error when opening java project on Doom emacs 
```
File mode specification error: (file-missing Cannot open load file No such file or directory treemacs-treelib)
```
the lsp can not start and it is blocking me could you please provide a workaround while waiting for the PR merged?

2022-09-19 06:42 UTC, logc commented
@hlissner : reworded!

You change git conventions more often than I re-read git conventions 😄

2022-09-19 06:43 UTC, logc commented
@nqminhuit : you can work around this issue by pinning a different version on `packages.el`, like this:

```elisp
(package! treemacs :pin "861418d...")
(package! lsp-treemacs :pin "f7ae97560cfbc88e781a2d5b9253dace7175b918")
```

and then using `doom sync -u`

2022-09-19 07:19 UTC, nqminhuit commented
@logc 
I got this error:
```
Eager macro-expansion failure: (error "[Treemacs] :face parameter is mandatory") [2 times]
File mode specification error: (error [Treemacs] :face parameter is mandatory)
```
Do you have any idea what that is, I only have these configs for treemacs:
```
...
(after! lsp-treemacs (load-library "doom-themes-ext-treemacs"))
...
(after! prog-mode
  ;; to get faster link download for jdt, go to https://ci.eclipse.org/ls/job/jdt-ls-master/Milestone/
  (setq
   treemacs-collapse-dirs 3
   treemacs-show-cursor t
   treemacs-position 'right
   treemacs-indentation 1
   ...
  )
)
```

2022-09-19 07:30 UTC, logc commented
@nqminhuit : right, there is a message in my `*Messages*` buffer that I had not noticed, since it doesn't prevent LSP from loading. In my case, it is slightly different:

```
Eager macro-expansion failure: (wrong-number-of-arguments (1 . 1) 0)
```

If you find the reason, please share.

2022-09-19 08:02 UTC, nqminhuit commented
I tried to change to the latest commit, which is: https://github.com/Alexander-Miller/treemacs/commit/e4bb236bd5cd7c077c2207b33d2699485c405536, maybe this commit from treemacs fixed it: https://github.com/Alexander-Miller/treemacs/commit/6dc0ca1c819ab3c9c8a54599955c03087e7adcfe

```
(package! treemacs :pin "e4bb236bd5cd7c077c2207b33d2699485c405536")
(package! lsp-treemacs :pin "f7ae97560cfbc88e781a2d5b9253dace7175b918")
```
the face mandatory is over, however some lsp functions do not work (like go to definition, open java docs, ...) here is the message:
```
lsp--send-request-async: The connected server(s) does not support method textDocument/implementation.
To find out what capabilities support your server use ‘M-x lsp-describe-session’
and expand the capabilities section
```

2022-09-19 10:10 UTC, hlissner approved these changes

2022-09-20 00:29 UTC, closed without merging

2022-09-20 00:50 UTC, hlissner commented
Due to a few errors on the proposed commit of Treemacs, I bumped the module further in 5c9672a and they went away. This should resolve the issues mentioned here (and in #6814). Let me know if I've missed something; thanks for bringing it to my attention!

> You change git conventions more often than I re-read git conventions :smile:

I don't think it's changed much in the year since we adopted it. At least the bump commit [certainly hasn't](https://gist.github.com/hlissner/4d78e396acb897d9b2d8be07a103a854/501bf231eee1f1a72311d9d2db4ebba539d31fa1) (from July 31, 2021).

2022-09-20 08:31 UTC, logc commented
@hlissner : sorry, I didn't mean that the conventions change too often, I meant that I don't contribute to this project so often. I did a commit [two years ago](https://github.com/doomemacs/doomemacs/commits?author=logc), and that is why I thought I knew the conventions.