nit(mu4e): clean up formatting/indentation
doomemacs/doomemacs pull request #6823
Opened 2022-09-20 14:17 UTC by tecosaur

Just some minor formatting changes.

-----
- [ ] I searched the issue tracker and this hasn't been PRed before.
- [x] My changes are not on [the do-not-PR list](https://doomemacs.org/d/do-not-pr) for this project.
- [x] My commits conform to [the git conventions](https://doomemacs.org/d/git-conventions).
- [ ] My changes are visual; I've included before and after screenshots.
- [ ] I am blindly checking these off.
- [ ] Any relevant issues or PRs have been linked to.
- [ ] This a draft PR; I need more time to finish it.

2022-09-20 14:27 UTC, hlissner submitted a review, later dismissed

2022-09-20 22:57 UTC, hlissner requested changes

2022-09-20 22:57 UTC, hlissner commented on modules/email/mu4e/autoload/email.el
> +                                 (mu4e-clear-caches)))
The previous indentation was correct.

2022-11-07 17:45 UTC, tecosaur commented on modules/email/mu4e/autoload/email.el
> +                                 (mu4e-clear-caches)))
Done.

2023-02-17 16:33 UTC, merged