fix(csharp): fix +tree-sitter
doomemacs/doomemacs pull request #6829
Opened 2022-09-21 03:31 UTC by dradetsky

The syntax highlighting for basic csharp-mode is busted, and I don't know how to fix it upstream. I'm not even sure if it can be fixed without abandoning the current cc-langs based approach (explaining this is probably more complicated than maintainers want to hear about).

Fortunately, csharp-mode also supports an "experimental" csharp-tree-sitter-mode which actually works correctly. However, doom's +tree-sitter flag does not correctly enable this mode. I think the existing use of the flag may have been based on instructions from before it was a separate major mode. Anyway, this change seems to fix it.

-----
- [ ] I searched the issue tracker and this hasn't been PRed before.
- [ ] My changes are not on [the do-not-PR list](https://doomemacs.org/d/do-not-pr) for this project.
- [ ] My commits conform to [the git conventions](https://doomemacs.org/d/git-conventions).
- [ ] My changes are visual; I've included before and after screenshots.
- [ ] I am blindly checking these off.
- [ ] Any relevant issues or PRs have been linked to.
- [ ] This a draft PR; I need more time to finish it.

2022-09-21 11:29 UTC, jeetelongname commented
> explaining this is probably more complicated than maintainers want to hear about
If you can it would be a help :slightly_smiling_face: 

Otherwise I can open a PR that adds `csharp-tree-sitter-mode` to the block that enables tree-sitter

2022-09-21 13:33 UTC, jeetelongname commented
Ill review this in a bit

2022-09-21 17:46 UTC, dradetsky commented
@jeetelongname since you asked for the explanation: here are two files that aren't highlighted properly with regular syntax highlighting:

```
class C {
    const string s = @"ok ""esc""} str";
}
```

and

```
class Klass {
    public static bool operator ==(Klass var0, Klass var1) {
        return true;
    }
}
```

I didn't look into the second case very carefully. I was looking into how I could fix the first case, then noticed the second case, then decided to try tree-sitter, discovered that it actually worked, and decided that I didn't know if fixing regular syntax was worth doing.

Anyway, I'm not great at elisp, but as far as I can tell csharp-mode is using the cc-langs system for "multiline strings" to handle verbatim strings. In verbatim strings, `""` is a single escaped `"`, so when you encounter one you're supposed to keep the string going as far as highlighting is concerned. But the multiline string routine _requires_ that `"` be treated as a closer for the string; it's designed to handle cases like Python multiline strings where the closer is `"""`, and then you match the final quote or whatever. It's possible that I've misunderstood how this system works, but the people who wrote csharp-mode clearly didn't make it work and they're probably much better at both elisp and csharp than me.

The only possible escape hatch seems to be `c-make-ml-string-closer-re-function`. I _think_ this overrides the normal closer-finding behavior, but I'm not totally sure. In any case, I couldn't get a solution based on this to work. This is probably just me being bad at elisp, but my point is that I can't determine if there is or is not a solution within the `c-lang-defconst` way of doing things. I could learn a bunch more about elisp, but I could also just use tree-sitter, which seems to handle every case perfectly so that seemed better.

2022-09-29 11:46 UTC, jeetelongname requested changes

2022-09-29 11:46 UTC, jeetelongname commented on modules/lang/csharp/config.el
> +  (when (modulep! +tree-sitter)
Why can this not be added to the local hook [here?](https://github.com/doomemacs/doomemacs/blob/master/modules/lang/csharp/config.el#L38-L39)

This will run after tree sitter is enabled and will stay local to the buffer.

2022-09-29 11:46 UTC, jeetelongname commented on modules/lang/csharp/packages.el
> +(when (modulep! +tree-sitter)
Why is tree-sitter-indent needed here? Is it a dependency of of `csharp-tree-sitter-mode`? If not it may be better off in the `:tools tree-sitter` module or in one of the `:editor` modules

2022-09-29 23:35 UTC, dradetsky commented on modules/lang/csharp/config.el
> +  (when (modulep! +tree-sitter)
I tried that & it didn't work. I think it's because we're trying to change something that's global & which we specifically want enabled before we load tree-sitter or csharp. Anyway, I'm basically doomifying this: https://github.com/emacs-csharp/csharp-mode/#tree-sitter-support

2022-09-29 23:36 UTC, dradetsky commented on modules/lang/csharp/config.el
> +  (when (modulep! +tree-sitter)
Also, I'm pretty sure the hook you're referring to is obsolete (i.e. we don't to set that thing anymore), but I didn't want to remove it in case somebody could explain what was going on there better.

2022-09-29 23:37 UTC, dradetsky commented on modules/lang/csharp/packages.el
> +(when (modulep! +tree-sitter)
Yes, it is.

2022-10-13 17:52 UTC, jeetelongname commented on modules/lang/csharp/packages.el
> +(when (modulep! +tree-sitter)
Can you add a comment than mentions this.

2022-10-13 17:58 UTC, jeetelongname commented on modules/lang/csharp/config.el
> +  (when (modulep! +tree-sitter)
I will discuss this with @hlissner but we use the local vars hook as its only called in the places we wanted (file associated buffers being the main one)

2022-10-14 02:45 UTC, dradetsky commented on modules/lang/csharp/packages.el
> +(when (modulep! +tree-sitter)
done

2022-10-14 02:57 UTC, dradetsky commented on modules/lang/csharp/config.el
> +  (when (modulep! +tree-sitter)
I checked the source. There are comparatively few instances of `auto-mode-alist` in modules code. Of those, I checked about 8. 2 of them (`lang/cc/autoload.el`, `lang/latex/config.el`) are just top-level usages. All the others I checked did the same sort of thing I do: modify `auto-mode-alist` in the `:init` form. Of those, one (`lang/nix/config.el`) appears to have been written by hlissner (or at least he definitely touched that code according to git-blame). I didn't check who wrote the other examples that do the same thing I do.

So I mean, feel free to discuss it with him if you want, but I dunno that you necessarily have to.

2022-10-14 19:02 UTC, hlissner approved these changes

2023-02-21 05:52 UTC, closed without merging

2023-02-21 05:58 UTC, hlissner commented
Sorry for the tremendously late response. I've merged this into 883a3fa, where I've grouped the tree-sitter config under csharp-tree-sitter. I've also added tree-sitter-indent to the tree-sitter module, so it can be opted into wherever it is available (and superior to built-in indentation). Let me know how that fairs!

In any case, thanks for your help and the PR, and for the helpful examples!