fix(lib): langtool unable to honor brew install binary
doomemacs/doomemacs pull request #6857
Opened 2022-09-28 07:07 UTC by hw202207

-----

- turns out brew install language-tool has different location
- plus it provides binary tool

-----
- [x] I searched the issue tracker and this hasn't been PRed before.
- [x] My changes are not on [the do-not-PR list](https://doomemacs.org/d/do-not-pr) for this project.
- [x] My commits conform to [the git conventions](https://doomemacs.org/d/git-conventions).

2022-09-30 20:35 UTC, hlissner commented
Homebrew doesn't symlink the binary into `$PATH`?

2022-10-01 03:47 UTC, hw202207 commented
Hmm, good point! it does link to `/opt/homebrew/bin/languagetool`

2022-10-02 11:14 UTC, hlissner commented
> Hmm, good point! it does link to `/opt/homebrew/bin/languagetool`. I can change to that if preferred.

In that case, how about this more general fallback?

```diff
     (cond (IS-MAC
            (cond
             ;; is user using home brew?
             ((file-directory-p "/usr/local/Cellar/languagetool")
              (setq langtool-language-tool-jar
                    (locate-file "libexec/languagetool-commandline.jar"
                                 (doom-files-in "/usr/local/Cellar/languagetool"
                                                :type 'dirs
                                                :depth 2))))
             ;; macports compatibility
             ((file-directory-p "/opt/local/share/java/LanguageTool")
              (setq langtool-java-classpath "/opt/local/share/java/LanguageTool/*"))))
           (IS-LINUX
-           (setq langtool-java-classpath "/usr/share/languagetool:/usr/share/java/languagetool/*")))))
+           (setq langtool-java-classpath "/usr/share/languagetool:/usr/share/java/languagetool/*"))
+          ((setq langtool-bin (executable-find "languagetool"))))))


 ;; Detects weasel words, passive voice and duplicates. Proselint would be a
 ;; better choice.
 (use-package! writegood-mode
```

This way, if `languagetool` is anywhere in `$PATH`, it will use it.

2022-10-02 21:55 UTC, hw202207 commented
`execute-find` is neat! Thanks!
What I found was I have to run it before `IS-MAC` and `IS-Linux`. (pushed another commit)

2022-10-03 12:20 UTC, hlissner requested changes

2022-10-03 12:20 UTC, hlissner commented on modules/checkers/grammar/config.el
> -
Minor nit: but please restore this blank line. `use-package!` blocks are separated by two blank lines by convention.

2022-10-03 12:20 UTC, hlissner commented on modules/checkers/grammar/config.el
> +           (setq langtool-bin (executable-find "languagetool")))
To reduce the redundancy, please refactor this into:

```diff
               langtool-language-tool-jar
               langtool-java-classpath)
-    (cond (IS-MAC
+    (cond ((setq langtool-bin (executable-find "languagetool")))
+          (IS-MAC
            (cond
             ;; is user using home brew?
             ((file-directory-p "/usr/local/Cellar/languagetool")
              (setq langtool-language-tool-jar
                    (locate-file "libexec/languagetool-commandline.jar"
```
If `executable-find` returns nil, so will the whole `setq` statement.

2022-10-03 15:56 UTC, hw202207 commented on modules/checkers/grammar/config.el
> -
Reverted.

2022-10-03 15:56 UTC, hw202207 commented on modules/checkers/grammar/config.el
> +           (setq langtool-bin (executable-find "languagetool")))
Removed the redundant check.

2022-10-03 16:32 UTC, hlissner approved these changes

2022-10-03 16:33 UTC, merged

2022-10-03 16:33 UTC, hlissner commented
LGTM. Thanks for your help!