docs(notmuch): fix incorrect custom sync backend snippet
doomemacs/doomemacs pull request #6863
Opened 2022-10-01 01:58 UTC by deheras

The method for customizing +notmuch-sync-backend was changed in 19d4126 to accept a string; consequently the current example in the docs results in an error:

`user-error: Invalid notmuch backend specified: custom`

-----
- [x] I searched the issue tracker and this hasn't been PRed before.
- [x] My changes are not on [the do-not-PR list](https://doomemacs.org/d/do-not-pr) for this project.
- [x] My commits conform to [the git conventions](https://doomemacs.org/d/git-conventions).
- [x] I am blindly checking these off.

2022-10-02 11:09 UTC, hlissner requested changes
This affects the wrong branch (rewrite-docs was merged into `master` in https://github.com/hlissner/doom-emacs/commit/1f8bf7accba23b4f352d0eddd0410c4cc08abaae). Could you rebase this onto `master`?

2022-10-26 02:02 UTC, deheras commented
Sorry about that -- fixed

2022-10-27 18:04 UTC, hlissner approved these changes

2022-10-29 00:50 UTC, merged

2022-10-29 00:50 UTC, hlissner commented
Looks good to me! Thanks for your help!