tweak(dired): don't ask when kill-current-buffer
doomemacs/doomemacs pull request #6918
Opened 2022-10-28 04:28 UTC by daanturo

In dired buffers, `(buffer-modified-p (current-buffer))` frequently returns t although no modifications have been made. Which makes `doom--switch-to-fallback-buffer-maybe-a's `y-or-n-p' is always asked.

Fix by checking if current `major-mode` isn't `dired-mode`. We may need a more generic checker like `derived-mode-p` if needed.

-----
- [x] I searched the issue tracker and this hasn't been PRed before.
- [x] My changes are not on [the do-not-PR list](https://doomemacs.org/d/do-not-pr) for this project.
- [x] My commits conform to [the git conventions](https://doomemacs.org/d/git-conventions).
- [ ] My changes are visual; I've included before and after screenshots.
- [ ] I am blindly checking these off.
- [x] Any relevant issues or PRs have been linked to.
- [ ] This a draft PR; I need more time to finish it.

2022-10-28 05:25 UTC, hlissner requested changes
Can you provide steps to reproduce this? In what case(s) does dired change its buffer's modified flag?

Also, could you reword the commit message to:

```
tweak: kill-current-buffer: suppress prompt for dired-mode buffers

In dired buffers, `(buffer-modified-p (current-buffer))` frequently
returns t although no modifications have been made. Which makes
`doom--switch-to-fallback-buffer-maybe-a's `y-or-n-p' is always asked.
```

(The scope should specify where the change occurs, not what package(s) it affects. Since the change is in core, there should be no scope)

2022-10-28 05:25 UTC, hlissner commented on lisp/doom-ui.el
> +                          (not (member major-mode '(dired-mode)))
Please replace `member` with `memq`, as it is optimal for symbol lists.

2022-10-28 05:36 UTC, daanturo commented
> Can you provide steps to reproduce this? In what case(s) does dired change its buffer's modified flag?

I just try with
```bash
emacs -q ~ --eval "(print (buffer-modified-p (current-buffer)))"
# Emacs prints `t`
```
It's reproducible whether in vanilla Emacs or Doom. I happens for me nearly in every directory under `$HOME`.

2022-10-28 05:48 UTC, daanturo commented
Excuse me, I'm on Emacs 29, I'll investigate more and maybe report upstream.

2022-10-28 08:28 UTC, aikrahguzar commented
> Can you provide steps to reproduce this? In what case(s) does dired change its buffer's modified flag?

Generally this is due to some package modifying text properties without using `with-silent-modifications`. In dired's case marking files also does that. That can actually be an argument against this change since those marks might have been due to some reason but unmarking everything doesn't reset the flag and for me at least marks don't need to exist long term. If I am killing a dired buffer with marked files, it is because I am done with what I wanted to do.

2022-10-29 13:37 UTC, daanturo commented
This is indeed an Emacs 29.0 regression, now fixed https://git.savannah.gnu.org/cgit/emacs.git/commit/?id=e9bdf3d4bd5aa2be7448b0f7a968af5abb058db0.

Unless there's a need to avoid the prompt for certain modes, I think we can close this PR.

2022-10-29 20:00 UTC, hlissner commented
> Unless there's a need to avoid the prompt for certain modes, I think we can close this PR.

In that case I think it can be left as is. Thanks for looking into it and for your help!

2022-10-29 20:00 UTC, closed without merging