feat(javascript): add coffee-mode
doomemacs/doomemacs pull request #6935
Opened 2022-11-04 17:12 UTC by offbyone

I noticed when opening coffeescript files that coffee-mode is missing; I added the latest commit (pinned) for it here.

-----
- [X] I searched the issue tracker and this hasn't been PRed before.
- [X] My changes are not on [the do-not-PR list](https://doomemacs.org/d/do-not-pr) for this project.
- [X] My commits conform to [the git conventions](https://doomemacs.org/d/git-conventions).
- [X] Any relevant issues or PRs have been linked to.

2022-11-08 17:26 UTC, iyefrat requested changes
Can you put this behind a `+coffeescript` flag? I don't think coffeescript is used widely enough to be on by default.

(heads up, this PR might be closed before it gets merged due to a pending repo split. If this is the case you should re open it on the `modules` repo once that's a thing)

2022-11-08 17:44 UTC, offbyone commented
> Can you put this behind a `+coffeescript` flag? I don't think coffeescript is used widely enough to be on by default.

Done.

2022-11-08 19:07 UTC, iyefrat requested changes
few points:
1. I forgot to say last time, but please add the package to the list of packages in the readme
2. you added the configuration of the package under `+tree-sitter` by mistake
3. you also need to flag-gate the package install in `packages.el`

2022-11-08 20:02 UTC, elken commented on modules/lang/javascript/README.org
> +  [[https://coffeescript.org/][Coffeescript]] is a language that compiles into javascript. This flag will installs and
*install and enable

2022-11-08 20:02 UTC, elken commented on modules/lang/javascript/README.org
> +- doom-package:coffee-mode if [[doom-module::+coffeescript]]
[[doom-package:coffee-mode]]

2022-11-08 21:22 UTC, offbyone commented on modules/lang/javascript/README.org
> +- doom-package:coffee-mode if [[doom-module::+coffeescript]]
Man... it is _hard_ to tell which things you need to add in org-mode sometimes :) 

The text for that in my editor looked _exactly_ the same as the others. I had to actually `find-file-literally` to see what the difference was.

2022-11-09 23:46 UTC, iyefrat requested changes
Hey, a few more points, sorry for the repeated revisions on such a small PR but I think they're important to have. Also, please squash everything to one commit once you're done.

2022-11-09 23:46 UTC, iyefrat commented on modules/lang/javascript/README.org
> +  enables `coffee-mode`.
```suggestion
- +coffeescript ::
 Enables support for [[https://coffeescript.org/][Coffeescript]].
```

Sorry to nitpick, but doom packages have a special syntax (also, \`foo\` is markdown verbatim, regular or verbatim is =foo=, and doom's docs have a separate thing), but either way I think that explaining this here is redundant with the `Packages` section

2022-11-09 23:46 UTC, iyefrat commented on modules/lang/javascript/README.org
> +- Coffeescript & JSX support ([[doom-package:coffee-mode]])
These should be split to separate lines because `coffee-mode` only effects the coffeescript part (as far as i'm aware).

2022-11-09 23:46 UTC, iyefrat commented on modules/lang/javascript/README.org
> +- [[doom-package:coffee-mode]] if [[doom-module::+coffeescript]]
```suggestion
- [[doom-package:coffee-mode]]* if [[doom-module::+coffeescript]]
```
see the `ivy` module for examples of this syntax. i don't think it's documented in the repo yet, but i'm not sure maybe i missed it.

2022-11-09 23:47 UTC, iyefrat commented on modules/lang/javascript/README.org
> +- doom-package:coffee-mode if [[doom-module::+coffeescript]]
hot tip: doing `SPC m l t` will **t**oggle the **l**inks to appear in plaintext mode so they are easier to edit

2022-11-10 07:41 UTC, elken commented on modules/lang/javascript/README.org
> +- [[doom-package:coffee-mode]] if [[doom-module::+coffeescript]]
It's only recently gone live, I think documenting is a good shout

2022-11-10 07:43 UTC, elken commented on modules/lang/javascript/README.org
> +- Coffeescript & JSX support ([[doom-package:coffee-mode]])
Yeah coffee-mode doesn't do anything with jsx so they should be different lines

2022-11-10 07:45 UTC, elken commented on modules/lang/javascript/config.el
> +(when (modulep! +coffeescript)
I think stylistically we prefer `:when` over wrapping in a `when` form

2022-11-24 20:40 UTC, offbyone commented
Is this suitable to merge?

2022-11-30 12:51 UTC, elken commented
After speaking to Henrik about this, it seems this has [already been removed](https://github.com/doomemacs/doomemacs/commit/ec95669710dead9e7e21dc429553a7026dbdefb5) one for being too trivial, so this is likely to be rejected for the same reason.

I'll leave it to Henrik for the final say though :)

2023-02-23 06:07 UTC, hlissner commented
Sorry for the late response. Unfortunately, I must turn this PR down. coffee-mode was intentionally removed from this module in 657b326e92a3 because I deemed the language too niche to be included by default, and its configuration is trivial enough for users to install themselves. Thanks for the PR, in any case!

2023-02-23 06:07 UTC, closed without merging