require consult in lookup autoloads
doomemacs/doomemacs pull request #6967
Opened 2022-11-27 17:13 UTC by clatisus

Replace this with a summary of what you've changed and why, followed by a list of issues it affects, if any.

References [Discord thread](https://discord.com/channels/406534637242810369/1046468107822170142)

-----
- [ ] I searched the issue tracker and this hasn't been PRed before.
- [ ] My changes are not on [the do-not-PR list](https://doomemacs.org/d/do-not-pr) for this project.
- [ ] My commits conform to [the git conventions](https://doomemacs.org/d/git-conventions).

When `(lookup +docsets)` enabled, open Doom Emacs, `SPC s k` shows error: `Symbol’s function definition is void: consult--async-throttle`.

This is due to `consult` not loaded.

2022-11-27 19:47 UTC, clatisus commented
Gently ping @hlissner PTAL

2022-11-28 23:28 UTC, iyefrat requested changes

2022-11-28 23:28 UTC, iyefrat commented on modules/tools/lookup/autoload/docsets.el
>          (dash-docs-docsets
This shouldn't be required at the top level, since `consult` is only used with the `:completion vertico` module. Please move it to be under the `(modulep! :completion vertico)` section

2022-11-29 08:47 UTC, clatisus commented on modules/tools/lookup/autoload/docsets.el
>          (dash-docs-docsets
Good suggestion! Comment addressed~

2022-11-30 17:41 UTC, iyefrat requested changes
Please squash the change into one commit, and follow the commit conventions listed in the PR checklist, the title of the PR follow the convention, but I'd suggest a title like:

```
fix(lookup): require consult in +lookup/in-docsets
```

2022-11-30 18:48 UTC, clatisus commented
> Please squash the change into one commit, and follow the commit conventions listed in the PR checklist, the title of the PR follows the convention, but I'd suggest a title like:
> 
> ```
> fix(lookup): require consult in +lookup/in-docsets
> ```

This is my first PR to doom, sorry I didn't notice the conventions 😃.

2022-12-05 07:23 UTC, clatisus commented
Gently ping @iyefrat @hlissner

2022-12-09 11:21 UTC, iyefrat approved these changes

2022-12-12 08:32 UTC, clatisus commented
Hi @hlissner could you please help me merge this PR?

2022-12-15 08:53 UTC, clatisus commented
Hi @iyefrat , do you have merge permission? This PR have been there few days, so if you got time please help merge it, thanks!

2022-12-15 10:37 UTC, iyefrat commented
fyi i don't have merge permissions and henrik is unavailable at the moment, this will get merged soon after he gets back i expect

2023-01-10 10:36 UTC, clatisus commented
Gently ping @hlissner in case this PR got missed somehow.

2023-02-23 02:14 UTC, hlissner approved these changes

2023-02-23 02:14 UTC, merged

2023-02-23 02:15 UTC, hlissner commented
LGTM! Thanks for your help!