bump :tools tree-sitter
doomemacs/doomemacs pull request #6973
Opened 2022-11-30 04:07 UTC by jeetelongname

Replace this with a summary of what you've changed and why, followed by a list of issues it affects, if any.

Fixes #0000
References #0000
Replaces #0000

-----
- [x] I searched the issue tracker and this hasn't been PRed before.
- [ ] My changes are not on [the do-not-PR list](https://doomemacs.org/d/do-not-pr) for this project.
- [x] My commits conform to [the git conventions](https://doomemacs.org/d/git-conventions).
- [ ] My changes are visual; I've included before and after screenshots.
- [ ] I am blindly checking these off.
- [x] Any relevant issues or PRs have been linked to.
- [ ] This a draft PR; I need more time to finish it.

- Bump the module
- add haskell support

2022-11-30 17:49 UTC, iyefrat commented
> add haskell support

Thanks yeet!

2022-11-30 20:43 UTC, jeetelongname commented
The highlighting is interesting, but it has grown on me so I have left it as is

2023-02-18 19:20 UTC, hlissner requested changes
LGTM, but would you mind re-bumping the :tools tree-sitter module? All three packages have new commits.

2023-02-18 19:22 UTC, jeetelongname commented
Sure, once i have emacs set up on my new machine ill bump the module again

2023-02-22 01:34 UTC, hlissner requested changes

2023-02-22 01:34 UTC, hlissner commented on modules/lang/ess/config.el
> +      (add-hook 'ess-r-mode-local-vars-hook #'tree-sitter! 'append))
Please correct the indentation.

2023-02-22 01:34 UTC, hlissner commented on modules/lang/lua/config.el
> +    (add-hook! 'fennel-mode-local-vars-hook 'tree-sitter!)))
Please append this hook, use `add-hook` instead, and sharp-quote `tree-sitter!`:

```elisp
(add-hook 'fennel-mode-local-vars-hook #'tree-sitter! 'append)
```

2023-02-22 01:44 UTC, jeetelongname commented
@hlissner Done and Done

2023-02-22 01:51 UTC, hlissner approved these changes

2023-02-22 01:51 UTC, merged

2023-02-22 01:51 UTC, hlissner commented
Great work, as always! Thanks again for your help!