feat(default): add C-h/C-l evil keybinds for vertico
doomemacs/doomemacs pull request #7001
Opened 2022-12-20 15:55 UTC by BenediktBroich

Add C-h/C-l keybinding for directory up/directory enter or embark preview to vertico-map. The keybindings are currently not used. I try to replicate the C-h/C-l behavior from helm that i added in these pull requests: [pr](https://github.com/doomemacs/doomemacs/pull/6853) and was merged [here](https://github.com/doomemacs/doomemacs/commit/6887998c23d31430bde619e52d86de7b0ddf5c96)
 
Fixes 0
References 0
Replaces 0

-----
- [x] I searched the issue tracker and this hasn't been PRed before.
- [x] My changes are not on [the do-not-PR list](https://doomemacs.org/d/do-not-pr) for this project.
- [x] My commits conform to [the git conventions](https://doomemacs.org/d/git-conventions).
- [ ] My changes are visual; I've included before and after screenshots.
- [ ] I am blindly checking these off.
- [ ] Any relevant issues or PRs have been linked to.
- [ ] This a draft PR; I need more time to finish it.

2022-12-31 22:22 UTC, iyefrat requested changes

2022-12-31 22:22 UTC, iyefrat commented on modules/completion/vertico/autoload/vertico.el
> +  "Enter directory or embark preview on current candidate."
What is the reason for using this custom function over the built in `vertico-directory-enter`?

2022-12-31 22:22 UTC, iyefrat commented on modules/completion/vertico/autoload/vertico.el
> +              (embark-dwim)))))))
don't really love the use of `embark-dwim` here, makes it harder to reason what this function is meant to be doing.

2022-12-31 22:22 UTC, iyefrat commented on modules/config/default/+evil-bindings.el
> +          "C-l"  #'+vertico/directory-enter))))
I know this PR got accepted for helm, but binding something on `C-h` in a vertico session does have a side effect, which is losing the ability to `C-h k` in a vertico completion session, which is pretty useful. Not really sure which way that should go, Henrik will weight in when he gets to this PR.

2023-01-01 09:13 UTC, BenediktBroich commented on modules/completion/vertico/autoload/vertico.el
> +  "Enter directory or embark preview on current candidate."
So `vertico-directory-enter` exits the search buffer. This function allows you to complete the directory and preview files.

2023-01-01 09:15 UTC, BenediktBroich commented on modules/config/default/+evil-bindings.el
> +          "C-l"  #'+vertico/directory-enter))))
True. :)

2023-03-22 01:00 UTC, agzam commented on modules/completion/vertico/autoload/vertico.el
> +  (if (>= vertico--index 0)
FYI, lispers prefer to use `<` because prefix notation allows multiple arguments and can be confusing.

```suggestion
  (if (<= 0 vertico--index)
```

2023-03-22 22:30 UTC, closed without merging

2023-03-22 22:41 UTC, hlissner commented
After a couple tweaks I've merged this into 890f200. The conditional keybinds are a bit verbose, but I'll revisit its elegance after v3.

> I know this PR got accepted for helm, but binding something on C-h in a vertico session does have a side effect, which is losing the ability to C-h k in a vertico completion session, which is pretty useful. Not really sure which way that should go, Henrik will weight in when he gets to this PR.

To help soften the blow, I've made C-h (and C-l) conditional on whether the current session is a file command. That said, in situations where C-h is remapped, you can always use F1 instead.

> don't really love the use of embark-dwim here

I agree with that. Since I plan to dig into embark's guts post-v3, I'll see if I can make the embark call there more explicit then, unless another PR can beat me to it.

-----

Anyhow, thanks for the PR and input!