module: Add corfu
doomemacs/doomemacs pull request #7002
Opened 2022-12-20 18:45 UTC by LuigiPiucco

Implements a [corfu](https://github.com/minad/corfu) module, which can be used as a lightweight alternative to company. Overview of features (unchecked means it is not implemented, but planned to be):

- [x] Basic integration (keybinds, general settings, lazy-loading, ...);
- [x] Configurable auto-completion;
- [x] Manual completion;
- [x] Integration with vertico and embark;
- [x] LSP as provider;
- [x] Terminal Emacs support;
- [x] Documentation popup (only in graphical Emacs, needs support from upstream for terminal);
- [x] Optional Tab'n'Go-style keybinds;
- [x] Optional orderless multiple component search;
- [x] Optional icons;
- [ ] Mode-specific CAPFs, such as for LaTeX commands or HTML entities; 
- [ ] Dictionary/ispell completion;
- [ ] Eshell completion via pcomplete (probably with [pcmpl-args](https://github.com/JonWaltman/pcmpl-args.el));
- [ ] Snippets integration (may be worth waiting for a [tempel](https://github.com/minad/tempel) module);
- [ ] Integration with helm and/or ido (maybe ivy too, if it isn't removed);

Fixes  #5600
Replaces  #5600 

Additional discussion happened on Discord, it was there that I got the suggestion to open a draft PR for public commentary.

Some inspiration came from @gagbo's [module](https://git.sr.ht/~gagbo/doom-config/tree/8e3014985774d68c6f768dd4e3c8045255cd87d1/item/modules/completion/corfu), though I only discovered it after writing most of this one.

-----
- [x] I searched the issue tracker and this hasn't been PRed before.
- [ ] My changes are not on [the do-not-PR list](https://doomemacs.org/d/do-not-pr) for this project. (Unsure, I think it is now but may not be after v3)
- [x] My commits conform to [the git conventions](https://doomemacs.org/d/git-conventions) (I hope so, at least).
- [ ] I am blindly checking these off.
- [x] Any relevant issues or PRs have been linked to.
- [x] This a draft PR; I need more time to finish it.

2023-02-03 19:39 UTC, Roger-Roger-debug commented
I noticed a small issue that when enabling `(corfu +icons)` the completion menu doesn't show all entries. I set `corfu-count` to 5 however only 4 get rendered. 
![image](https://user-images.githubusercontent.com/29002762/216692130-862d5f47-a524-4a42-93e5-df5275d92ecd.png)

Same settings but without the icons
![image](https://user-images.githubusercontent.com/29002762/216692316-1ef58807-c86e-4a26-aa79-fa2f97f6a4a9.png)

2023-02-04 15:05 UTC, LuigiPiucco commented
I had noticed that, though failed to fix it before. Plus, since review may take a while due to Henrik's move, I was waiting to see if it was just a temporary bug. I will look at it again now, maybe now there's a fix. Also, I didn't see it was related to the icons (which are implemented separately, via [kind-icon](https://github.com/jdtsmith/kind-icon)). That information may prove helpful.

2023-02-05 14:48 UTC, Roger-Roger-debug commented
If you look closely you can see that there's a lot more space between the entries in the version with icons. I assume the icons get rendered too big and cause every entry to be bigger than it's supposed to be.

I'll try and look into it myself a bit but doubt that I'll find anything, much less a fix.

2023-02-05 16:29 UTC, LuigiPiucco commented
I think I fixed it, the issue I found is described in the commit message. Could you check if this fixes it for you as well?

2023-02-05 18:36 UTC, Roger-Roger-debug commented
Almost, I had to change the value of `+corfu-icon-height` to 0.8 as 0.9 was still too large.

2023-04-05 18:01 UTC, bdarcus commented
Not sure if this is an issue with this module per se, but when trying it just now in `nxml-mode`, I noticed `cape-ispell` is first in `completion-at-point-functions` , and `rng-completion-at-point` is second/last. It should be reversed.

Now, when trying to complete an XML element, for example, you can end up with this (spelling isn't really relevant when completing an XML node):

![image](https://user-images.githubusercontent.com/1134/230164770-3bdc3769-c069-489e-93d0-4f2216ac15ac.png)

2023-04-05 18:45 UTC, bdarcus commented on modules/completion/corfu/config.el
> +                (add-to-list 'completion-at-point-functions #'cape-ispell))))
Maybe the depth could be adjusted here so it's not placed first in modes where it doesn't make sense (like where editing `XML` or `HTML`)?

2023-04-05 23:24 UTC, bdarcus commented on modules/completion/corfu/config.el
> +                (add-to-list 'completion-at-point-functions #'cape-ispell))))
On a related point, I Just realized that minad just pushed this commit:

```
        36256bb Deprecate cape-ispell in favor of cape-dict
```

2023-04-07 11:13 UTC, bdarcus commented on modules/completion/corfu/config.el
> +                (add-to-list 'completion-at-point-functions #'cape-ispell))))
I had the earlier comments on `cape-ispell`, but I can't see anything wrong with the code.

But I left the one about it being deprecated (though I haven't manged to get that working correctly).

2023-04-07 17:42 UTC, LuigiPiucco commented on modules/completion/corfu/config.el
> +                (add-to-list 'completion-at-point-functions #'cape-ispell))))
I'm working on rebasing this and pushing some fixes, I believe the issue with ispell appearing first can be solved by just appending it (by default, `add-to-list` prepends). I've also swapped out `cape-ispell` for `cape-dict`, as mentioned in the deprecation commit.

2023-04-07 17:59 UTC, bdarcus commented
>
> What was confusing me though you want looks like the spelling capf should
only be added to the default writing mode (org, markdown, latex)?

>
> Message ID: ***@***.***>
>

2023-04-07 19:46 UTC, bdarcus commented on modules/completion/corfu/config.el
> +                (add-to-list 'completion-at-point-functions #'cape-ispell))))
That fixes it all for me.

What was confusing me earlier was that it looked like, based on config.el, the spelling capf should only be added in the default writing modes (org, markdown, latex), so I'm not sure why it was active at all in nxml.

2023-04-07 20:14 UTC, LuigiPiucco commented on modules/completion/corfu/config.el
> +                (add-to-list 'completion-at-point-functions #'cape-ispell))))
It also activates in comments and strings even in programming modes, perhaps there's a bug somewhere, but I'm considering removing dict completion altogether, or writing something custom based on ispell. `cape-dict` just greps a fixed wordlist, which may not even exist on many systems (NixOS, for instance, which I use).

2023-04-07 20:34 UTC, bdarcus commented on modules/completion/corfu/config.el
> +                (add-to-list 'completion-at-point-functions #'cape-ispell))))
To clarify, the latest changes work as expected for me, including in XML comments.

2023-04-17 21:51 UTC, minad commented on modules/completion/corfu/config.el
> +                       (cape-capf-inside-string #'cape-dict)))
I recommend to avoid `cape-super-capf`. It is mostly not needed. In this case you could simply add two capfs (inside comment and inside string) to `completion-at-point-functions`, since they are mutually exclusive anyway.

2023-04-17 21:52 UTC, minad commented on modules/completion/corfu/config.el
> +  (setq dabbrev-ignored-buffer-regexps '("\\.\\(?:pdf\\|jpe?g\\|png\\)\\'")))
On Emacs 29 (or 28?) you can also `dabbrev-ignored-buffer-modes`.

2023-04-17 21:54 UTC, minad commented on modules/completion/corfu/config.el
> +    :depth 2)
Regarding `cape-tex` and `cape-sgml` - they are not meant to be used in TeX or html modes, since these Capfs don't complete entities. These Capfs just use the entity name to complete unicode characters conveniently, e.g., when you edit code which allows Unicode like Julia.

2023-04-17 21:56 UTC, minad commented on modules/completion/corfu/config.el
> +(defvar +corfu-ispell-completion-modes '(org-mode markdown-mode text-mode)
Instead of the name `corfu-ispell` or `cape-ispell` you should probably use `corfu-dict`, since these Capfs are about completing words from a dictionary. (The obsoleted `cape-ispell` did just the same as the new `cape-dict`, grepping through /usr/share/dict/words).

2023-04-18 02:32 UTC, peterhoeg commented on modules/completion/corfu/config.el
> +  (setq dabbrev-ignored-buffer-regexps '("\\.\\(?:pdf\\|jpe?g\\|png\\)\\'")))
emac29 only

2023-06-03 08:28 UTC, shroomist commented
I'm curious what's the status of this?
I've been rebasing this branch for quite a while onto the master with my local setup.
do I still need to do it? 🤔

2023-06-15 13:50 UTC, andrewpeck commented
I've been using this module for a few months now and am quite happy with it. Thanks so much for your great work on this, I really look forward to seeing it merged in.. I too have been rebasing onto master.

One issue I've run into though.. in an org mode file RET calls `+org/return` and generates an error for me:

```
Debugger entered--Lisp error: (wrong-type-argument frame-live-p nil)
  frame-visible-p(nil)
  (and t (frame-visible-p corfu--frame))
  (if (and t (frame-visible-p corfu--frame)) (corfu-insert) (org-return electric-indent-mode))
  +org/return()
  funcall-interactively(+org/return)
  command-execute(+org/return)
```

corfu-frame is nil for me so `(frame-visible-p corfu--frame)` fails. Without truly understanding, I just added a check that `corfu--frame` is non-nil into the `and`: 

```
(defun +org/return ()
  "Call `org-return' then indent (if `electric-indent-mode' is on)."
  (interactive)
  (if (and (modulep! :completion corfu)
           corfu--frame
           (frame-visible-p corfu--frame))
      (corfu-insert)
    (org-return electric-indent-mode)))
```

This seems to resolve my issue.

Thanks again!

2023-07-06 17:09 UTC, LuigiPiucco commented on modules/completion/corfu/config.el
> +    :depth 2)
Indeed, I thought they were for tex and html completion, upon actually trying them I realize what they're for. I removed those capfs in the rebase, I think it would be best to add them in the lang modules later.

2023-07-06 17:11 UTC, LuigiPiucco commented on modules/completion/corfu/config.el
> +  (setq dabbrev-ignored-buffer-regexps '("\\.\\(?:pdf\\|jpe?g\\|png\\)\\'")))
I removed dabbrev config, it wasn't very useful in the time I had it enabled. Perhaps I'll revisit it later for buffers that have no other completion mechanism.

2023-07-06 17:15 UTC, minad commented on modules/completion/corfu/config.el
> +  (setq dabbrev-ignored-buffer-regexps '("\\.\\(?:pdf\\|jpe?g\\|png\\)\\'")))
In my personal config I use `cape-dabbrev` and `cape-dict` in `text-mode` buffers. There they are quite useful and don't interfere with programming mode completion, e.g., lsp. But in the end it is a matter of taste. The better default is certainly to install only few Capfs.

2023-07-06 17:17 UTC, LuigiPiucco commented on modules/completion/corfu/config.el
> +(defvar +corfu-ispell-completion-modes '(org-mode markdown-mode text-mode)
Dictionary completion was removed in the rebase as well. While it is useful, I think we need support for something better than simple dictionary files. Not sure if that's something we can resolve in the scope of Doom, though. I tried using dictionary programs, such as aspell and hunspell, but they're a real hassle to configure, it doesn't seem worth it.

2023-07-06 17:19 UTC, LuigiPiucco commented on modules/completion/corfu/config.el
> +                       (cape-capf-inside-string #'cape-dict)))
Resolved due to removal of ispell. The suggestion is good though, I don't know how I didn't see that.

2023-07-06 17:25 UTC, minad commented on modules/completion/corfu/config.el
> +(defvar +corfu-ispell-completion-modes '(org-mode markdown-mode text-mode)
Yes, dictionary completion is problematic. I don't think Hunspell/Aspell are an ideal fit for completion. These programs are good for corrections, but not for word expansions. Personally I switched to my [Jinx](/minad/jinx) package for correction, which uses Hunspell/Aspell behind the scene, but through the Enchant library.

In https://github.com/minad/cape/commit/28a2a1655026ae68ed9180db6527694334c5d1d4 I made some recent changes which should improve the behavior of `cape-dict`, in particular in combination with dictionaries sorted by word frequency. See for example https://wortschatz.uni-leipzig.de/en/download/English.

2023-07-06 17:25 UTC, LuigiPiucco commented
I rebased and pushed some extra commits addressing the review and the `+org/return` issue. Mostly it entails the removal of some incomplete features, see the comments in the conversations. About a merging ETA, I do not know, but it may be a while, since we need to wait for v3.0.

2023-07-24 17:53 UTC, hlissner requested changes
How ready is this to merge? Barring a few small changes (and some refactoring, which I'll look into after it is merged), I'd be willing to merge it now and tackle the other concerns as we move forward.

2023-07-24 17:53 UTC, hlissner commented on modules/completion/corfu/packages.el
> +  (package! corfu-terminal))
Please pin these packages. The quickest way is to run `M-x doom/bump-packages-in-buffer` in this file.

2023-07-24 17:53 UTC, hlissner commented on modules/completion/corfu/config.el
> +  (plist-put svg-lib-style-default :height +corfu-icon-height))
It's a little bothersome that we are imposing two icon libraries, but I suppose this is a greater problem to sort out later.

2023-07-24 17:53 UTC, hlissner commented on modules/lang/org/autoload/org.el
> +    (org-return electric-indent-mode)))
This seems like something that ought to be a corfu keymap. Does corfu not have a transient keymap while it is active, like how company has `company-active-map`?

2023-07-25 00:48 UTC, LuigiPiucco commented on modules/lang/org/autoload/org.el
> +    (org-return electric-indent-mode)))
This is interesting. It does, it's `corfu-map`, which only activates while the popup is shown, as opposed to `corfu-mode-map`. This works for all other modes I tried, but it seems in org-mode specifically RET resolves to `evil-org-mode-map` instead, and calls `+org/return`. My explanation is that, while I checked `minor-mode-overriding-map-alist` and it does receive `corfu-map`'s bindings when and only when the popup is shown, the binding there was for key 13 (return) and _global_. Whereas the binding for `+org/return` in `evil-org-mode-map`, while having lower precedence, was _local to insert state_, for key 13 and also symbol `return`. The solution was to add an explicit binding for insert state, but for whatever reason it has to be done with `evil-collection-define-key`. `map!` and `evil-define-key` don't work, I don't know why. It's late here, I may only be able to push changes tomorrow, but I'll leave this comment, in case you know why this is the behavior we get.

2023-07-25 01:43 UTC, LuigiPiucco commented
I believe I've addressed the comments in the last push. I left the one about the keymap open, since I'm not fully confident there isn't a cleaner solution than what I pointed out. It's implemented [here](https://github.com/doomemacs/doomemacs/pull/7002/commits/32a2be838fe5479db0987ced71857db6403ae672). For now, I need to sleep, but if the current modifications are sufficient, I can't think of a reason not to merge. The features that were removed/not implemented can be revisited later, in a separate PR.

2023-07-25 02:30 UTC, peterhoeg commented on modules/tools/lsp/+lsp.el
> +    (setq lsp-completion-provider :none)
Isn't this specific to `lsp-mode` (and thus not necessary or with different requirements for eglot)? In principal there is of course no issue setting a variable, but it doesn't quite pass the smell test.

2023-07-25 15:33 UTC, LuigiPiucco commented on modules/tools/lsp/+lsp.el
> +    (setq lsp-completion-provider :none)
Isn't this file loaded only with lsp-mode active, though? Plus, it's part of `lsp-mode`'s `:config`, so it should only run after loading the package.
I've been using Eglot recently, and the variable assignment really doesn't run. I will double check the `lsp-mode` version, however, just in case I broke it accidentally.

2023-07-25 20:45 UTC, elken commented on modules/lang/org/autoload/org.el
> +    (org-return electric-indent-mode)))
I just opted to [advise](https://github.com/elken/doom/blob/master/modules/completion/corfu/config.el#L75-L80) org return.

2023-07-25 20:46 UTC, elken commented on modules/tools/lsp/+lsp.el
> +    (setq lsp-completion-provider :none)
Yes that should only be loaded when eglot is not named so it's fine

2023-07-25 23:37 UTC, LuigiPiucco commented on modules/tools/lsp/+lsp.el
> +    (setq lsp-completion-provider :none)
I'll resolve it then.

2023-07-26 23:20 UTC, LuigiPiucco commented
We have snippets now. @elken provided feedback and initial code for that. Also, can the remaining reviews be resolved, or do they need further modification?

2023-07-27 10:41 UTC, elken reviewed
I also don't think it's unreasonable to add a flag to pull in orderless here rather than depending on `:completion vertico`, it doesn't depend on the whole stack and it's not impossible that someone might want say ivy and corfu

2023-07-27 10:41 UTC, elken commented on modules/completion/corfu/+yas-capf.el
> +;;; Capf for yasnippet. Inspired by @elken's yas-capf.
I don't really understand why you ripped bits out of my package here rather than just using it straight-up, this seems much more unnecessarily complicated

2023-07-27 10:41 UTC, elken commented on modules/completion/corfu/config.el
> +(defvar +corfu-auto-delay 0.1
This doesn't need to be a `defvar`, `setq`-ing auto-delay is fine

2023-07-27 10:41 UTC, elken commented on modules/completion/corfu/config.el
> +(defvar +corfu-auto-prefix 2
Same as above

2023-07-27 10:41 UTC, elken commented on modules/completion/corfu/config.el
> +        corfu-quit-at-boundary (unless +corfu-want-multi-component 'separator t)
I don't think these two lines are working as you think they are

2023-07-27 10:41 UTC, elken commented on modules/completion/corfu/config.el
> +  (when (and (modulep! :tools lsp) (not (modulep! :tools lsp +eglot)))
This doesn't have a matching eglot version, though I'm not convinced either are needed

2023-07-27 10:41 UTC, elken commented on modules/completion/corfu/config.el
> +  (when (modulep! :editor evil)
What's this for?

2023-07-27 10:41 UTC, elken commented on modules/completion/corfu/config.el
> +(when (modulep! :completion vertico)
Should be part of main `:config` body for corfu & `(after! vertico`

2023-07-27 10:41 UTC, elken commented on modules/completion/corfu/config.el
> +  (when (and (modulep! :tools lsp) (not (modulep! :tools lsp +eglot)))
What's this for?

2023-07-27 10:41 UTC, elken commented on modules/completion/corfu/config.el
> +  (plist-put svg-lib-style-default :height +corfu-icon-height))
Integrating all-the-icons would be more manual than kind-icon, but yeah it's not ideal

2023-07-27 10:41 UTC, elken commented on modules/completion/corfu/config.el
> +(use-package! corfu-terminal
Might be worth also adding in https://codeberg.org/akib/emacs-corfu-doc-terminal but I haven't used it in terminal for so long now, it might not be needed anymore

2023-07-27 10:41 UTC, elken commented on modules/completion/corfu/config.el
> +(setq read-extended-command-predicate
What's this for?

2023-07-27 23:36 UTC, LuigiPiucco commented on modules/completion/corfu/config.el
> +(use-package! corfu-terminal
I tried, but it depends on the deprecated [corfu-doc](https://github.com/galeo/corfu-doc), and doesn't work with the in-built popupinfo.

2023-07-27 23:40 UTC, LuigiPiucco commented on modules/completion/corfu/config.el
> +  (when (and (modulep! :tools lsp) (not (modulep! :tools lsp +eglot)))
It was supposed to allow showing snippet completions even if LSP ones were found, by making `lsp-completion-at-point` non-exclusive. It still doesn't show them still, though. I'll remove it soon.

2023-07-27 23:42 UTC, LuigiPiucco commented on modules/completion/corfu/config.el
> +(when (modulep! :completion vertico)
Yes, that is indeed better. I'll push it later.

2023-07-27 23:55 UTC, LuigiPiucco commented on modules/completion/corfu/config.el
> +  (when (modulep! :editor evil)
This is for the issue with `+org/return`. It's bound in a way that has precedence over `corfu-map`. Just adding one more clause to the `map!` call above does nothing, because it never triggers the keybind. Using `evil-collection-define-key` works, however.

The alternatives considered so far are this,  `add-advice`-ing `+org/return`, and modifying it's definition. These last two seem more convoluted to me, because then we don't fix the keybinding, we alter the bound-function to work around the binding issue. But I can swap it if needed.

2023-07-27 23:57 UTC, LuigiPiucco commented on modules/completion/corfu/config.el
> +        corfu-quit-at-boundary (unless +corfu-want-multi-component 'separator t)
Indeed they are not. I don't know why I thought last night that `unless` would work here, they were `if`s before.

2023-07-27 23:58 UTC, LuigiPiucco commented on modules/completion/corfu/config.el
> +  (when (and (modulep! :tools lsp) (not (modulep! :tools lsp +eglot)))
Upon testing, neither is really needed. It will be removed.

2023-07-28 00:01 UTC, LuigiPiucco commented on modules/completion/corfu/config.el
> +(defvar +corfu-auto-delay 0.1
Yes, it works actually. Good catch. I thought letting the user set it in their config.el would be too late, but seems not.

2023-07-28 00:02 UTC, LuigiPiucco commented on modules/completion/corfu/config.el
> +(setq read-extended-command-predicate
I'm unsure. Probably a mistake.

2023-07-28 00:36 UTC, LuigiPiucco commented on modules/completion/corfu/+yas-capf.el
> +;;; Capf for yasnippet. Inspired by @elken's yas-capf.
About not putting this logic in Doom, but in a separate package, yes, that would be ideal.

About my logic being complicated, it really was. I had a wrong assumption about the way the completion table was supposed to behave. I'll be pushing a simplified version soon. We can also look into separating some form of this into a package, or perhaps adding to cape as optional.

2023-07-28 04:56 UTC, peterhoeg commented on modules/completion/corfu/packages.el
> +  (package! orderless :pin "e6784026717a8a6a7dcd0bf31fd3414f148c542e"))
How do we make sure to keep this pin in sync with orderless from vertico?

2023-07-29 15:35 UTC, LuigiPiucco commented on modules/completion/corfu/packages.el
> +  (package! orderless :pin "e6784026717a8a6a7dcd0bf31fd3414f148c542e"))
Upon testing, `doom sync` seems to always favor vertico's pin, probably because it comes last in my `init.el`. I can see a few alternatives:

- Tell the user to keep corfu before vertico in the documentation (and do the same in the default config);
   This doesn't really sync the two, just ensures vertico prevails. I believe breakage would be rare, as all that's done here is introduce orderless as a completion category and change some defaults if it's there. The version mostly doesn't matter, since we don't use its API.
- Introduce logic into CI to check they are the same;
  This could be done as a one-off check, or perhaps we could change Doom's CLI to check for these inconsistencies, instead of picking the last. Then run a `doom sync -u` in CI to ensure there are none. I think either of these are out-of-scope for the PR, though, especially now with the rewrite ongoing.

I can  implement the first in the next update, or we can leave as-is until the rewrite. I'm fine with whichever the maintainers prefer.

2023-07-29 17:35 UTC, LuigiPiucco commented on modules/completion/corfu/config.el
> +  (plist-put svg-lib-style-default :height +corfu-icon-height))
This is probably for later, but I'll ponder a bit on the alternatives.

1. Keeping `kind-icon` here: It's less code for us to worry about and maintain, since it already works like plug-and-play with `corfu`. Also, since it supports `company` as well and (from a quick look) it seems Doom implements its own icon logic for `company-box`, we could add it there for consistency and possibly simplify some code. At the cost of one more dependency, of course.
2. Using `all-the-icons` here: `all-the-icons` doesn't have any icon formatter for completion; `all-the-icons-completions` does have an `:affixation-function` (rather, an advice on `completion-metadata-get` that adds one) for icons, but it seems to not recognize programming language kinds, only things like file, buffer, language etc. We would need to write and maintain our own, which would trade the extra dependency for code burden. That could start with refactoring the icon mapping in the `company` module out and implementing a function to apply it to `corfu`.

However, since both are likely out-of-scope and reasonably big, breaking changes, I will not act on either here, unless deemed necessary. I can provide a partial implementation of these in a separate branch if required, though.

2023-07-30 20:24 UTC, LuigiPiucco commented
Yasnippet integration was rebased out and moved to a [separate repository](https://github.com/LuigiPiucco/yasnippet-capf). Currently, it has a custom recipe for pulling from GitHub, but hopefully I can get it on an archive sometime soon. Other than this, the only thing I can think to modify here is adding eshell completion, but that can wait. I'll re-request reviews, I think it's somewhat ready.

2023-07-30 20:25 UTC, LuigiPiucco commented on modules/completion/corfu/+yas-capf.el
> +;;; Capf for yasnippet. Inspired by @elken's yas-capf.
And now it's been extracted as a package. I think this can be marked resolved.

2023-07-30 20:37 UTC, elken commented
Is there anything wrong with the package I had already written?

2023-07-30 21:03 UTC, LuigiPiucco commented
No, there's not. I suppose I got too greedy when writing this. It's all I've done these past few days, after all. Not using your package was me being bad, not your code. I'm sorry if I offended you by not using it. I can rebase the code to use yours if that would be better.

2023-07-30 21:05 UTC, elken commented
> No, there's not. I suppose I got too greedy when writing this. It's all I've done these past few days, after all. Not using your package was me being bad, not your code. I'm sorry if I offended you by not using it. I can rebase the code to use yours if that would be better.

No offense, just curious why :stuck_out_tongue:

2023-07-30 21:11 UTC, LuigiPiucco commented
Okay then. I'm happy I didn't do that bad. If you want to know some of my thoughts while reading the code, I saw that you pull in all templates multiple times, which seems like an expensive operation. I tried to optimize that, and ended up writing a whole lot.

2023-08-02 06:53 UTC, LemonBreezes commented
You should remove all the `:desc` arguments of `map!` because you never actually see those hints since the keys are not prefixed and they crowd the `which-key-replacement-alist` which has negative performance implications and they add an extra `(after! which-key ... )` block that increases load time.

2023-08-11 18:51 UTC, ispringle commented on modules/completion/corfu/config.el
> +      (when (imagep image)
I believe that `imagep` is new to Emacs 29. This is the [commit it was added in](https://github.com/emacs-mirror/emacs/commit/8557ecca5363e9b99371d2a3459da654d4d32fc1#diff-c83f9f6de8c37e67607edd5ba02ac01f6557471d75d8e12cbfaddb7f997a2451) and I've verified this won't run on Emacs 28 (but it does work well for me when I'm on Emacs 29!). Not sure if this is a big deal or not, but since Doom docs and Doom doctor still insist that Emacs 29 is unstable and shouldn't be used, might be good to provide a fallback for earlier version or find an alternative?

2023-08-14 16:05 UTC, LuigiPiucco commented on modules/completion/corfu/config.el
> +      (when (imagep image)
You are correct, but this may raise a problem: I need to check if the value of display for the text is, in fact, an image, or the fallback text. Do you know if testing whether the `car` is `'image` or not works, or some other way?

I searched for image-related functions at the time, but that was the only type predicate I could find. It's written in C too, which I assume means there is some issue with doing it via elisp.

2023-08-15 18:55 UTC, LemonBreezes commented
Hey, this seems like a new addition to `cape` but maybe we should also add `cape-elisp-block` too:
```
(add-hook! (org-mode markdown-mode)
  (add-to-list 'completion-at-point-functions #'cape-elisp-block))
```

2023-08-17 20:11 UTC, zhenwu0728 commented
I've been testing this module for a while but after a recent update to the latest commit, I got an error every time I open emacs. 
`(void-function evil-collection-define-key)`

Then I ran `emacs --debug-init` and got the following:
```
Debugger entered--Lisp error: (void-function evil-collection-define-key)
  (evil-collection-define-key 'insert 'corfu-map (kbd "RET") #'corfu-insert [return] #'corfu-insert)
  (progn (evil-collection-define-key 'insert 'corfu-map (kbd "RET") #'corfu-insert [return] #'corfu-insert))
  (if t (progn (evil-collection-define-key 'insert 'corfu-map (kbd "RET") #'corfu-insert [return] #'corfu-insert)))
  (progn (use-package-statistics-gather :config 'corfu nil) (add-to-list 'completion-styles 'partial-completion t) (add-to-list 'completion-styles 'initials t) (progn (setq corfu-cycle t) (setq corfu-separator (if t (progn 32))) (setq corfu-preselect t) (setq corfu-count 16) (setq corfu-max-width 120) (setq corfu-preview-current 'insert) (setq corfu-on-exact-match nil) (setq corfu-quit-at-boundary (if t 'separator t)) (setq corfu-quit-no-match (if t 'separator t)) (setq tab-always-indent (if nil 'complete tab-always-indent))) (if t (progn (cond (nil (add-to-list 'completion-category-overrides '(eglot ...))) (t (add-hook 'lsp-completion-mode-hook (defalias 'doom--use-orderless-lsp-capf #'...)))))) (progn (if nil nil (general-define-key "C-SPC" #'completion-at-point)) (progn (if t (progn (general-define-key :keymaps ''corfu-map "C-SPC" #'corfu-insert-separator))) (if nil (progn (general-define-key :keymaps ''corfu-map [tab] #'corfu-next [backtab] #'corfu-previous "TAB" #'corfu-next "S-TAB" #'corfu-previous))))) (if t (progn (evil-collection-define-key 'insert 'corfu-map (kbd "RET") #'corfu-insert [return] #'corfu-insert))) (progn (eval-after-load 'vertico #'(lambda nil (defalias 'corfu-move-to-minibuffer #'(lambda nil ... ...)) (progn (general-define-key :keymaps '... "s-<down>" #'corfu-move-to-minibuffer) (if t (progn ...)))))) t (use-package-statistics-gather :config 'corfu t))
  (closure (t) nil (progn (use-package-statistics-gather :config 'corfu nil) (add-to-list 'completion-styles 'partial-completion t) (add-to-list 'completion-styles 'initials t) (progn (setq corfu-cycle t) (setq corfu-separator (if t (progn 32))) (setq corfu-preselect t) (setq corfu-count 16) (setq corfu-max-width 120) (setq corfu-preview-current 'insert) (setq corfu-on-exact-match nil) (setq corfu-quit-at-boundary (if t 'separator t)) (setq corfu-quit-no-match (if t 'separator t)) (setq tab-always-indent (if nil 'complete tab-always-indent))) (if t (progn (cond (nil (add-to-list 'completion-category-overrides '...)) (t (add-hook 'lsp-completion-mode-hook (defalias ... ...)))))) (progn (if nil nil (general-define-key "C-SPC" #'completion-at-point)) (progn (if t (progn (general-define-key :keymaps '... "C-SPC" #'corfu-insert-separator))) (if nil (progn (general-define-key :keymaps '... [tab] #'corfu-next [backtab] #'corfu-previous "TAB" #'corfu-next "S-TAB" #'corfu-previous))))) (if t (progn (evil-collection-define-key 'insert 'corfu-map (kbd "RET") #'corfu-insert [return] #'corfu-insert))) (progn (eval-after-load 'vertico #'(lambda nil (defalias 'corfu-move-to-minibuffer #'...) (progn (general-define-key :keymaps ... "s-<down>" ...) (if t ...))))) t (use-package-statistics-gather :config 'corfu t)))()
  eval-after-load-helper("~/.config/emacs/.local/straight/build-29.1/corfu/corfu.elc")
  do-after-load-evaluation("~/.config/emacs/.local/straight/build-29.1/corfu/corfu.elc")
  require(corfu nil nil)
  load-with-code-conversion("~/.config/doom/config.el" "~/.config/doom/config.el" nil t)
  load("~/.config/doom/config" nil nomessage)
  (condition-case e (load path noerror 'nomessage) ((debug doom-error) (signal (car e) (cdr e))) ((debug error) (setq path (locate-file path load-path (get-load-suffixes))) (signal (cond ((not (and path (featurep ...))) 'error) ((file-in-directory-p path (expand-file-name "cli" doom-core-dir)) 'doom-cli-error) ((file-in-directory-p path doom-core-dir) 'doom-core-error) ((file-in-directory-p path doom-user-dir) 'doom-user-error) ((file-in-directory-p path doom-profile-dir) 'doom-profile-error) ((file-in-directory-p path doom-modules-dir) 'doom-module-error) ('doom-error)) (list path e))))
  doom-load("~/.config/doom/config")
  byte-code("\305\306!\204\f\0\305\307!\203\347\1\10\30\310\311!\211\203\"\0\211@\312\1!\210\1A\266\202\202\21\0\210\313\21\314\22\315\316\317\"\210\315\320\321\"\210\315..." [doom-context doom-modules doom-disabled-packages custom-file doom-module-context doom-context-p init reload ensure-list modules doom-context-push #<hash-table equal 37/65 0x1ff520e6944d> nil setplist :core (nil [0 -110 -110 :core nil nil nil]) :user (nil [1 105 -105 :user nil nil nil]) :completion (vertico [3 0 0 :completion vertico nil nil] corfu [4 0 0 :completion corfu (+icons +orderless) nil]) :ui (doom [5 0 0 :ui doom nil nil] doom-dashboard [6 0 0 :ui doom-dashboard nil nil] hl-todo [7 0 0 :ui hl-todo nil nil] modeline [8 0 0 :ui modeline nil nil] popup [9 0 0 :ui popup (+defaults) nil] vc-gutter [10 0 0 :ui vc-gutter (+pretty) nil] vi-tilde-fringe [11 0 0 :ui vi-tilde-fringe nil nil]) :editor (evil [12 0 0 :editor evil (+everywhere) nil] multiple-cursors [13 0 0 :editor multiple-cursors nil nil] snippets [14 0 0 :editor snippets nil nil]) :emacs (dired [15 0 0 :emacs dired nil nil] electric [16 0 0 :emacs electric nil nil] ibuffer [17 0 0 :emacs ibuffer nil nil] undo [18 0 0 :emacs undo nil nil] vc [19 0 0 :emacs vc nil nil]) :term (vterm [20 0 0 :term vterm nil nil]) :checkers (grammar [21 0 0 :checkers grammar nil nil]) :tools (biblio [22 0 0 :tools biblio nil nil] eval [23 0 0 :tools eval (+overlay) nil] lookup [24 0 0 :tools lookup (+dictionary) nil] lsp [25 0 0 :tools lsp nil nil] magit [26 0 0 :tools magit nil nil] pdf [27 0 0 :tools pdf nil nil] tree-sitter [28 0 0 :tools tree-sitter nil nil]) :os (macos [29 0 0 :os macos nil nil]) :lang (emacs-lisp [30 0 0 :lang emacs-lisp nil nil] julia [31 0 0 :lang julia (+lsp +tree-sitter +snail) nil] latex [32 0 0 :lang latex (+cdlatex +fold +latexmk +lsp) nil] markdown [33 0 0 :lang markdown nil nil] org [34 0 0 :lang org (+noter +dragndrop +beamer +roam2 +jupyter) nil]) :config (use-package [2 -111 -111 :config use-package nil nil] literate [35 0 0 :config literate nil nil] default [36 0 0 :config default (+bindings +smartparens) nil]) [2 -111 -111 :config use-package nil nil] doom-load "~/.config/emacs/modules/config/use-package/init" [0 -110 -110 :core nil nil nil] "~/.config/emacs/lisp/init" doom-run-hooks doom-before-modules-init-hook [12 0 0 :editor evil (+everywhere) nil] "~/.config/emacs/modules/editor/evil/init" doom-after-modules-init-hook doom-before-modules-config-hook [3 0 0 :completion vertico nil nil] ...] 4)
  load("~/.config/emacs/.local/etc/@/init.29.elc" noerror nomessage nosuffix)
  (progn (load init-file-name 'noerror 'nomessage 'nosuffix))
  (if init-file-name (progn (load init-file-name 'noerror 'nomessage 'nosuffix)))
  (let ((init-file-name (file-name-concat doom-profile-dir (format "init.%d.elc" emacs-major-version)))) (setq user-init-file t) (if init-file-name (progn (load init-file-name 'noerror 'nomessage 'nosuffix))) (if (eq user-init-file t) (progn (signal 'doom-nosync-error (list init-file-name)))) (setq user-init-file (concat (string-remove-suffix ".elc" user-init-file) ".el")))
  (progn (let ((init-file-name (file-name-concat doom-profile-dir (format "init.%d.elc" emacs-major-version)))) (setq user-init-file t) (if init-file-name (progn (load init-file-name 'noerror 'nomessage 'nosuffix))) (if (eq user-init-file t) (progn (signal 'doom-nosync-error (list init-file-name)))) (setq user-init-file (concat (string-remove-suffix ".elc" user-init-file) ".el"))))
  (if init-file-user (progn (let ((init-file-name (file-name-concat doom-profile-dir (format "init.%d.elc" emacs-major-version)))) (setq user-init-file t) (if init-file-name (progn (load init-fil [...]

2023-08-18 16:42 UTC, ispringle commented on modules/completion/corfu/config.el
> +      (when (imagep image)
I'm not aware of any, I looked a bit before commenting and could not find anything to detect if a thing is an image or not. What happens if you just let it pass? Like in Emacs 29 do the above and then if it's a version less than 29, can you just assume it's an image, the result would be a maybe badly colored face right?

2023-08-21 19:11 UTC, ispringle commented on modules/completion/corfu/packages.el
> +  (package! yasnippet-capf :recipe (:repo "https://github.com/LuigiPiucco/yasnippet-capf.git") :pin "c169e6724f0b7a594d985aa8da822bf7bcd2e2f9"))
Will this be updated to @elken's package which is now on MELPA?

2023-08-22 03:53 UTC, LemonBreezes commented
We should add Vim omni-completion keybindings for Corfu. Here are the docs: https://vimdoc.sourceforge.net/htmldoc/insert.html#ins-completion. I think Hlissner should write these though since he is very familiar with Vim.

2023-08-22 03:55 UTC, LemonBreezes commented
We should add Vim omni-completion keybindings for Corfu. Here are the docs: [vimdoc.sourceforge.net/htmldoc/insert.html#ins-completion](https://vimdoc.sourceforge.net/htmldoc/insert.html#ins-completion). I think maybe @hlissner  should write these though since he is very familiar with Vim. I personally don't have the "Vim taste" to write them.

2023-08-23 20:37 UTC, LuigiPiucco commented on modules/completion/corfu/packages.el
> +  (package! yasnippet-capf :recipe (:repo "https://github.com/LuigiPiucco/yasnippet-capf.git") :pin "c169e6724f0b7a594d985aa8da822bf7bcd2e2f9"))
Yes, I'm working on that right now. Once it's pushed, do note I had to delete `$EMACSDIR/.local/straight/build-$VERSION-cache.el` manually for `doom sync` to work. So if you encounter an error saying the package does not exist, do that. Sadly, it'll cause a long rebuild...

2023-08-23 20:38 UTC, elken commented on modules/completion/corfu/packages.el
> +  (package! yasnippet-capf :recipe (:repo "https://github.com/LuigiPiucco/yasnippet-capf.git") :pin "c169e6724f0b7a594d985aa8da822bf7bcd2e2f9"))
`doom sync -u` when a recipe changes

2023-08-23 20:42 UTC, LuigiPiucco commented
> I've been testing this module for a while but after a recent update to the latest commit, I got an error every time I open emacs. `(void-function evil-collection-define-key)`
> 
> Then I ran `emacs --debug-init` and got the following:
> 
> ```
> Debugger entered--Lisp error: (void-function evil-collection-define-key)
>   (evil-collection-define-key 'insert 'corfu-map (kbd "RET") #'corfu-insert [return] #'corfu-insert)
>   (progn (evil-collection-define-key 'insert 'corfu-map (kbd "RET") #'corfu-insert [return] #'corfu-insert))
>   (if t (progn (evil-collection-define-key 'insert 'corfu-map (kbd "RET") #'corfu-insert [return] #'corfu-insert)))
>   (progn (use-package-statistics-gather :config 'corfu nil) (add-to-list 'completion-styles 'partial-completion t) (add-to-list 'completion-styles 'initials t) (progn (setq corfu-cycle t) (setq corfu-separator (if t (progn 32))) (setq corfu-preselect t) (setq corfu-count 16) (setq corfu-max-width 120) (setq corfu-preview-current 'insert) (setq corfu-on-exact-match nil) (setq corfu-quit-at-boundary (if t 'separator t)) (setq corfu-quit-no-match (if t 'separator t)) (setq tab-always-indent (if nil 'complete tab-always-indent))) (if t (progn (cond (nil (add-to-list 'completion-category-overrides '(eglot ...))) (t (add-hook 'lsp-completion-mode-hook (defalias 'doom--use-orderless-lsp-capf #'...)))))) (progn (if nil nil (general-define-key "C-SPC" #'completion-at-point)) (progn (if t (progn (general-define-key :keymaps ''corfu-map "C-SPC" #'corfu-insert-separator))) (if nil (progn (general-define-key :keymaps ''corfu-map [tab] #'corfu-next [backtab] #'corfu-previous "TAB" #'corfu-next "S-TAB" #'corfu-previous))))) (if t (progn (evil-collection-define-key 'insert 'corfu-map (kbd "RET") #'corfu-insert [return] #'corfu-insert))) (progn (eval-after-load 'vertico #'(lambda nil (defalias 'corfu-move-to-minibuffer #'(lambda nil ... ...)) (progn (general-define-key :keymaps '... "s-<down>" #'corfu-move-to-minibuffer) (if t (progn ...)))))) t (use-package-statistics-gather :config 'corfu t))
>   (closure (t) nil (progn (use-package-statistics-gather :config 'corfu nil) (add-to-list 'completion-styles 'partial-completion t) (add-to-list 'completion-styles 'initials t) (progn (setq corfu-cycle t) (setq corfu-separator (if t (progn 32))) (setq corfu-preselect t) (setq corfu-count 16) (setq corfu-max-width 120) (setq corfu-preview-current 'insert) (setq corfu-on-exact-match nil) (setq corfu-quit-at-boundary (if t 'separator t)) (setq corfu-quit-no-match (if t 'separator t)) (setq tab-always-indent (if nil 'complete tab-always-indent))) (if t (progn (cond (nil (add-to-list 'completion-category-overrides '...)) (t (add-hook 'lsp-completion-mode-hook (defalias ... ...)))))) (progn (if nil nil (general-define-key "C-SPC" #'completion-at-point)) (progn (if t (progn (general-define-key :keymaps '... "C-SPC" #'corfu-insert-separator))) (if nil (progn (general-define-key :keymaps '... [tab] #'corfu-next [backtab] #'corfu-previous "TAB" #'corfu-next "S-TAB" #'corfu-previous))))) (if t (progn (evil-collection-define-key 'insert 'corfu-map (kbd "RET") #'corfu-insert [return] #'corfu-insert))) (progn (eval-after-load 'vertico #'(lambda nil (defalias 'corfu-move-to-minibuffer #'...) (progn (general-define-key :keymaps ... "s-<down>" ...) (if t ...))))) t (use-package-statistics-gather :config 'corfu t)))()
>   eval-after-load-helper("~/.config/emacs/.local/straight/build-29.1/corfu/corfu.elc")
>   do-after-load-evaluation("~/.config/emacs/.local/straight/build-29.1/corfu/corfu.elc")
>   require(corfu nil nil)
>   load-with-code-conversion("~/.config/doom/config.el" "~/.config/doom/config.el" nil t)
>   load("~/.config/doom/config" nil nomessage)
>   (condition-case e (load path noerror 'nomessage) ((debug doom-error) (signal (car e) (cdr e))) ((debug error) (setq path (locate-file path load-path (get-load-suffixes))) (signal (cond ((not (and path (featurep ...))) 'error) ((file-in-directory-p path (expand-file-name "cli" doom-core-dir)) 'doom-cli-error) ((file-in-directory-p path doom-core-dir) 'doom-core-error) ((file-in-directory-p path doom-user-dir) 'doom-user-error) ((file-in-directory-p path doom-profile-dir) 'doom-profile-error) ((file-in-directory-p path doom-modules-dir) 'doom-module-error) ('doom-error)) (list path e))))
>   doom-load("~/.config/doom/config")
>   byte-code("\305\306!\204\f\0\305\307!\203\347\1\10\30\310\311!\211\203\"\0\211@\312\1!\210\1A\266\202\202\21\0\210\313\21\314\22\315\316\317\"\210\315\320\321\"\210\315..." [doom-context doom-modules doom-disabled-packages custom-file doom-module-context doom-context-p init reload ensure-list modules doom-context-push #<hash-table equal 37/65 0x1ff520e6944d> nil setplist :core (nil [0 -110 -110 :core nil nil nil]) :user (nil [1 105 -105 :user nil nil nil]) :completion (vertico [3 0 0 :completion vertico nil nil] corfu [4 0 0 :completion corfu (+icons +orderless) nil]) :ui (doom [5 0 0 :ui doom nil nil] doom-dashboard [6 0 0 :ui doom-dashboard nil nil] hl-todo [7 0 0 :ui hl-todo nil nil] modeline [8 0 0 :ui modeline nil nil] popup [9 0 0 :ui popup (+defaults) nil] vc-gutter [10 0 0 :ui vc-gutter (+pretty) nil] vi-tilde-fringe [11 0 0 :ui vi-tilde-fringe nil nil]) :editor (evil [12 0 0 :editor evil (+everywhere) nil] multiple-cursors [13 0 0 :editor multiple-cursors nil nil] snippets [14 0 0 :editor snippets nil nil]) :emacs (dired [15 0 0 :emacs dired nil nil] electric [16 0 0 :emacs electric nil nil] ibuffer [17 0 0 :emacs ibuffer nil nil] undo [18 0 0 :emacs undo nil nil] vc [19 0 0 :emacs vc nil nil]) :term (vterm [20 0 0 :term vterm nil nil]) :checkers (grammar [21 0 0 :checkers grammar nil nil]) :tools (biblio [22 0 0 :tools biblio nil nil] eval [23 0 0 :tools eval (+overlay) nil] lookup [24 0 0 :tools lookup (+dictionary) nil] lsp [25 0 0 :tools lsp nil nil] magit [26 0 0 :tools magit nil nil] pdf [27 0 0 :tools pdf nil nil] tree-sitter [28 0 0 :tools tree-sitter nil nil]) :os (macos [29 0 0 :os macos nil nil]) :lang (emacs-lisp [30 0 0 :lang emacs-lisp nil nil] julia [31 0 0 :lang julia (+lsp +tree-sitter +snail) nil] latex [32 0 0 :lang latex (+cdlatex +fold +latexmk +lsp) nil] markdown [33 0 0 :lang markdown nil nil] org [34 0 0 :lang org (+noter +dragndrop +beamer +roam2 +jupyter) nil]) :config (use-package [2 -111 -111 :config use-package nil nil] literate [35 0 0 :config literate nil nil] default [36 0 0 :config default (+bindings +smartparens) nil]) [2 -111 -111 :config use-package nil nil] doom-load "~/.config/emacs/modules/config/use-package/init" [0 -110 -110 :core nil nil nil] "~/.config/emacs/lisp/init" doom-run-hooks doom-before-modules-init-hook [12 0 0 :editor evil (+everywhere) nil] "~/.config/emacs/modules/editor/evil/init" doom-after-modules-init-hook doom-before-modules-config-hook [3 0 0 :completion vertico nil nil] ...] 4)
>   load("~/.config/emacs/.local/etc/@/init.29.elc" noerror nomessage nosuffix)
>   (progn (load init-file-name 'noerror 'nomessage 'nosuffix))
>   (if init-file-name (progn (load init-file-name 'noerror 'nomessage 'nosuffix)))
>   (let ((init-file-name (file-name-concat doom-profile-dir (format "init.%d.elc" emacs-major-version)))) (setq user-init-file t) (if init-file-name (progn (load init-file-name 'noerror 'nomessage 'nosuffix))) (if (eq user-init-file t) (progn (signal 'doom-nosync-error (list init-file-name)))) (setq user-init-file (concat (string-remove-suffix ".elc" user-init-file) ".el")))
>   (progn (let ((init-file-name (file-name-concat doom-profile-dir (format "init.%d.elc" emacs-major-version)))) (setq user-init-file t) (if init-file-name (progn (load init-file-name 'noerror 'nomessage 'nosuffix))) (if (eq user-init-file t) (progn (signal 'doom-nosync-error (list init-file-name)))) (setq user-init-file (concat (string-remove-suffix ".elc" user-init-file) ".el"))))
>   (if init-file-user (progn (let ((init-file-name (file-name-concat doom-profile-dir (format "init.%d.elc" emacs-major-version)))) (setq user-ini [...]

2023-08-23 20:56 UTC, LuigiPiucco commented on modules/completion/corfu/config.el
> +      (when (imagep image)
It seems testing for the `car` to be `'image` works. I'll push that along with the other alterations, Soon™.

2023-08-23 21:24 UTC, LuigiPiucco commented on modules/completion/corfu/packages.el
> +  (package! yasnippet-capf :recipe (:repo "https://github.com/LuigiPiucco/yasnippet-capf.git") :pin "c169e6724f0b7a594d985aa8da822bf7bcd2e2f9"))
`doom sync -u` and `doom build` failed as well for me.

2023-08-24 02:23 UTC, zhenwu0728 commented
> > @zhenwu0728 Do you perhaps not use evil? I ask to confirm my suspicion that it's because that is missing. In any case, this is a bug. I'll fix it once I confirm the reason.
> 
> Thanks for your response @LuigiPiucco - I use evil.
> 
> > Edit: Nevermind. I just checked, the code only calls evil-collection-define-key if the evil module is enabled. So this could be problem with the bytecode, in which case doom build should fix it; or something else.
> 
> I'll try that and let you know if that works

@LuigiPiucco after I ran `doom build` the error still exists.

2023-08-24 02:28 UTC, LemonBreezes commented
> > > @zhenwu0728 Do you perhaps not use evil? I ask to confirm my suspicion that it's because that is missing. In any case, this is a bug. I'll fix it once I confirm the reason.
> > 
> > Thanks for your response @LuigiPiucco - I use evil.
> > 
> > > Edit: Nevermind. I just checked, the code only calls evil-collection-define-key if the evil module is enabled. So this could be problem with the bytecode, in which case doom build should fix it; or something else.
> > 
> > I'll try that and let you know if that works
> 
> @LuigiPiucco after I ran `doom build` the error still exists.

Try deleting the straight folder and running `doom sync` again. I don't think this is related to the Corfu module.

2023-08-24 02:56 UTC, zhenwu0728 commented
> Try deleting the straight folder and running `doom sync` again. By the way, you shouldn't have your Doom modules compiled yet. It's not officially supported. I don't think that issue is related to the Corfu module itself. It sounds like some bad bytecode file is being loaded somewhere.

Thanks for your reply @LemonBreezes! I removed the whole `~/.config/emacs/.local` folder and ran `doom sync`, but the error still exists. 

However, after I commented out the following lines in `modules/completion/corfu/config.el`, the error goes away.
```
(when (modulep! :editor evil)
    (evil-collection-define-key 'insert 'corfu-map
      (kbd "RET") #'corfu-insert
      [return] #'corfu-insert))
```

2023-08-24 02:57 UTC, LemonBreezes commented
> > Try deleting the straight folder and running `doom sync` again. By the way, you shouldn't have your Doom modules compiled yet. It's not officially supported. I don't think that issue is related to the Corfu module itself. It sounds like some bad bytecode file is being loaded somewhere.
> 
> Thanks for your reply @LemonBreezes! I removed the whole `~/.config/emacs/.local` folder and ran `doom sync`, but the error still exists. 
> 
> However, after I commented out the following lines in `modules/completion/corfu/config.el`, the error goes away.
> ```
> (when (modulep! :editor evil)
>     (evil-collection-define-key 'insert 'corfu-map
>       (kbd "RET") #'corfu-insert
>       [return] #'corfu-insert))
> ```

Oh wait!! Do you have Evil enabled but not +everywhere?

2023-08-24 02:59 UTC, zhenwu0728 commented
> > > Try deleting the straight folder and running `doom sync` again. By the way, you shouldn't have your Doom modules compiled yet. It's not officially supported. I don't think that issue is related to the Corfu module itself. It sounds like some bad bytecode file is being loaded somewhere.
> > 
> > 
> > Thanks for your reply @LemonBreezes! I removed the whole `~/.config/emacs/.local` folder and ran `doom sync`, but the error still exists.
> > However, after I commented out the following lines in `modules/completion/corfu/config.el`, the error goes away.
> > ```
> > (when (modulep! :editor evil)
> >     (evil-collection-define-key 'insert 'corfu-map
> >       (kbd "RET") #'corfu-insert
> >       [return] #'corfu-insert))
> > ```
> 
> Oh wait!! Do you have Evil enabled but not +everywhere?

I have `(evil +everywhere)` enabled

2023-08-24 03:00 UTC, LemonBreezes commented
Then `evil-define-key` should be autoloaded. Is it not? Try describe function.

2023-08-24 03:09 UTC, zhenwu0728 commented
> Then `evil-collection-define-key` should be autoloaded. Is it not? Try describe function.

What should I expect to see?
<img width="1680" alt="Screenshot 2023-08-23 at 11 09 44 PM" src="https://github.com/doomemacs/doomemacs/assets/46291075/1abfcae3-3a2a-49f4-aa6b-5c1692baebdf">

2023-08-24 03:24 UTC, LemonBreezes commented
> > Then `evil-collection-define-key` should be autoloaded. Is it not? Try describe function.
> 
> What should I expect to see?
> <img width="1680" alt="Screenshot 2023-08-23 at 11 09 44 PM" src="https://github.com/doomemacs/doomemacs/assets/46291075/1abfcae3-3a2a-49f4-aa6b-5c1692baebdf">
> 

I mean if you go to the function definition, it should have an autoload cookie the line above. It should also say it in the describe-function page for the function.

2023-08-24 03:35 UTC, zhenwu0728 commented
> I mean if you go to the function definition, it should have an autoload cookie the line above. It should also say it in the describe-function page for the function.

That's what I saw in the describe-function page. 
Sorry I'm slow - I just started to use emacs a few months ago.

<img width="1680" alt="Screenshot 2023-08-23 at 11 33 23 PM" src="https://github.com/doomemacs/doomemacs/assets/46291075/87bf2b4c-05f0-4a10-b09e-41d3e0e2d114">

2023-08-24 03:53 UTC, LemonBreezes commented
> > I mean if you go to the function definition, it should have an autoload cookie the line above. It should also say it in the describe-function page for the function.
> 
> That's what I saw in the describe-function page. Sorry I'm slow - I just started to use emacs a few months ago.
> 
> <img alt="Screenshot 2023-08-23 at 11 33 23 PM" width="1680" src="https://user-images.githubusercontent.com/46291075/262852909-87bf2b4c-05f0-4a10-b09e-41d3e0e2d114.png">

No worries. I just got to my computer. I think that it's possible we are not getting the error because we are loading `evil-collection` early through some other module. The correct solution, I believe is to wrap that keybinding with:
```
(after! evil-collection-corfu ...)
```

2023-08-24 03:59 UTC, zhenwu0728 commented
> No worries. I just got to my computer. I think that it's possible we are not getting the error because we are loading `evil-collection` early through some other configuration. The correct solution is to wrap that keybinding with:
> 
> ```
> (after! evil-collection-corfu ...)
> ```
This works!
in `modules/completion/corfu/config.el` I change the code to:
```
  (after! evil-collection-corfu
    (when (modulep! :editor evil)
      (evil-collection-define-key 'insert 'corfu-map
        (kbd "RET") #'corfu-insert
        [return] #'corfu-insert)))
```

2023-08-26 17:56 UTC, snyball commented
@LuigiPiucco The combo of corfu/lsp-capf occasionally causes emacs to freeze at 100% CPU utlilization, the fix is https://github.com/minad/corfu/issues/227#issuecomment-1236373720:

```emacs-lisp
(advice-add #'lsp-completion-at-point :around #'cape-wrap-noninterruptible)
```

There's also a problem with how the vertico module configures orderless. With vertico disabled and `(corfu +orderless)` I can do fuzzy matching, where something like `abcdef` will match function `abc_def` like I would expect, but with vertico enabled the completion stops abruptly at `abcd`.

2023-09-04 23:46 UTC, LuigiPiucco commented
I've applied the latest fixes as commits, except for the orderless issue. The reason for that is because this module enables the `partial-completion` style, which allow a contiguous input like `abcd` to be broken apart and match **abc**_**d**ef. However, the vertico modules does not, and it uses `setq` to configure orderless, so if it loads later (the common case) the value gets overriden. I could make sure `partial-completion` is not overriden, but since it isn't used in vertico, I wonder if I should instead remove it to match the other module by default and place it behind a flag. What do you think?

2023-09-05 05:25 UTC, asymmetric commented
Is there a way to enable `partial-completion`  only for corfu invocations of orderless?

2023-09-12 14:50 UTC, elken commented
As of #7411, we'll be moving to nerd-icons which has a [copyable config for kind-icon](https://github.com/rainstormstudio/nerd-icons.el#use-nerd-icons-with-corfu). Suggest also disabling `svg-lib` if it's being pulled by straight, since we won't be using it then

2023-09-18 15:36 UTC, LuigiPiucco commented
I pushed a new version [here](https://github.com/LuigiPiucco/doom-emacs/tree/corfu-rewrite), a rewrite really. Since changes were pretty big (from 32 to 3 commits), I'll leave it there for 1 or 2 days so that people interested can check if it breaks things. What was done:
- Commits correcting mistakes and failed attempts were squashed, to make the history cleaner;
- Rebased to latest;
- The kind-icon + svg-lib combo was replaced by nerd-icons, with a [simple margin-formatter](https://github.com/LuigiPiucco/doom-emacs/commit/69375800be5eebb95b610f6c62863c038181d281#diff-55fc837446c1f77710c8d35ba9c0a9ff1f8e2c3f3be5e2cc4477385107cb3038R95-R112). It reads from `+corfu-icon-mapping`, which contains the [same mapping suggested by nerd-icons for kind-icon](https://github.com/rainstormstudio/nerd-icons.el#use-nerd-icons-with-corfu). This saves us some dependencies, and removes the need for the scaling fixes from before.
- The value of `completion-styles` used for corfu was separated from the global state [here](https://github.com/LuigiPiucco/doom-emacs/commit/69375800be5eebb95b610f6c62863c038181d281#diff-55fc837446c1f77710c8d35ba9c0a9ff1f8e2c3f3be5e2cc4477385107cb3038R114-R128). It gets replaced locally with `+corfu-completion-styles`, which the user can set. An extra default style of `flex` was added instead of `partial-completion`, since that seemed to work better, but it's configurable. `orderless` is added as well if `+orderless`, no need to put it here.

I ask that people who've been following this thread check it out and comment if it's okay or broken before I force push it to here.

2023-09-18 16:57 UTC, Roger-Roger-debug commented
I just quickly checked out your branch and tried to edit some text. I configured the module like this
```elisp
       (corfu +icons)

```
and did a `doom sync -u` afterwards. Upon trying to edit I'm getting the following errors

```
Error running timer ‘corfu--auto-complete-deferred’: (void-variable corfu-icon-mapping)
Error running timer ‘corfu--auto-complete-deferred’: (void-variable corfu-icon-mapping)
Error in post-command-hook (corfu--post-command): (void-variable corfu-icon-mapping)
```

When opening documentation for the variable it does have a value though.

2023-09-18 20:43 UTC, maikol-solis commented
I have the same issue with. The problem is in this line where it should be `+corfu-icon-mapping` instead of `corfu-icon-mapping`

https://github.com/LuigiPiucco/doom-emacs/blob/e1b34be4912ebb61e740e8d481105f7bae5b222a/modules/completion/corfu/config.el#L103

2023-09-18 21:56 UTC, LuigiPiucco commented
A fix is pushed to the same branch. Thanks for checking it out.

2023-09-18 23:31 UTC, maikol-solis commented
Thanks for the fix. Now it works perfectly. 👍🏻

2023-09-19 20:37 UTC, maikol-solis commented
Perhaps in the README, you could add a guide on how to add new capes for some modes. I am not sure if the correct form is something like that. 
```elisp
(after! cape
  (add-hook! 'text-mode-hook
    (lambda ()
      (+corfu--add-capf! #'cape-dabbrev)
      (+corfu--add-capf! #'cape-abbrev)
      (+corfu--add-capf! #'cape-tex)
      (+corfu--add-capf! #'cape-dict)
      (+corfu--add-capf! #'cape-file))))
```

2023-09-19 21:12 UTC, LemonBreezes commented
> Perhaps in the README, you could add a guide on how to add new capes for some modes. I am not sure if the correct form is something like that.
> 
> ```emacs-lisp
> (after! cape
>   (add-hook! 'text-mode-hook
>     (lambda ()
>       (+corfu--add-capf! #'cape-dabbrev)
>       (+corfu--add-capf! #'cape-abbrev)
>       (+corfu--add-capf! #'cape-tex)
>       (+corfu--add-capf! #'cape-dict)
>       (+corfu--add-capf! #'cape-file))))
> ```

That works though you can even be more concise with something like
```
(add-hook! text-mode
  (add-to-list 'completion-at-point-functions #'cape-elisp-block))
```
But I recommend using a `defun` instead since if you ever want to change that function later, it's easier to redefine it or remove it from the hook.

2023-09-20 00:13 UTC, maikol-solis commented
> Though I also prefer just using the built-in `add-to-list` personally instead of `+corfu--add-capf!`.

Yes, the problem with this method is you can't hook the capes directly to some specific mode. Maybe this is not a big problem, though.

2023-09-20 00:22 UTC, LemonBreezes commented
> > Though I also prefer just using the built-in `add-to-list` personally instead of `+corfu--add-capf!`.
> 
> Yes, the problem with this method is you can't hook the capes directly to some specific mode. Maybe this is not a big problem, though.

No, I mean like
```
(add-hook! (org-mode markdown-mode)
  (add-to-list 'completion-at-point-functions #'cape-elisp-block))
```
I think `add-hook` is more appropriate but I use `add-to-list` because I'm more used to it.

2023-09-20 14:24 UTC, LuigiPiucco commented
I added a section in the README about adding CAPFs. Below is an explanation of how it works, though that's an optional read. Also, I'll be merging the branch into this pull request later today.

Adding a CAPF is done via hooks, to do it on a per-mode basis. As such, normally you'd use `add-hook`, as in:
```emacs-lisp
(add-hook 'some-mode-hook (lambda () (add-to-list 'completion-at-point-functions 'some-capf)))
```
It has no special handling for auto quoting the arguments or wrapping them in `lambda`, so it has to be as above. If, however, you use Doom's version `add-hook!`, that one has such handling and can be called in any of the following ways:
```emacs-lisp
(add-hook! 'some-mode-hook (lambda () (add-to-list 'completion-at-point-functions 'some-capf))) ; As add-hook
(add-hook! 'some-mode-hook (add-to-list 'completion-at-point-functions 'some-capf)) ; Wraps the forms in lambda automatically
(add-hook! some-mode (lambda () (add-to-list 'completion-at-point-functions 'some-capf))) ; Quotes and adds -hook to some-mode automatically
(add-hook! some-mode (add-to-list 'completion-at-point-functions 'some-capf)) ; Mix and match
(add-hook! '(1-mode-hook 2-mode-hook) (add-to-list 'completion-at-point-functions 'some-capf)
                                      (add-to-list 'completion-at-point-functions 'some-other-capf)) ; M forms/functions to N hooks
(add-hook! (1-mode 2-mode) (add-to-list 'completion-at-point-functions 'some-capf)
                           (add-to-list 'completion-at-point-functions 'some-other-capf)) ; With mode symbols instead of hook symbols
```

`(after! cape ...)`, though correct, is unneeded, since it loads very early, upon opening the first buffer. Also, `+corfu--add-capf!` was a macro that just expanded to `(add-to-list 'completion-at-point-functions ...)`, but it didn't help that much so I removed it.

Hope it helps!

2023-09-20 14:58 UTC, maikol-solis commented
Thanks for the explanation in the README. It's much clearer now.

2023-09-21 08:43 UTC, elken commented on modules/completion/corfu/config.el
> +          (:when (modulep! :editor evil) "s-j" #'corfu-move-to-minibuffer))))
The bigger issue is they _might_ be captured. Sometimes I've had Emacs take priority, sometimes the WM has taken priority. Agree binding to super is wrong.

`M-m` maybe for `minibuffer move`

2023-09-21 21:18 UTC, LuigiPiucco commented on modules/completion/corfu/config.el
> +          (:when (modulep! :editor evil) "s-j" #'corfu-move-to-minibuffer))))
I think `M-m` is good. I'll just wait on https://github.com/melpa/melpa/pull/8742 before pushing again, to extract the icons along with this fix.

2023-09-24 09:13 UTC, Roger-Roger-debug commented
Iirc that's the behavior for company as well. I have added `(add-hook! 'evil-insert-state-exit-hook #'corfu-quit)` to my config though because it makes it feel more natural (and matches the way my vim config works).

2023-09-24 20:22 UTC, LemonBreezes commented
The yasnippet-capf `use-package!` block should also be guarded by `:when (modulep! :editor snippets)`.

2023-10-02 16:29 UTC, LuigiPiucco commented
I updated with the suggestions and rebased. I also used @hpfr's commit about savehist, I hope that's OK.

> The yasnippet-capf `use-package!` block should also be guarded by `:when (modulep! :editor snippets)`.

Is this needed? `package.el` already has that check, the package won't even be installed if snippets are disabled, right?

2023-10-02 16:44 UTC, LemonBreezes commented
> I updated with the suggestions and rebased. I also used @hpfr's commit about savehist, I hope that's OK.
> 
> > The yasnippet-capf `use-package!` block should also be guarded by `:when (modulep! :editor snippets)`.
> 
> Is this needed? `package.el` already has that check, the package won't even be installed if snippets are disabled, right?

Yes because depending on the expansion of the use-package macro, this could lead to autoloading functions from files that do not exist or calling `require` on a package which is not in the load path. It's also possible that it does not lead to problems but adding `:when (modulep! :editor snippets)` is still smart IMO.

2023-10-02 17:08 UTC, LuigiPiucco commented
I did add the check, I was just curious if it was necessary. I thought `use-package!` wouldn't actually expand to any requires when lazy loading, just add handlers in case the package happens to be loaded, like `after!`.

2023-10-02 18:18 UTC, LemonBreezes commented
> I did add the check, I was just curious if it was necessary. I thought `use-package!` wouldn't actually expand to any requires when lazy loading, just add handlers in case the package happens to be loaded, like `after!`. 

Yeah, that basically depends on whether the package is deferred, how it is deferred, etc. I think that if it is deferred incrementally it will fail silently but if it's loaded by a command or a timer, it will signal an error.

2023-10-12 02:52 UTC, LemonBreezes commented
> In fact, because it is independent of Corfu, it might make more sense to move `yasnippet-capf` to `:editor snippets` and instead condition using `(not (modulep! :completion company))`.

I think we should keep the capf stuff with Corfu because it makes it easier to bisect problems with autocompletion. If we don't have an autocompletion module enabled, there should be no change to the autocompletion configuration.

2023-10-15 18:35 UTC, LuigiPiucco commented
I'm working on rebasing and using [nerd-icons-corfu](https://github.com/LuigiPiucco/nerd-icons-corfu) in this module, it will probably come later today.

### About `+corfu-completion-styles`

In https://github.com/LuigiPiucco/doom-emacs/commit/69375800be5eebb95b610f6c62863c038181d281#r127739389, the author of Corfu said having a separate value of `completion-styles` for just Corfu will cause problems and inconsistent behavior later on. I unfortunately forgot about it for a while, but now I'm getting back to it. I'd like to know other's opinion on this, and whether the behavior is useful. The main alternative is to ask the user to configure `completion-styles` directly, and use its global value. This will make all other completion front-ends (vertico, for instance) behave consistently, but also means it's harder to have one completion front-end be less strict in matching than the others.

I'm pinging @asymmetric and @snyball because they mentioned wanting it. To get fuzzy matching everywhere, add `flex` to `completion-styles` globally, that's what's done for Corfu locally. Is that good enough? If yes, I'll rebase the feature out, if not we can discuss what to do.

2023-10-15 22:21 UTC, LemonBreezes commented
So I've been looking at `yasnippet-capf` and I think it's problematic that it is prepended to `completion-at-point-functions`. In Elisp, for example, this means you get only the snippet completions when you type `co` and the Elisp completions show up only after typing `com`. To be honest, I think it's better to append it.

I think also I agree with the backend list here
![image](https://github.com/doomemacs/doomemacs/assets/29102529/e5f5f4dd-1018-4207-b72f-2f80859a7c0b)
in that we should enable `cape-dabbrev` for `conf-mode` and maybe make some other changes. I'll work on this later. I think that we will need to use `add-hook` with so many `completion-at-point-functions` to make sure that they get added in the correct order.

2023-10-16 07:16 UTC, LemonBreezes commented
https://0x0.st/H4CH.txt
This is what I have so far as a patch you can `git apply`. I just spent all night figuring out what `capfs` to enable, lol. This is all a bit opinionated but we can spend time discussing it here.

@LuigiPiucco  One hack that I like a lot and might be what you're looking for in the `+corfu-completion-styles` is this:

```
(defmacro cae-orderless-escapable-split-fn (char)
  `(defun cae-orderless-escapable-split-on-space-or-char (s)
     (mapcar
      (lambda (piece)
        (replace-regexp-in-string
         (string 1) ,(string char)
         (replace-regexp-in-string
          (concat (string 0) "\\|" (string 1))
          (lambda (x)
            (pcase x
              ("\0" " ")
              ("\1" ,(string char))
              (_ x)))
          piece
          ;; These are arguments to `replace-regexp-in-string'.
          'fixedcase 'literal)
         'fixedcase 'literal))
      (split-string (replace-regexp-in-string
                     (concat "\\\\\\\\\\|\\\\ \\|\\\\" ,(string char))
                     (lambda (x)
                       (pcase x
                         ("\\ " "\0")
                         (,(concat "\\" (string char)) "\1")
                         (_ x)))
                     s 'fixedcase 'literal)
                    ,(concat "[ " (string char) "]+") t))))

(when (modulep! :completion corfu +split-char)
  (after! orderless
    ;; Orderless splits the string into components and then determines the
    ;; matching style for each component. This is all regexp stuff.
    (progn (setq orderless-component-separator
                 (cae-orderless-escapable-split-fn ?,))
           (after! corfu
             (setq corfu-separator ?,)
             (map! :map corfu-map
                   "," #'corfu-insert-separator)))))
```
Now you can use the comma key to fuzzy-search completions with Corfu and that key is customizable.

2023-10-16 11:59 UTC, Roger-Roger-debug commented
> I think also I agree with the backend list here
> ![image](https://user-images.githubusercontent.com/29102529/275357455-e5f5f4dd-1018-4207-b72f-2f80859a7c0b.png)
> in that we should enable `cape-dabbrev` for `conf-mode` and maybe make some other changes. I'll work on this later. I think that we will need to use `add-hook` with so many `completion-at-point-functions` to make sure that they get added in the correct order.

Maybe that's just personal taste but I like having dabbrev in every buffer, helps me avoid subtle spelling mistakes and can save some time on long words.

2023-10-16 15:21 UTC, LemonBreezes commented
> > I think also I agree with the backend list here
> > ![image](https://user-images.githubusercontent.com/29102529/275357455-e5f5f4dd-1018-4207-b72f-2f80859a7c0b.png)
> > in that we should enable `cape-dabbrev` for `conf-mode` and maybe make some other changes. I'll work on this later. I think that we will need to use `add-hook` with so many `completion-at-point-functions` to make sure that they get added in the correct order.
> 
> Maybe that's just personal taste but I like having dabbrev in every buffer, helps me avoid subtle spelling mistakes and can save some time on long words.
> 
> 

(I'm gonna also PR the Corfu module today. The patch was to hopefully get a bit of feedback if anyone checked it out before the PR. The patch is a draft.)

But yeah, regarding `dabbrev`, I've enabled it in `conf-mode`, `text-mode`, and `comint-mode`. I'm unsure about enabling it in `prog-mode` or `eshell-mode` since it will almost never trigger there because other completion backends like LSP and Pcomplete would be active.

2023-10-16 23:43 UTC, LemonBreezes commented
Ok. I just made a PR here making lots of changes. https://github.com/LuigiPiucco/doom-emacs/pull/1

One thing I am still interested in adding is `fish-completion` & `pcmpl-args` support on a global level since `pcomplete` is used outside of `eshell` and `comint` buffers like say, when reading a shell command from the minibuffer.

2023-10-20 15:52 UTC, LemonBreezes commented
I'm also using these keybindings. They're a bit different from the old ones for Company but I don't like those because they override useful Emacs keybindings like `mark-page` and `set-goal-column`.
```elisp
  (defalias 'cae-cape-history-or-line
    (cape-interactive-capf (cape-capf-super #'cape-history #'cape-line)))
  (defalias 'cae-cape-keyword-or-dict
    (cape-interactive-capf (cape-capf-super #'cape-keyword #'cape-dict)))

(defun cae-cape-lsp ()
  (interactive)
  (cond ((and (modulep! :tools lsp)
              (not (modulep! :tools lsp +eglot)))
         (cape-interactive #'lsp-completion-at-point))
        (t (cape-interactive #'eglot-completion-at-point))))

(map! (:prefix "C-x"
       :i "C-c" #'copilot-complete
       :i "C-f" #'cape-file
       (:after cape
        :i "C-l" #'cae-cape-history-or-line
        :i "C-s" #'yasnippet-capf)
       :i "C-]" #'cae-cape-lsp
       (:after cape
        :i "C-r" #'cae-cape-keyword-or-dict)
       :i "s" #'cape-elisp-symbol
       :i "C-n" nil
       :i "C-p" nil))
```

2023-10-31 04:37 UTC, LemonBreezes commented
I'm looking at the current code. Some of these are minor mistakes on my part but:

1. If you want to just escape the space character, I recommend that you use `orderless-escapable-split-on-space` instead of writing a custom function. This is the function I based my own code on. This would resolve that TODO.
2. It says that `cape-interactive-capf` is obsolete so that should become `cape-capf-interactive` instead.
3. In this code,
```elisp
(setq cape-dabbrev-check-other-buffers t
     dabbrev-friend-buffer-function #'+dabbrev-friend-buffer-p
     dabbrev-ignored-buffer-regexps
     '("\\.\\(?:pdf\\|jpe?g\\|png\\|svg\\|eps\\)\\'"
       "^ \\*"
       "\\(TAGS\\|tags\\|ETAGS\\|etags\\|GTAGS\\|GRTAGS\\|GPATH\\)\\(<[0-9]+>\\)?"))
```
the `^ \\*"` should be changed to `^ `. 
4. If `?\s` is used as the only separator for overless, that has to be the value of `corfu-separator` as well because Corfu does not do the filtering of the candidates so that `&` will be treated as part of the search string.

2023-10-31 12:36 UTC, LuigiPiucco commented
Yes, I pushed yesterday to give a preview, but this code is not yet complete. I didn't implement escaping with `C-SPC`, and there are some mistakes, as you pointed out. I'll try to correct it later today.

2023-11-26 15:15 UTC, LuigiPiucco commented
New changes:
- Rebase to latest master;
- Merge @LemonBreezes's pull-request;
- Very small change to the first commit ([modules/completion/corfu/config.el](https://github.com/doomemacs/doomemacs/blob/232c25589f2ea8202c62c0dde43efbf2b3038f17/modules/completion/corfu/config.el#L12-L13));

2023-11-29 16:45 UTC, ReggieMarr commented
Just want to add my two cents, I've been using this module for the past while and it's been great.
I had actually setup corfu myself before that and the integrations provided here are better than what I setup myself.

That all being said, is this close to being merged ? It's a big improvement to the company completion setup imho so it'd be nice to see it mainlined

2023-12-04 12:57 UTC, Roger-Roger-debug commented on modules/completion/corfu/README.org
> +- +tng ::
Iirc `tng` refers to tab 'n go, that's what company calls it anyway

2023-12-04 17:51 UTC, LuigiPiucco commented on modules/completion/corfu/config.el
> +  :commands
Thanks for the clarification. I'll check and leave only any that lack the cookies.

2023-12-04 18:00 UTC, LuigiPiucco commented on modules/completion/corfu/packages.el
> +(package! corfu :recipe (:files ("*.el" "extensions/*.el")) :pin "457042d486e7542b9a6a832e47e6833d217ffd47")
This code is pretty old now, older than the addition to MELPA, and I believe ELPA used to not provide the extensions. That's probably why it's like this. It's no longer needed and can be removed, though. I'll do that in the next push.

2023-12-04 18:09 UTC, LuigiPiucco commented on modules/completion/corfu/README.org
> +** Module flags
I'll leave it for now, to give @LemonBreezes time to explain his rationale.

To be honest, I didn't like having `cape-line` by default, that's part of why I made it into a flag. It brought up too many completions that I never used. I agree with leaving this to the user, maybe a comment on the README about setting it up would suffice?

2023-12-04 18:18 UTC, LuigiPiucco commented on modules/completion/corfu/config.el
> +  (map! :unless (modulep! +tng) :gi "C-SPC" #'completion-at-point)
Wouldn't that cause problems with Company? It doesn't go through `completion-at-point` and has it's own entrypoint, no?

2023-12-05 17:17 UTC, LuigiPiucco commented on modules/completion/corfu/config.el
> +          [return] #'corfu-insert
It shouldn't be related to that, since I removed it locally as well. I just checked and it still seems to work fine. Maybe stale bytecode? Can you try `doom purge` with the changes coming soon?

2023-12-05 17:20 UTC, LuigiPiucco commented on modules/completion/corfu/config.el
> +        corfu-quit-at-boundary t
I remember the escape toggling feature working with this setup when I added it, but it's broken here now too. I think I fully fixed it now, though.

2023-12-05 20:35 UTC, LuigiPiucco commented on modules/completion/corfu/config.el
> +                    :filter +corfu--insert-separator-or-toggle-escape)))
I ended up implementing this differently in the current push. It's a regular command now; please check again. I used your suggestion to delete the separator instead of resetting everything, by the way.

As a side note, expanding `cmds!` leads to a nameless version of the prior `menu-item`s, so I guess it's the same in the end.

2023-12-05 20:46 UTC, LuigiPiucco commented
Above I marked as resolved everything I already addressed. Beyond that, there's a fix for LSP misbehavior included in the latest changes. Some things are still in discussion, those will be addressed later.

I don't quite like that @hpfr disappeared from the history after squashing though... Maybe I'll do something about that later.

2023-12-08 17:41 UTC, LuigiPiucco commented on modules/completion/corfu/config.el
> +              (add-hook 'completion-at-point-functions #'yasnippet-capf 30 t))))
As a small possible nitpick, is that `after!` needed? In `yasnippet-capf` I declare `yasnippet` in `Package-Depends`, I'd expect that to cause Emacs to always load it before the CAPF (and therefore the `add-hook!` will execute immediately anyway). I actually don't know, though.

The `:defer t` + `:init` bit really is unintentional, I'll fix it. About `defun` , I actually didn't read its documentation, just assumed it would work like `lambda` and return the created function 😅.

2023-12-09 19:30 UTC, ellakk commented on modules/completion/corfu/config.el
> +        :eig "C-SPC" #'completion-at-point
I think C-SPC should only be enabled for Evil modes since that is how you set the mark to copy text without Evil in Emacs.

2023-12-09 21:45 UTC, ellakk commented on modules/completion/corfu/config.el
> +        :eig "C-SPC" #'completion-at-point
Ah sorry, missed those comments, so why not add them to the config module in the this PR?

2023-12-09 22:55 UTC, LuigiPiucco commented on modules/completion/corfu/config.el
> +  (map! :unless (modulep! +tng) :gi "C-SPC" #'completion-at-point)
Okay. I think I'll just hold off on moving to `:config default` until either v3.0 or merge, since that module is not part of this PR. I believe changes aren't that frequent there, but they may become later, and that would make rebasing a pain. Resolving for now.

2023-12-09 23:06 UTC, LuigiPiucco commented on modules/completion/corfu/config.el
> +        :eig "C-SPC" #'completion-at-point
For now, I'll just remove the global binding, but later we'll have to consider how to handle Emacs bindings. I can't think of a good alternative to invoke completion in the default mode, and there needs be a binding set in the module.

2023-12-09 23:34 UTC, LuigiPiucco commented on modules/completion/corfu/config.el
> +    (add-hook 'evil-insert-state-exit-hook #'corfu-quit))
Actually, the one down below is strange. I don't remember why it's there and I tried reproducing the issue on its comment, but it works fine. I guess I kept it from some other iteration. I'll remove that one.

2023-12-09 23:45 UTC, LuigiPiucco commented on modules/completion/corfu/config.el
> +          [return] #'corfu-insert
Is this still an issue? I'd like to close it if not.

2023-12-10 08:04 UTC, ellakk commented on modules/completion/corfu/config.el
> +        :eig "C-SPC" #'completion-at-point
It's the :g that is the problem for people without the Evil module enabled. It's like removing Visual Mode in Vim as it's makes us unable to copy text. I think something like this would solve it:
```emacs-lisp
(if (modulep! :editor evil)
      (map! :map corfu-mode-map
            :ig "C-SPC" #'completion-at-point
            :mnor "C-SPC" (cmd! (call-interactively #'evil-insert-state)
                                (call-interactively #'completion-at-point))
            :v "C-SPC" (cmd! (call-interactively #'evil-change)
                             (call-interactively #'completion-at-point)))
    (map! :map corfu-mode-map
          "C-M-i" #'completion-at-point))
```

2023-12-10 18:27 UTC, LuigiPiucco commented on modules/completion/corfu/config.el
> +        :eig "C-SPC" #'completion-at-point
I'll use those bindings then. However, while playing around with `map!` trying to shorten the declaration, I found a greater issue. I thought `:g` shouldn't be needed for evil, because all states would have bindings, removing the need to put it into the `global-map`. I tried removing it, and unbinding `C-SPC` from `global-map` on `corfu-mode` entry, so it would keep searching until reaching `corfu-mode-map`. But that didn't work, I get "C-SPC is undefined". And, looking at `corfu-mode-map`, it's empty; after chasing my tail for _a while_, I discovered that `map!` only expands evil binds if the evil module has already been configured, meaning it has to come first in the user's `init.el`. I changed the order of the `:editor` and `:completion` categories and it worked. This is very weird, and something to investigate further. I'll push the latest version, please check if you can reproduce this.

2023-12-10 19:18 UTC, LemonBreezes commented on modules/completion/corfu/README.org
> +** Module flags
Hi. I just moved and I am currently building a new PC but yeah, I wanted to actually suggest the removal of `+line` myself. I do not believe it works well as an auto-capf.

2023-12-11 15:13 UTC, LuigiPiucco commented on modules/completion/corfu/README.org
> +** Module flags
I planned to push the removal yesterday, but got delayed. It will come in a few hours.

2023-12-14 18:40 UTC, LuigiPiucco commented
> which usually means you are composing something more complex, like a shell command

It also activates when searching a buffer with evil, which is the main pain point for me.

I can switch the bindings around, that was just an example of what I'm asking to help me with. The goal was to give the user a way to ignore the completion if needed. For instance, I often want to search the buffer for some word, and end up finding the match I'm looking for before typing the whole thing. But with auto completion, typing RET right then is going to complete the first candidate, which isn't what I want most of the time. This leads me to losing the match I found.

How about `RET` = `#'corfu-insert`, `C-RET` = `#'exit-minibuffer`, `C-S-RET` = `#'corfu-insert` then `#'exit-minibuffer`?

2023-12-15 09:45 UTC, asymmetric commented
(drive-by comment) Couldn't `ESC` be bound to `#'exit-minibuffer`? Or are the evil mode bindings active in the minibuffer (that would surprise me, it's not how it works for me)?

2023-12-15 14:46 UTC, LuigiPiucco commented
> (drive-by comment) Couldn't `ESC` be bound to `#'exit-minibuffer`? Or are the evil mode bindings active in the minibuffer (that would surprise me, it's not how it works for me)?

I think there may be a misunderstanding. `#'exit-minibuffer` is for when you want to "do" what you just typed in the minibuffer, no? For instance, if you're composing a shell command, it runs the command after exiting the minibuffer. In the case of search, it starts the search. You might have assumed it goes back without doing anything? In that case, `ESC` would be good, but it doesn't seem to work as a cancel here.

Evil is active in the minibuffer as well, it's just that we start in insert state and entering normal state runs `#'doom/escape`, so it seems like it's not.

Anyway, I think I managed to implement what I was talking about, I'll push later for feedback. We can always go back if it turns out bad.

2023-12-21 02:17 UTC, LemonBreezes commented
For `+tng`, I preferred the behavior we had before since it worked like the default but now I have to hit enter twice. Also, in `dap-eval`, `completion-at-point` is not bound, though that is the only scenario I know off the top of my head where I would want `cape-dabbrev` for sure even though `completion-at-point` is not bound.

2023-12-21 15:38 UTC, LuigiPiucco commented
> For `+tng`, I preferred the behavior we had before for the minibuffer completion since it worked like the default but now I have to hit enter twice.

Yes, I'm reimplementing that. Just finished, will push soon. That's what we're were discussing with `C-RET`/`S-RET`/`RET`/etc. above.
What I've settled with is (for `+tng` and non-`+tng`): just `RET` inserts the completion only, to match Corfu behavior in other buffers; `S-RET` is probably what you want, it inserts and finishes completion afterwards; `C-RET` is in case you don't want the completion, just to finish the minibuffer. This last one can happen when you want to search for part of a word but completion will give you a full word. Say, if you already found what you were looking for, you can go immediately, instead of inserting the candidate and possibly losing the match if it's the wrong word.

> Also, in `dap-eval`, `completion-at-point` is not bound, though that is the only scenario I know off the top of my head where I would want `cape-dabbrev` for sure even though `completion-at-point` is not bound.

I never managed to get DAP working quite right. Do you have a suggestion on how to handle this? Is checking for `dap-eval` in addition to `completion-at-point` being bound enough?

Along with the changes for the minibuffer, I removed `cape-line` and updated documentation in the coming push.

2023-12-21 22:16 UTC, LemonBreezes commented
> I never managed to get DAP working quite right. Do you have a suggestion on how to handle this? Is checking for `dap-eval` in addition to `completion-at-point` being bound enough?

To be honest, I would just check if the minibuffer prompt is "Eval: " an OR to the current condition.

(Haven't looked into the other changes yet but my guess is that I might prefer the old way XD)

2024-01-21 14:58 UTC, maikol-solis commented
> People have expressed frustration here and on Discord about the PR not getting merged. A gentle reminder that Henrik is the only one who can merge PRs, so as long as he isn’t around, there is nothing that can be done. In the meantime, you can easily add Luigi’s fork as a remote in your Doom checkout, checkout his branch, and run `doom sync -u`. Since Henrik is away you won’t be missing anything from the main branch.

Another solution for people who want to test the PR is to copy and paste the files into `~/doom.d/modules/completion/corfu`, and it should work as expected.

With all due respect to Henrik and the entire project, I don't know if he could grant PR merging permissions to well-known and capable community members. According to the Discord announcements, he is dealing with some personal issues, and it is important that he has the time and space to address them. Meanwhile, the community can help him merge small PRs and update some modules until he returns.

It is just a suggestion, and I entirely understand if he can't do it at this moment.

Best.

2024-01-22 16:40 UTC, LuigiPiucco commented on modules/config/default/+evil-bindings.el
> +        "C-h"   #'corfu-popupinfo-toggle)))
Would this be better if bound to `C-i`? For "info", as in the code's documentation. Also, this binding only takes effect when Corfu is completing and popupinfo is active, I think it's reasonable to expect users to press `ESC` before going to the help menu.

2024-01-22 16:48 UTC, LuigiPiucco commented on modules/config/default/config.el
> +         "C-s" #'+corfu-move-to-minibuffer
To be honest, this functionality is somewhat specific and power-user only. I wonder if we should leave it unbound, with a comment on the README about setting it? That being said, I just looked it up, and it seems company binds similar functionality to `C-S-s`. I'll bind to that for now.

2024-01-22 16:56 UTC, LuigiPiucco commented on modules/completion/corfu/config.el
> +  (global-corfu-mode)
I was having some issue with defered loading, but it seemed temporary. I'll check if it's gone and update accordingly. However, maybe there's a better hook for this; is there some way to load when `completion-at-point-functions` is added-to for the first time? This way, if the user never enters a buffer that has completion support, we don't need to load Corfu.

2024-01-22 17:07 UTC, LuigiPiucco commented
I added some questions/comments above, and will push again when we resolve then.

About the delay in merging, I agree we should give Henrik time to sort things out, I'll be maintaining the fork meanwhile. It is good to investigate the possibility of following @maikol-solis's advice, but let's not rush.

About the people who were frustated, can I ask what is the main painpoint? Maybe there's something I can do to help aliviate it. The big difference I can see with maintaining a forked config is that `doom upgrade` doesn't work, requiring manual git intervention. Perhaps changing the script temporarily to track my branch would help?

2024-01-23 09:12 UTC, peterhoeg commented
How about this instead:

┌────
│ (use-package! corfu
│   :defer-incrementally t
│   :config
│   (global-corfu-mode))
└────

Sure, it will end up loading even if not needed, but it will not delay regular loading and it will *most likely* be available when needed.

I’ve used `:defer-incrementally t' quite a lot for these “not critical to be immediately available but good enough as long as it’s there at some point” cases.

2024-01-24 16:21 UTC, LuigiPiucco commented on modules/completion/corfu/config.el
> +  (global-corfu-mode)
I changed to `doom-first-buffer-hook` for now, maybe I'll look more into it later.

2024-01-24 16:23 UTC, LuigiPiucco commented
Beyond addressing the review, I also added a section about the minibuffer `RET/C-RET/S-RET` binds so that people don't have to come across this thread to understand it.

2024-01-25 18:50 UTC, LuigiPiucco commented on modules/completion/corfu/README.org
> +kicked in as you typed, you may loose the match, since it will complete the
Now this is a bit embarrassing... :rofl:

2024-01-26 15:17 UTC, LuigiPiucco commented on modules/completion/corfu/README.org
> +kicked in as you typed, you may loose the match, since it will complete the
I'll squash then, I agree history should be terse regarding typos. I just accepted the GitHub suggestion and it committed.

2024-01-29 10:17 UTC, peterhoeg commented
IMO the standard defer keyword and hooking global-corfu-mode to something like doom-first-buffer-hook makes more sense in this case




The problem is that it delays startup. And I’m not calling out this specific module, but it’s more of a general problem. Doom will report a very brief loading time (about 1s) in my case with about 400 packages, but it’s still 10 seconds before emacs becomes available when launched directly (without emacsclient) due to all the bits that are activated on “ready for someone to do some input”.



For many of my own things, I use defer-incrementally simply because I don’t need them immediately, but they are most likely available when I do need them. And I would imagine that it’s quite unlikely that people need it right away.



You have a good point about possible support issues, but I would argue that we could document ourselves out of it, or maybe even introduce a new :delay-interactive option so we have a proper way to choose between “make it available at some point” and “ensure it’s available for immediate use”.

2024-01-30 03:28 UTC, LemonBreezes commented
Also, since we use Corfu in the minibuffer, it's possible that you would want Corfu for interactively evaluating Elisp before any buffers are loaded. And it's not possible for a user to modify the loading behavior of Corfu without modifying the Doom Emacs source code.

2024-02-01 03:17 UTC, liaowang11 commented
There are some keybindings under `modules/editor/evil/config.el`, which I think are really useful for evil users, specifically `company-files` alike.
How about bind <kbd>C-x C-f</kbd> to `cape-file` and <kbd>C-x C-l</kbd> to `cape-line`?
```elisp
      (:when (modulep! :completion company)
        (:prefix "C-x"
         :i "C-l"    #'+company/whole-lines
         :i "C-k"    #'+company/dict-or-keywords
         :i "C-f"    #'company-files
         :i "C-]"    #'company-etags
         :i "s"      #'company-ispell
         :i "C-s"    #'company-yasnippet
         :i "C-o"    #'company-capf
         :i "C-n"    #'+company/dabbrev
         :i "C-p"    #'+company/dabbrev-code-previous))
```

2024-02-02 13:28 UTC, LemonBreezes commented
Also, I finally got that Anzu PR merged (the one that was necessary for the minibuffer `+tng` completion implementation I wrote): https://github.com/emacsorphanage/anzu

2024-02-02 14:08 UTC, emenel commented
Since updating to the latest PR in my personal config `global-corfu-mode` is no longer enabled automatically at all, and I have to manually call it to get completion working.

2024-02-02 15:37 UTC, LuigiPiucco commented
> Since updating to the latest PR in my personal config `global-corfu-mode` is no longer enabled automatically at all, and I have to manually call it to get completion working.

Yes, it's because of a typo. The `:hook` keyword of `use-package` appends `-hook` to the name automatically, I forgot that, so it was adding `global-corfu-mode` to `doom-first-buffer-hook-hook`. I'm correcting the typo as well as applying the above suggestions.

For the keybinds, I'll only add the ones present in cape, since some of the listed company ones would require a separate implementation. I can do that later if asked to, but let's limit the scope of this PR for now.

2024-02-02 16:07 UTC, LuigiPiucco commented
@LemonBreezes can you adapt your code now that the Anzu PR is merged? I'll ask you to PR it again to my fork, since I rebased the bit about Anzu out for simplicity while we awaited it. I assume it would need refactoring anyway.

As to the latest push, the branch is rebased; has the new keybindings; and properly activates on startup now.

2024-02-03 19:46 UTC, LuigiPiucco commented on modules/completion/corfu/config.el
> +  (when (modulep! :editor evil)
This has been fixed and can be resolved. I believe the "moving to `:config default`" commit was the one.

2024-02-03 19:51 UTC, LuigiPiucco commented on modules/completion/corfu/config.el
> +          (:when (modulep! :editor evil) "s-j" #'corfu-move-to-minibuffer))))
We ended up settling on `C-S-s`, which is the same as company's version of this.

2024-02-03 19:55 UTC, LuigiPiucco commented on modules/completion/corfu/config.el
> +  (map! :unless (modulep! +tng) :gi "C-SPC" #'completion-at-point)
We did end up moving to `:config default`, as it fixed some precedence issues. I'll resolve.

2024-02-04 21:42 UTC, LuigiPiucco commented
Yesterday's push was just a rebase. Today, 1) I updated `+corfu-move-to-minibuffer` to the new suggestion on Corfu's README, with some changes to (hopefully) decouple from vertico/consult. I haven't tested helm, ivy and ido though, so if someone uses them with Corfu a report would be appreciated; and 2) bumped the packages in the module, plus `evil-collection`, due to a breaking change in Corfu. An explanation is provided in the relevant commit.

2024-02-06 19:36 UTC, LuigiPiucco commented
Changelog for last push:
1. Rebase;
2. Fix the de-structuring pattern in `+corfu-move-to-minibuffer` (by removing the `.` operator);
3. Switch to `completing-read` instead of `completion-in-region` for the generalized implementation (this is supported by all of the frameworks, isn't overridden by Corfu and doesn't depend on the `default-value` of a symbol being correct);

2024-02-06 19:41 UTC, LemonBreezes commented
(Also I will get back to you with a PR latest this weekend)

2024-02-07 12:52 UTC, jduhamel commented
This may be a nit but the binding for cape-file is set to run on C-x C-f where the equivalent company-file is only for insert mode in evil-mode. Was not quite what I expected when I tried to open a file. 
It also seems to overwite some other keybinds such as C-x C-k, C-x C-l etc.

2024-02-08 17:27 UTC, miker2049 commented
Just to add on:  `C-x s` for saving all buffers is a huge muscle memory command for me and seems to also now be shadowed by the cape command `cape-dict` .

2024-02-09 21:45 UTC, LuigiPiucco commented
The C-x bindings are behind insert state now. It bothers me that there is no equivalent to them for Emacs-binding users, but that seems to be the case for company as well.

2024-02-12 05:41 UTC, LemonBreezes commented
Ok I didn't realize this weekend was the superbowl but I'll try to do this soon.

2024-02-12 16:14 UTC, minad commented
@LuigiPiucco 

> Switch to completing-read instead of completion-in-region for the generalized implementation (this is supported by all of the frameworks, isn't overridden by Corfu and doesn't depend on the default-value of a symbol being correct);

This has the following disadvantages:

1. In contrast to `completion-in-region`, `completing-read` does not insert the selected candidate in the buffer when pressing RET and it does not invoke the `:exit-function`.
2. `consult-completion-in-region` previews the selected candidate in buffer.

2024-02-12 17:20 UTC, LuigiPiucco commented
> @LuigiPiucco
> 
> > Switch to completing-read instead of completion-in-region for the generalized implementation (this is supported by all of the frameworks, isn't overridden by Corfu and doesn't depend on the default-value of a symbol being correct);
> 
> This has the following disadvantages:
> 
>     1. In contrast to `completion-in-region`, `completing-read` does not insert the selected candidate in the buffer when pressing RET and it does not invoke the `:exit-function`.
> 
>     2. `consult-completion-in-region` previews the selected candidate in buffer.

Yes, it's certainly not perfect; there's a trade-off here, between making it featureful vs. compatible. I agree the `completing-read` implementation is not equivalent, I wouldn't classify it as a general piece you could put in Corfu's README, for instance. To clarify, the use-case I had in mind is not just getting the completions onto the other frameworks, it's using them to export and manipulate the completion info. To my knowledge, this entails sending it to a buffer, which brings further considerations.

The main reason for the change is that Doom supports other frameworks (ivy, helm and ido) which have their own APIs and aren't exactly compatible with one another. Corfu + Vertico (in Doom, the latter brings Consult) is a fortunate pairing, since they complement each other, but I'd like to support other combinations as well.

Also, for the technical limitations, they seem ok to me:

1. If the user just wants to insert into the buffer, they don't need to go through that function, Corfu does this on RET;
2. If the user wants to modify the completions then insert, they'll probably end up exporting to a regular buffer, so I think the difference from RET-when-done to copy-paste is not too much of a loss here;
3. Not running `:exit-function` is a problem for things like snippets, they won't be expanded, but I'm not sure if much can be done in that front, nor how valuable that would be. To get something like that done well would be much more involved coding than is the scope here;
4. Preview is nice, but if the user is modifying the list, wouldn't that get cumbersome?

This was my reasoning, but feel to make suggestions and discuss further. It also depends on Henrik's review, maybe he'll have different opinions or solutions to these shortcomings, so I won't revert for now.

2024-02-12 17:30 UTC, minad commented
@LuigiPiucco As far as I know, both Ivy and Helm support `completion-in-region` and Vertico supports it via `consult-completion-in-region`. If all you want is moving the candidates to the minibuffer, then `completing-read` is good enough, e.g., for acting with Embark. I only want to point out is that `completion-in-region` is not equivalent to `completing-read`. You lose the main feature, namely completing in the original buffer. For background, `consult-completion-in-region` is essentially a wrapper around `completing-read`, a wrapper with additional functionality.

2024-02-16 06:00 UTC, LemonBreezes commented
Okay, I just updated to the latest version of this module so I'm gonna begin working on getting the `+tng` minibuffer completion like what it was before for me and some small recommendations here and there.

2024-02-16 19:01 UTC, LuigiPiucco commented
> ```emacs-lisp
> (defun corfu-move-to-minibuffer ()
>   (interactive)
>   (pcase completion-in-region--data
>     (`(,beg ,end ,table ,pred ,extras)
>      (let ((completion-extra-properties extras)
>            completion-cycle-threshold completion-cycling)
>        (funcall
>         (or (seq-find #'fboundp '(consult-completion-in-region
>                                   ivy-completion-in-region
>                                   helm-completion-in-region))
>             (error "No minibuffer completion UI available"))
>         beg end table pred)))))
> ```

I tried this snippet and have some comments, also some advancements and issues. While it _should work_, only consult is compliant enough in my testing.
- Ivy is mostly compliant with `completion-in-region`, and calling it as above exports like expected, but it doesn't support the markers we get for beg and end. They move when ivy deletes the thing at point for preview, and that causes an attempt to delete negative markers on RET. So for ivy we need to convert those to positions before passing;
- Helm doesn't have any `helm-completion-in-region` that I could find, it only provides `helm--completion-in-region`, which isn't fully compliant. It wants to be used as `:around` advice for the default `completion--in-region`, so we'll have to implement that for Doom (it isn't currently) and call the default if we detect helm's advice;
- Ido doesn't implement `completion-in-region`, and its `completing-read` is restricted to a list of strings as the table. This is my main issue, I'm unclear on how to export to it. Though it seems like it can't use the advanced transforms this is meant to enable, so perhaps we could do without that? Another option is using `completion--in-region` for ido as well.

I'll push my current implementation soon, it accounts for ivy and helm, considers ido as an error case, and fixes helm's completion-in-region. It has some Doom specific checks (`modulep!` for whether the respective module is enabled), but otherwise may be considered for inclusion in the README, if you want. It's not as clean, since it checks for each framework, so perhaps an explanation on how to optimize for non-modular configs should accompany.

2024-02-17 17:37 UTC, LemonBreezes commented
Hi. Just opened a PR with a bunch of fixes and opinions.
https://github.com/LuigiPiucco/doom-emacs/pull/3

2024-02-17 21:26 UTC, hlissner requested changes
Looks pretty good! I think all the `completion-at-point-functions` hooks in cape's config could be abstracted a bit (ala `set-company-backend!` -- but not exactly, that function is overdue a redesign as well), but I'll worry about that down the road. Also, adding `cape-dabbrev` to text-mode-hook casts too wide a net, but I'll factor that in when I get to capf abstractions later.

I'll check in again once you've sorted out the helm/ivy/ido stuff.

2024-02-17 21:26 UTC, hlissner commented on modules/config/default/+evil-bindings.el
> +        :desc "LSP Rename"                           "r"   #'lsp-rename
I agree with these changes, but they don't belong in this PR. Please rebase them out.

2024-02-17 21:26 UTC, hlissner commented on modules/config/default/+evil-bindings.el
> +        :desc "LSP Rename"                           "r"   #'eglot-rename
I agree with these changes, but they don't belong in this PR. Please rebase them out.

2024-02-17 21:26 UTC, hlissner commented on modules/config/default/config.el
> +          "<remap> <completion-at-point>" #'+corfu-smart-sep-toggle-escape)
Use `[remap completion-at-point]` instead of `"<remap> <completion-at-point>"`

2024-02-17 21:26 UTC, hlissner commented on modules/config/default/+emacs-bindings.el
> +         "C-S-h" #'corfu-popupinfo-toggle))
Indentation: one space too many

2024-02-17 21:26 UTC, hlissner commented on modules/completion/corfu/config.el
> +      (setq orderless-component-separator #'orderless-escapable-split-on-space))))
This seems redundant with the `orderless-component-separator` change in the vertico module?

2024-02-17 21:30 UTC, hlissner requested changes
Two other things I noticed:

- 0196f1e61afbe4dc88d87bf40ca9a13467134298: Please remove mention of `evil-collection`, since it's no longer affected by the change. It also lacks commit diff lines. E.g.
   ```
   minad/corfu@24dccafeea11 -> minad/corfu@b48d3017a477
   minad/cape@18a30f48bb87 -> minad/cape@bfde79ed4403
   elken/yasnippet-capf@a0a6b1c2bb6d -> elken/yasnippet-capf@db12b55cd08b
   ```

- 28ffdd016db61274946ec4d78b0cd16cabe107ad: please remove the space in the commit header:
   ```diff
   -feat(corfu, vertico): use equal orderless config 
   +feat(corfu,vertico): use equal orderless config 
   ```

2024-02-17 21:49 UTC, LuigiPiucco commented on modules/completion/corfu/config.el
> +      (setq orderless-component-separator #'orderless-escapable-split-on-space))))
This is in case Vertico is not active, but Corfu `+orderless` is. In the common case where they're together it really is redundant, but with other back-ends it guarantees the known value.

2024-02-18 00:56 UTC, LuigiPiucco commented
> I'll check in again once you've sorted out the helm/ivy/ido stuff.

About this, my prior comment was a bit poorly written, the push you reviewed already contained my suggestion for handling them. Helm and Ivy required only adapting to a few quirks, but Ido isn't quite able to support the export. I opted to leave it as unimplemented (trying to export with Ido enabled is treated the same as trying to export without a completion UI), as this simplifies the function. The main decision that needed to be taken was whether we'd try to implement it anyway, but I don't know how that could be done, so if export to Ido is necessary I may need some help.

Also, @LemonBreezes is working on some improvements, I'll ping again when we've got that ready.

2024-02-20 05:47 UTC, LemonBreezes commented
Ok. I made two

> > I'll check in again once you've sorted out the helm/ivy/ido stuff.
> 
> About this, my prior comment was a bit poorly written, the push you reviewed already contained my suggestion for handling them. Helm and Ivy required only adapting to a few quirks, but Ido isn't quite able to support the export. I opted to leave it as unimplemented (trying to export with Ido enabled is treated the same as trying to export without a completion UI), as this simplifies the function. The main decision that needed to be taken was whether we'd try to implement it anyway, but I don't know how that could be done, so if export to Ido is necessary I may need some help.
> 
> Also, @LemonBreezes is working on some improvements, I'll ping again when we've got that ready.

Ok. I made two small PRs and that's it basically.

2024-02-21 23:14 UTC, LemonBreezes commented
> > I'll check in again once you've sorted out the helm/ivy/ido stuff.
> 
> About this, my prior comment was a bit poorly written, the push you reviewed already contained my suggestion for handling them. Helm and Ivy required only adapting to a few quirks, but Ido isn't quite able to support the export. I opted to leave it as unimplemented (trying to export with Ido enabled is treated the same as trying to export without a completion UI), as this simplifies the function. The main decision that needed to be taken was whether we'd try to implement it anyway, but I don't know how that could be done, so if export to Ido is necessary I may need some help.
> 
> Also, @LemonBreezes is working on some improvements, I'll ping again when we've got that ready.

Dude, for some reason none of the :enable menu items work for me. They just get enabled unconditionally.

2024-02-23 15:47 UTC, LemonBreezes commented
Based on the Emacs maintainers replies to my bug report in https://debbugs.gnu.org/cgi/bugreport.cgi?bug=69306, the `:enable` attribute does not affect key lookups. So we should use `:filter` instead.

2024-02-24 00:55 UTC, LemonBreezes commented
Okay, the way I have resolved the YaSnippet vs Corfu vs indentation keybinding collision in my personal config:
```elisp
(setq tab-always-indent 'complete)
(after! cc-vars
  (setq c-tab-always-indent 'complete))
(map! [C-i] #'doom/dumb-indent
      "C-S-i" #'doom/dumb-dedent
      (:when (and (modulep! :editor snippets)
                  (modulep! :completion corfu +tng))
       ;; Use `M-<tab>' for expanding snippets when we are using `<tab>' for
       ;; completion. 
       (:after yasnippet
        :map yas-minor-mode-map
        "M-<tab>" yas-maybe-expand
        "TAB" nil
        :map yas-keymap
        "TAB" nil
        "S-<tab>" nil
        "<backtab>" nil
        "M-<tab>" (yas-filtered-definition 'yas-next-field-or-maybe-expand)
        "M-S-<tab>" (yas-filtered-definition 'yas-prev-field))
       (:after corfu
        :map corfu-map
        "M-<tab>" yas-maybe-expand
        ;; Collides with the alternate Doom leader key so you might want to use
        ;; comma as a separator like I did in my private config or use a
        ;; different key for this.
        :ig "M-SPC" #'+corfu-smart-sep-toggle-escape)))
```
I think we should probably include something like this in the module but then again, the current Company module also has this keybinding collision issue.

2024-02-28 11:06 UTC, abeforgit commented
While I think the minibuffer completion is neat, and the C-RET and family bindings a sensible default, years of vim muscle memory make it really hard to get used to having to hit C-RET everytime I want to save all (`:wa` in vim-world). 

For those in the same boat, here's how I disabled the minibuffer completions:
```elisp
(after! corfu
  (add-hook! 'minibuffer-setup-hook
    (defun +corfu-enable-in-minibuffer ()
      "override the corfu hook to make sure it doesn't trigger in the minibuffer"
      (corfu-mode -1)
      ))
  )
```

It might be an idea to add an opt-out option for the minibuffer completions in this module, but I'm ok with the above workaround as well.

2024-02-28 11:36 UTC, LemonBreezes commented
> While I think the minibuffer completion is neat, and the C-RET and family bindings a sensible default, years of vim muscle memory make it really hard to get used to having to hit C-RET everytime I want to save all (`:wa` in vim-world). 
> 
> For those in the same boat, here's how I disabled the minibuffer completions:
> ```elisp
> (after! corfu
>   (add-hook! 'minibuffer-setup-hook
>     (defun +corfu-enable-in-minibuffer ()
>       "override the corfu hook to make sure it doesn't trigger in the minibuffer"
>       (corfu-mode -1)
>       ))
>   )
> ```
> 
> It might be an idea to add an opt-out option for the minibuffer completions in this module, but I'm ok with the above workaround as well.

Another option which I like is that for `+tng`, RET can insert the completion and exit the minibuffer. We can already insert completions without exiting by using TAB.

2024-02-28 23:46 UTC, LemonBreezes commented
> While I think the minibuffer completion is neat, and the C-RET and family bindings a sensible default, years of vim muscle memory make it really hard to get used to having to hit C-RET everytime I want to save all (`:wa` in vim-world).
> 
> For those in the same boat, here's how I disabled the minibuffer completions:
> 
> ```emacs-lisp
> (after! corfu
>   (add-hook! 'minibuffer-setup-hook
>     (defun +corfu-enable-in-minibuffer ()
>       "override the corfu hook to make sure it doesn't trigger in the minibuffer"
>       (corfu-mode -1)
>       ))
>   )
> ```
> 
> It might be an idea to add an opt-out option for the minibuffer completions in this module, but I'm ok with the above workaround as well.

Ok. I just added a `+corfu-want-minibuffer-completion` option to my latest Corfu module PR: https://github.com/LuigiPiucco/doom-emacs/pull/5 as well as the TAB `+tng` behavior I was talking about.

2024-03-02 04:41 UTC, LemonBreezes commented
One more PR with fixes to the last PR as well as the addition of Fish completion:
https://github.com/LuigiPiucco/doom-emacs/pull/6

Check out my commit message on the Fish completion commit.

2024-03-02 16:40 UTC, LuigiPiucco commented
Warning: Big breaking change incoming.

See https://github.com/doomemacs/doomemacs/pull/7002/commits/03f065df9f95a79633019dadf7b44ab1fe701289 and the new README for details, but now the modules flags are implemented to enable particular behaviors rather than to select between named styles. This allows the user to configure everything to their liking (or very little at all if desired). It attempts to solve having the personal preferences of the authors interfere with the users' and cause need for working around them. The change is somewhat experimental and may be undone depending on feedback.

The only real intended "removal" was pruning the global CAPF count, in favor of having separate keybindings. So `+dict`, `+emoji`, and other such features are moved to the `C-x` prefix, if opted-in, or left for the user to add. The exception is `+dabbrev`, which works very well and doesn't obscure the semantic alternatives.

2024-03-03 03:07 UTC, LemonBreezes commented
Hi @LuigiPiucco. Generally, we shouldn't have that flags or variables to tune keybindings unless they are global keybindings, see https://discourse.doomemacs.org/t/do-not-pr/2406 and https://github.com/doomemacs/doomemacs/pull/7176. So using `:when` is okay for the `C-x` bindings, but not for any of the other ones. I don't think @hlissner will approve these changes.

Having a variable for the smart return behavior is okay because we can code it into the `:filter` function itself so that the user does not have to run `doom sync` to try the different behaviors. 

Also, I had just fixed the `cape-spell` backend in my new PR. What was the precise sense in which the other backends did not work?

2024-03-03 18:04 UTC, LuigiPiucco commented on modules/completion/corfu/README.org
> +and vi movements to control the selection and documentation view.
No, it was more to keep consistent with the general theme of the refactor. It does make more sense to document how to remove them instead of having a flag though.

2024-03-03 19:11 UTC, LuigiPiucco commented on modules/completion/corfu/autoload.el
> +(defun +corfu-in-doc-or-comment-p (_sym)
This was used to limit the text CAPFs to comments and documentation (with proper tree-sitter support), but the last commit removes those from the global list. I'll leave it as a comment on the README, but remove from here.

2024-03-03 19:41 UTC, LuigiPiucco commented
> Also, I had just fixed the `cape-spell` backend in my new PR. What was the precise sense in which the other backends did not work? I guess if no one will miss them it's okay to remove them. :(

Sorry if it was rude of me to remove them, but they weren't broken, there were just too many in `completion-at-point-functions`. So at least for me, there were many trivial candidates to sift through in some modes (org for instance, would list a lot of emojis any time I typed a colon), I had to prune the list very often. So I thought it would be better to leave this to the user. Also, I'm now fixing this issue based on Liam's comments, but the list of module flags was pretty big, removing made it shorter.

I'm rebasing the commit shortly, it will remove some flags and transfer certain features to the documentation for the user to include in their config.

2024-03-04 03:26 UTC, LemonBreezes commented
> > Also, I had just fixed the `cape-spell` backend in my new PR. What was the precise sense in which the other backends did not work? I guess if no one will miss them it's okay to remove them. :(
> 
> Sorry if it was rude of me to remove them, but they weren't broken, there were just too many in `completion-at-point-functions`. So at least for me, there were many trivial candidates to sift through in some modes (org for instance, would list a lot of emojis any time I typed a colon), I had to prune the list very often. So I thought it would be better to leave this to the user. Also, I'm now fixing this issue based on Liam's comments, but the list of module flags was pretty big, removing made it shorter.
> 
> I'm rebasing the commit shortly, it will remove some flags and transfer certain features to the documentation for the user to include in their config.

Yeah, I was a bit upset that there were so many changes but today I sent a patch fixing an Org mode issue that has been splitting my hairs for years so I feel better and I hope that gets accepted: https://lists.gnu.org/archive/html/emacs-orgmode/2024-03/msg00037.html. 

I'll check it out tonight or tomorrow or something. Soonish.

2024-03-04 15:55 UTC, LemonBreezes commented on modules/completion/corfu/README.org
> +fixes the issue Cape's implementation has with tree-sitter.
I only tested it with the tree-sitter.el external package which Doom Emacs uses and is now obsolete in favor of the built-in tree-sitter support in Emacs29+. But for tree-sitter.el, I did open an issue in Cape and will edit this comment in 1 minute with a link.

2024-03-04 16:12 UTC, LuigiPiucco commented on modules/completion/corfu/README.org
> +fixes the issue Cape's implementation has with tree-sitter.
LemonBreezes would be better suited to explain this, I mostly just pattern-matched his code. But I believe one was opened, https://github.com/minad/cape/pull/109, and to fix it would require non-trivial hacks and maybe a tree-sitter dependency (I'm unsure), so minad opted to not accept it. Perhaps a better solution would be a general comment on the edge cases of `cape-capf-inside-*`, placed in Cape's README?

2024-03-04 16:21 UTC, LuigiPiucco commented on modules/config/default/+emacs-bindings.el
> +
`C-S-h` is there for parity with Company, it binds to `company-show-doc-buffer` a few lines above. Though maybe that function doesn't do what I think it does, I assumed it was to show/hide Company's popupinfo equivalent. If it is for that, maybe we could take the inverse path, change Company to use `M-t`? Or ignore this, parity probably doesn't need to be that perfect.

2024-03-04 16:28 UTC, LuigiPiucco commented on modules/completion/corfu/README.org
> +
That's a good point, which I kind of forgot. I think there were other places where working with completion-at-point instead of just Corfu could simplify things and expand usage. I'll review that too in the next push.

About removing, I think merging the other section to here would be a better text layout now that it isn't tied to a flag, I'll use that for now, we can change later if needed.

2024-03-04 16:29 UTC, LemonBreezes commented on modules/completion/corfu/README.org
> +fixes the issue Cape's implementation has with tree-sitter.
Yeah, basically getting the face at point actually gets the face of the character after the point. If you run `(describe-char (point-max))` you get the error "No character follows specified position." So you basically shouldn't use faces unless the construct involves being inside a paired delimiter like inside quotes (but not directly on the quotes). Hence, when the comments are line comments, you need to use `(nth 4 (syntax-ppss))`.

2024-03-04 16:31 UTC, LuigiPiucco commented on modules/completion/corfu/README.org
> +A snippet to unbind them is included after the table.
It's there for convenience, so the user doesn't have to look up all bindings, but since it's uncommon to remove these it can probably be removed.

2024-03-04 16:53 UTC, LemonBreezes commented on modules/completion/corfu/README.org
> +fixes the issue Cape's implementation has with tree-sitter.
Aha we should make cape-wrap-inside-faces check `(1- (point))` instead!

2024-03-04 17:14 UTC, LemonBreezes commented
> @LemonBreezes just to make sure, would you mind if I add you as a maintainer here? You already did in your PR, but since that may take a couple more days to settle, I'd like to give you proper credit sooner.

Sure! Thank you.

2024-03-06 16:12 UTC, LuigiPiucco commented on modules/completion/corfu/config.el
> +      (setq orderless-component-separator #'orderless-escapable-split-on-space))))
I'll close this for completeness, but feel free to reopen if my explanation was not enough.

2024-03-07 00:10 UTC, LemonBreezes commented
I've been reviewing the new changes and they are too extensive and basically broke the +tng behavior we had before. I'm just gonna use the previous version of the module for now. I think such wild drastic changes to the module's keybindings and flags should be broken up into smaller commits as well because this is very difficult for me to thoroughly review. I don't understand the reasoning for each of these individual changes either so I do not feel comfortable reverting your changes without discussing it with you first. Personally, I say, revert the changes, keep the old `+tng` flag and its behaviors & keybindings exactly as they were, and recommit the changes with smaller commits. 

What specific behaviors did you want from `+tng`? The trade-off between the two styles to me is basically that `+tng` is more ergonomic but causes the TAB key to not be as usable for indentation or expanding snippets.

2024-03-08 01:07 UTC, LuigiPiucco commented
About having smaller commits, I had already planned to restructure history once we settled on a design, I did it this way now because I was unsure if I was gonna keep the new changes or try an overhaul again (having one commit would have made reverting easier). However, now I'm more toward keeping these changes, restructuring before merge.

The purpose was not to remove `+tng` behavior, it was to make those behaviors modular while also making them easier to adapt without requiring the user to undo our defaults. Removing the flag was just a consequence.

I've rebased some changes, if those are enough I will tidy history tomorrow.

> You could have always done that with `+tng`. That has nothing to do with the latest changes. That is the default behavior of `indent-for-tab-command`, which is bound to TAB even in vanilla Emacs.
> 
> The latest changes have removed `+tng` all together and do not have TAB bound at all during completion so I believe you are not using the latest version of this module.

I think Prashant is referring to `tab-always-indent`. Previously, it was set to `'complete` in `+tng`, but left alone otherwise. Now it's always `'complete`.

> It's basically VS Code completion.

To my knowledge, VSCode only inserts on `RET`, pressing `TAB` just cycles the preview, but it is not inserted automatically.

2024-03-11 02:10 UTC, LemonBreezes commented
> Briefly looking over https://github.com/LuigiPiucco/doom-emacs/pull/8, you have some menu items with several `(modulep! :editor snippets)` checks buried in the definitions. Doom modules can only be enabled or disabled when syncing, not at runtime (unless you use `doom/reload`, which reloads your private config anyway), so you should just only define and bind the snippet menu items for users with the snippets module, and leave TAB and `S-TAB` bound directly to the Corfu commands for everyone else. Keeping dispatching/indirection minimal in bindings makes `describe-key{,-briefly}` more efficient for users.
> 
> The PR-to-a-PR strategy can work well when iterating heavily on an early unreviewed draft, but after this most recent one is resolved, you might want to stick to review comments here. It can be hard to determine the current status of this PR when reviewers have to keep checking the PRs to the fork, and reviewers might object to additions once they make it to the Doom PR anyway. Future improvements can always be added in subsequent PRs directly to Doom. For example, the changes to TAB yasnippet priority seem like enough content to move to a subsequent PR to avoid piling on review burden here.

Sure. The easiest way would be to wrap `cmds!` with an `eval` form. 

Also, I wanted to ask, how do you do those code reviews that you do for the PR? Do/Can you do them with the review package or how do you use the UI to do that?

2024-03-18 15:43 UTC, LemonBreezes commented
Ok. I have a patch for this PR that fixes an issue where the YaSnippet Capf doc buffer doesn't work in Evil mode:
```diff
-  (add-hook 'evil-insert-state-exit-hook #'corfu-quit)
+  (add-hook! 'evil-insert-state-exit-hook
+    (defun +corfu-quit-on-insert-exit-h ()
+      ;; This is a workaround for Corfu exiting when showing the popup
+      ;; help for `yasnippet-capf'.
+      (when (eq (window-buffer) (current-buffer))
+        (corfu-quit))))
```

2024-03-19 18:40 UTC, LuigiPiucco commented on modules/completion/corfu/config.el
> +               (timer--args evil--ex-search-update-timer))))))
@LemonBreezes Now that we dont't use `C-RET` and `S-RET` for the minibuffer anymore, can this be removed? It's commit message mentions it fix an issue with those binds, but they're not necessary with the overhaul and will disappear after the coming rebase.

2024-03-19 19:58 UTC, LuigiPiucco commented
> Ok. I have a patch for this PR that fixes an issue where the YaSnippet Capf doc buffer doesn't work in Evil mode:
> 
> ```diff
> -  (add-hook 'evil-insert-state-exit-hook #'corfu-quit)
> +  (add-hook! 'evil-insert-state-exit-hook
> +    (defun +corfu-quit-on-insert-exit-h ()
> +      ;; This is a workaround for Corfu exiting when showing the popup
> +      ;; help for `yasnippet-capf'.
> +      (when (eq (window-buffer) (current-buffer))
> +        (corfu-quit))))
> ```

Hmm, I can't observe the issue in the comment, it shows the documentation correctly. It may be that you're seeing snippets from LSP, though. Try to isolate `yasnippet-capf` to make sure. The following picture was obtained by typing a prefix, `M-x`, `yasnippet-capf`, `RET`, which should single it out.

![image](https://github.com/doomemacs/doomemacs/assets/31187340/cbe4124e-b80b-41ca-9cc5-916d6e34532f)

In contrast, this is an LSP snippet:

![image](https://github.com/doomemacs/doomemacs/assets/31187340/51460345-da44-45d1-b407-c4065b212d0e)

One issue I have observed is that pressing `ESC` with an LSP snippet selected expands it as if it had been selected. Maybe that's what you were referring to? We can't fix that one here, though, as it's a problem with `lsp-mode` (it quits properly with elken's package).

2024-03-19 20:14 UTC, LuigiPiucco commented
@hlissner Now that it's rebased with more concise history, it should be ready to review and hopefully merge. The only thing still pending is my last source comment, which might allow removal of https://github.com/doomemacs/doomemacs/pull/7002/commits/e9cc75e8b2f94cc32343698e638ba78eea50d88a. Later we can also transfer https://github.com/LuigiPiucco/doom-emacs/pull/8 to this repository's issue tracker.

2024-03-19 20:59 UTC, LemonBreezes commented on modules/completion/corfu/config.el
> +               (timer--args evil--ex-search-update-timer))))))
No. It also is used when `+corfu-want-ret-to-confirm` equals `minibuffer`.

2024-03-19 21:39 UTC, hlissner requested changes

2024-03-19 21:42 UTC, hlissner requested changes

2024-03-19 21:42 UTC, hlissner commented on modules/completion/corfu/config.el
> +    (add-to-list 'corfu-margin-formatters #'nerd-icons-corfu-formatter))
Please move this into a separate `use-package!` block for `nerd-icons-corfu` (further below). I.e.

```elisp
(use-package! nerd-icons-corfu
  :when (modulep! +icons)
  :after corfu
  :config (add-to-list 'corfu-margin-formatters #'nerd-icons-corfu-formatter))
```

2024-03-19 21:42 UTC, hlissner commented on modules/completion/corfu/config.el
> +           (modulep! +orderless))
Please move these into orderless' use-package! block, i.e.

```elisp
(use-package! orderless
  :when (not (modulep! :completion vertico))
  :when (modulep! +orderless)
  ...)
```

2024-03-19 21:42 UTC, hlissner commented on modules/completion/helm/config.el
> +  (advice-add #'completion--in-region :around #'helm--completion-in-region)
Is this necessary? Seems helm-mode [already does this](https://github.com/emacs-helm/helm/blob/master/helm-mode.el#L2773-L2775), and `helm-mode-handle-completion-in-region` is non-nil by default.

2024-03-19 22:11 UTC, LuigiPiucco commented on modules/completion/corfu/config.el
> +    (add-to-list 'corfu-margin-formatters #'nerd-icons-corfu-formatter))
That's a good call, I just note [a prior advice from Liam](https://github.com/doomemacs/doomemacs/pull/7002#pullrequestreview-1641118934) was to try and avoid `use-package`'s `:after` key. For now, I'll implement it as:

```emacs-lisp
(use-package! nerd-icons-corfu
  :when (modulep! +icons)
  :defer t
  :init
  (after! corfu
    (add-to-list 'corfu-margin-formatters #'nerd-icons-corfu-formatter)))
```
...but I can change back to eager loading if you think this case is an exception.

2024-03-19 22:58 UTC, hlissner commented on modules/completion/corfu/config.el
> +    (add-to-list 'corfu-margin-formatters #'nerd-icons-corfu-formatter))
Yeah, that works just fine!

2024-03-19 22:59 UTC, LuigiPiucco commented on modules/completion/helm/config.el
> +  (advice-add #'completion--in-region :around #'helm--completion-in-region)
So this is a bit strange. It _shouldn't_ be needed, but a least in my testing, `completion--in-region` isn't advised automatically even with `helm-mode-handle-completion-in-region` being t. However, while investigating this I found a better implementation for `+corfu-move-to-minibuffer`, that doesn't rely on the advice being there and also a way to include Ido. So I'll remove this line from the commit. The new `+corfu-move-to-minibuffer` looks like this:
```emacs-lisp
(defun +corfu-move-to-minibuffer ()
  "Move the current list of candidates to your choice of minibuffer completion UI."
  (interactive)
  (pcase completion-in-region--data
    (`(,beg ,end ,table ,pred ,extras)
     (let ((completion-extra-properties extras)
           completion-cycle-threshold completion-cycling)
       (cond ((and (modulep! :completion vertico)
                   (fboundp #'consult-completion-in-region))
              (consult-completion-in-region beg end table pred))
             ((and (modulep! :completion ivy)
                   (fboundp #'ivy-completion-in-region))
              (ivy-completion-in-region (marker-position beg) (marker-position end) table pred))
             ;; Important: `completion-in-region-function' is set to corfu at
             ;; this moment, so `completion-in-region' (single -) doesn't work
             ;; below.
             ((modulep! :completion helm)
              ;; Helm is special and wants to _wrap_ `completion--in-region'
              ;; instead of replacing it in `completion-in-region-function'.
              ;; But because the advice is too unreliable we "fake" the wrapping.
              (helm--completion-in-region #'completion--in-region beg end table pred))
             ((modulep! :completion ido)
              (completion--in-region beg end table pred))
             (t (error "No minibuffer completion UI available for moving to!")))))))
```

2024-03-19 23:07 UTC, hlissner commented on modules/completion/helm/config.el
> +  (advice-add #'completion--in-region :around #'helm--completion-in-region)
>  It shouldn't be needed, but a least in my testing, completion--in-region isn't advised

Oh, Corfu sets `completion-in-region-function` to `#'corfu--in-region`, so perhaps the advice is being applied to that?

> The new +corfu-move-to-minibuffer looks like this

LGTM!

2024-03-19 23:35 UTC, hlissner requested changes

2024-03-19 23:35 UTC, hlissner commented on modules/completion/vertico/packages.el
> +(package! orderless :pin "dc7a781acf2e58ac7d20d1b522be0cde5213e057")
Is this bump needed? I'd rather the module be bumped separately, or that this bump happen in a separate bump commit.

2024-03-19 23:38 UTC, hlissner commented on modules/completion/vertico/packages.el
> +(package! orderless :pin "dc7a781acf2e58ac7d20d1b522be0cde5213e057")
In fact, if it isn't strictly necessary, I'd rather the change be undone altogether, since the vertico module needs a larger bump (which I'd like to do separate from this PR).

2024-03-19 23:39 UTC, LuigiPiucco commented on modules/completion/vertico/packages.el
> +(package! orderless :pin "dc7a781acf2e58ac7d20d1b522be0cde5213e057")
No, it can be bumped separately.

2024-03-19 23:47 UTC, hlissner approved these changes

2024-03-19 23:48 UTC, hlissner commented
Great! I think this is good to go. If there's nothing else, I'll merge this later tonight.

2024-03-19 23:51 UTC, LuigiPiucco commented
Yay! Sure, merge when you're ready. I don't have any further pending changes.

2024-03-20 01:09 UTC, merged

2024-03-20 01:09 UTC, hlissner commented
It's been a long time coming, but thanks so much for your hard work (and patiences with me)! I have big plans for this module post-v3 (to phase out company and go all in on Corfu), so I'm happy to finally get this merged. Thanks again!