Removed csharp-tree-sitter-mode as it's not a void function
doomemacs/doomemacs pull request #7112
Opened 2023-02-24 13:20 UTC by passeride

in Emacs 29.0.60 the function (csharp-tree-sitter-mode) is void and deprecated, and seems that tree-sitter works just fine without it. So i have Removed it

Fixes #0000
References #0000
Replaces #0000

-----
- [X] I searched the issue tracker and this hasn't been PRed before.
- [X] My changes are not on [the do-not-PR list](https://doomemacs.org/d/do-not-pr) for this project.
- [X] My commits conform to [the git conventions](https://doomemacs.org/d/git-conventions).
- [ ] My changes are visual; I've included before and after screenshots.
- [ ] I am blindly checking these off.
- [X] Any relevant issues or PRs have been linked to.
- [ ] This a draft PR; I need more time to finish it.

2023-02-24 13:21 UTC, passeride commented
Emacs 29 might be out of scope, and i see that tree-sitter was included as of 29, if this is out of scope of doom, feel free to decline this PR.

2023-02-24 13:27 UTC, passeride commented
Added version check so this does not break anything on 28.X

2023-02-24 21:13 UTC, hlissner commented
I'm certain this is not a bug with Doom or the module. `csharp-tree-sitter-mode` is defined by [a third party package](https://github.com/emacs-csharp/csharp-mode/blob/master/csharp-tree-sitter.el#L397). The installed version of Emacs doesn't change whether it exists or not.

Rather, I suspect this is a bug with the new `loaddefs-gen.el` library in Emacs 29, because `csharp-tree-sitter-mode` is an autoloaded function, and I've been hearing bug reports here and there about various autoloads issues on Discord and [Github](https://github.com/doomemacs/doomemacs/pull/6482#issuecomment-1441509169).

As removing one autoloaded function is not a proper solution to this, I cannot accept this PR. Thanks for bringing to my attention, in any case.

2023-02-24 21:28 UTC, hlissner requested changes
My bad! I forgot that csharp-mode had been absorbed into (much later commits of) Emacs 29. So this PR is correct. Just one small correction and it'll be ready for merging:

2023-02-24 21:28 UTC, hlissner commented on modules/lang/csharp/config.el
> +  (if (version<= emacs-version "28")
Use `fboundp` instead of a version check, because it is still possible to be on a build of Emacs 29 that predates this change. I.e.

```diff
-(if (version<= emacs-version "28")
+(if (fboundp #'csharp-tree-sitter-mode)
```

Since the function is autoloaded, it can be detected before the package is loaded.

2023-02-26 12:47 UTC, passeride commented on modules/lang/csharp/config.el
> +  (if (version<= emacs-version "28")
:+1: I updated it to recomendastion, thanks 4 feedback

2023-03-09 01:30 UTC, merged

2023-03-09 01:30 UTC, hlissner commented
Thanks for your help!