fix(clojure): load the localleader map earlier
doomemacs/doomemacs pull request #7140
Opened 2023-03-11 10:24 UTC by elken

Move the map for the localleader to `:init` rather than `:config` as all
the necessary cider jack-in functions are autoloaded

Fix: #7130

2023-03-11 10:36 UTC, elken commented
From Henrik: 

>  Modules shouldn't be eagerly binding localleader keys

So this PR will need adjustment still

2023-03-17 04:25 UTC, hlissner requested changes

2023-03-17 04:25 UTC, hlissner commented on modules/lang/clojure/config.el
> +       "f"  #'neil-find-clojure-package))
The indentation for this `map!` call is off by one.

2023-03-20 22:28 UTC, hlissner approved these changes

2023-03-20 22:29 UTC, merged

2023-03-20 22:29 UTC, hlissner commented
Thanks again for your help!