docs(lispy): add notes for inserting brackets
doomemacs/doomemacs pull request #7260
Opened 2023-06-01 17:02 UTC by cpackard

Add documentation on how insert brackets `[]` with `lispy` enabled. 

By default `lispy` binds commands to `[` and `]` even in insert state, which caused myself (and a [few](https://github.com/noctuid/lispyville/issues/36) [others](https://github.com/abo-abo/lispy/issues/83)) confusion when first using the module.

-----
- [x] I searched the issue tracker and this hasn't been PRed before.
- [x] My changes are not on [the do-not-PR list](https://doomemacs.org/d/do-not-pr) for this project.
- [x] My commits conform to [the git conventions](https://doomemacs.org/d/git-conventions).
- [ ] I am blindly checking these off.
- [x] Any relevant issues or PRs have been linked to.

2023-07-22 14:09 UTC, hlissner requested changes

2023-07-22 14:09 UTC, hlissner commented on modules/editor/lispy/README.org
> +By default, =[= and =]= are [[https://github.com/noctuid/lispyville/tree/master#additional-movement-key-theme][bound]] to =lispyville-previous-opening= and =lispyville-next-closing= respectively. If
Please fill this paragraph (move cursor into paragraph and execute `M-x org-fill-paragraph`).

2023-07-22 14:09 UTC, hlissner commented on modules/editor/lispy/README.org
> +;; config.el
Please change this to:

```diff
-;; config.el
+;; in $DOOMDIR/config.el
```

This is a convention that I've been slowly introducing to our docs.

2023-07-22 14:09 UTC, hlissner commented on modules/editor/lispy/README.org
> +      "M-]" #'lispyville-next-closing)
Please combine the `map!` calls into logic groupings:

```lisp
(map! :after (lispy lispyville)
      :map lispy-mode-map-lispy
      ;; unbind individual bracket keys
      "[" nil
      "]" nil
      ;; re-bind commands bound to bracket keys by default
      "M-[" #'lispyville-previous-opening
      "M-]" #'lispyville.next-opening)
```

2023-07-22 14:09 UTC, hlissner commented on modules/editor/lispy/README.org
> +      "M-]" #'lispyville-next-closing)
Side question: are you sure that `lispy-mode-map-lispy` is the correct name for the keymap variable? It breaks a few naming conventions, which makes it look like a mistake.

2023-07-22 14:10 UTC, hlissner requested changes
Oh! I just realized this PR targets the `rewrite-docs` branch, which was already merged some time ago and is no longer being used. Could you rebase this PR onto `master`?

2023-07-24 18:34 UTC, cpackard commented on modules/editor/lispy/README.org
> +By default, =[= and =]= are [[https://github.com/noctuid/lispyville/tree/master#additional-movement-key-theme][bound]] to =lispyville-previous-opening= and =lispyville-next-closing= respectively. If
Sure, done.

2023-07-24 18:35 UTC, cpackard commented on modules/editor/lispy/README.org
> +;; config.el
Makes sense, updated to use this convention.

2023-07-24 18:39 UTC, cpackard commented
> Oh! I just realized this PR targets the `rewrite-docs` branch, which was already merged some time ago and is no longer being used. Could you rebase this PR onto `master`?

Sure, rebased this PR onto `master` and pointed the PR at the same branch upstream.

2023-07-24 19:12 UTC, hlissner approved these changes

2023-07-24 21:22 UTC, merged

2023-07-24 21:22 UTC, hlissner commented
LGTM! Thanks for your help!

2023-07-24 21:24 UTC, cpackard commented
Happy to help, thank you for a great framework!