feat(fortran): `SPC m f o` opens project config
doomemacs/doomemacs pull request #7396
Opened 2023-09-08 06:35 UTC by fosskers

This PR adds a new convenience function and binding to the `fortran` module.

-----
- [ ] I searched the issue tracker and this hasn't been PRed before.
- [ ] My changes are not on [the do-not-PR list](https://doomemacs.org/d/do-not-pr) for this project.
- [ ] My commits conform to [the git conventions](https://doomemacs.org/d/git-conventions).
- [ ] My changes are visual; I've included before and after screenshots.
- [ ] I am blindly checking these off.

2023-09-08 06:39 UTC, fosskers commented on modules/lang/fortran/autoload.el
> +    (find-file (file-name-concat root "fpm.toml"))))
Silently does nothing when not in an FPM-based project.

2023-09-08 18:59 UTC, hlissner requested changes

2023-09-08 18:59 UTC, hlissner commented on modules/lang/fortran/autoload.el
> +    (find-file (file-name-concat root "fpm.toml"))))
To make it more versatile and improve its feedback, please change it to:

```elisp
(defun +fortran/fpm-open-project-toml (project-root)
  "Open fpm.toml at PROJECT-ROOT (defaults to the open project)."
  (interactive (list (doom-project-root)))
  (let ((file (file-name-concat project-root "fpm.toml")))
    (if (file-exists-p file)
        (find-file file)
      (user-error "No fpm.toml found at project root (%s)"
                  (abbreviate-file-name project-root)))))
```

2023-09-09 01:33 UTC, fosskers commented on modules/lang/fortran/autoload.el
> +    (find-file (file-name-concat root "fpm.toml"))))
That would be much better yeah. Thanks for reminding me about `user-error`!

2023-09-09 10:21 UTC, fosskers commented on modules/lang/fortran/autoload.el
> +                         (abbreviate-file-name project-root))))))
An extra branch was necessary here; `abbreviate-file-name` gives an unhelpful error when `project-root` is `nil`.

2023-09-09 16:06 UTC, hlissner approved these changes

2023-09-09 21:58 UTC, merged

2023-09-09 21:58 UTC, hlissner commented
LGTM. Thanks again for your help!