Fix font fallbacks
doomemacs/doomemacs pull request #7448
Opened 2023-09-21 01:30 UTC by hpfr

See commit messages for details. Please comment if you can confirm this is an improvement, as font configuration varies from user to user and is somewhat dependent on environment and operating system. I’m fairly confident it’s good, though. To test, please remove any workarounds you may have made from your configs. Checking out my branch in your Doom installation and starting a new Emacs instance should be all you need to test. You can leave your current Emacs instance running if you have a bunch of stuff you’re working on. Just make sure to return to `master` when you’re done testing.

- Fix #2083
- Fix #3296
- Fix #5474
- Fix #5160
- Fix #5623
- Fix #7036
- Fix #7167
- Fix #7467

-----
- [x] I searched the issue tracker and this hasn't been PRed before.
- [x] My changes are not on [the do-not-PR list](https://doomemacs.org/d/do-not-pr) for this project.
- [x] My commits conform to [the git conventions](https://doomemacs.org/d/git-conventions).
- [ ] My changes are visual; I've included before and after screenshots.
- [x] *n/a* Any relevant issues or PRs have been linked to.

2023-09-21 03:15 UTC, hlissner requested changes
Looks good, but would you mind removing the `(core)` scope from the git messages ([scope should be omitted for changes to Doom's core](https://discourse.doomemacs.org/t/git-conventions/2407#scopes-4)).

2023-09-21 09:01 UTC, fosskers commented
This fixes the issue for me.

2023-09-21 16:31 UTC, catap commented
Well.. emacs-29.1 looks the same way

<img width="692" alt="Screenshot 2023-09-21 at 18 30 43" src="https://github.com/doomemacs/doomemacs/assets/37775/0f6866b6-bce6-44d4-be72-e0383d3cff8d">

2023-09-21 16:47 UTC, catap commented
but mine behaviour might not be related at all

2023-09-21 19:35 UTC, catap commented
Nope, mine issue is started after 9787022b839d2d22cb772c6d61cc7f35b9dd5e95 => should be fixed by this commit but doesn't

2023-09-21 22:55 UTC, George9000 commented
Please see my reply in #3296 This did not fix my reported issue and broke the workaround.

2023-09-22 03:10 UTC, fosskers commented
@hpfr Who is "you" in this case?

2023-09-22 23:01 UTC, vancleve commented
Hi @hpfr. I've tried your PR and it improves things somewhat but not completely. 

I'll show below screenshots for whether I set the `doom-unicode-font` and whether I use my hack from https://github.com/doomemacs/doomemacs/issues/7036#issuecomment-1409748597 for both `doom` master and for this PR. The upshot is that this PR does seem to be fixing some of the emoji issues but as you can see there are still a few emoji characters that don't display despite being present in the font Apple Color Emoji. These same emoji are displayed for some reason when I both set the `doom-unicode-font` and when I use my hack. For doom master, I bizarrely only get these emoji to display properly with my hack but *without* setting `doom-unicode-font`. When I set `doom-unicode-font` to JuliaMono in that case, some of the emoji are coming from JuliaMono instead of from Apple Color Emoji.

The PR does seem to fix the file icons to `Symbols Nerd` even when the `doom-font` has the same glyphs, which is nice.

Master:
<img width="1672" alt="image" src="https://github.com/doomemacs/doomemacs/assets/1442334/c5f7bd86-ca14-4de2-ab87-08c5f1e30659">

This PR:
<img width="1672" alt="image" src="https://github.com/doomemacs/doomemacs/assets/1442334/f784dd7b-7d26-4766-8b72-ae491f3908ae">



Doom info:
<img width="576" alt="image" src="https://github.com/doomemacs/doomemacs/assets/1442334/f30bc0d8-5339-4125-be6b-e6a13c4241f0">

2023-09-24 22:33 UTC, George9000 commented
@hpfr Results:

First, I cloned the latest doom commit to `~/.config/emacs`
Then I ran the config I use but stripped down, which can be seen [here](https://github.com/George9000/doom/tree/main). Doom info can be expanded below. File used in screenshots below is [here](https://gist.github.com/George9000/1f2ea7734c3198c263fda861d9e27af0)

<details>
<summary>doom/info</summary>

```
generated  Sep 24, 2023 17:04:24
system     MacOS 12.7 Darwin 21.6.0 arm64 mac
emacs      29.1 HEAD e5f196da5 ~/.config/emacs/
doom       3.0.0-pre PROFILE=_@0 grafted, HEAD -> master, origin/master, origin/HEAD
           844a82c 2023-09-22 23:18:31 +0200 ~/.config/doom/
shell      /bin/zsh
features   ACL GLIB GMP GNUTLS IMAGEMAGICK JSON LCMS2 LIBXML2 MODULES NATIVE_COMP
           NOTIFY KQUEUE PDUMPER RSVG SQLITE3 THREADS TOOLKIT_SCROLL_BARS TREE_SITTER
           WEBP XIM ZLIB
traits     gui server-running envvar-file
modules    :config use-package :completion company vertico :ui doom doom-dashboard
           hl-todo modeline ophints (popup +defaults) (vc-gutter +pretty)
           vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold
           snippets :emacs dired electric undo vc :checkers syntax :tools (eval
           +overlay) lookup lsp magit tree-sitter :os macos :lang emacs-lisp (julia
           +tree-sitter +lsp) markdown org sh :config (default +bindings +smartparens)
packages   (doct) (svg-tag-mode) (treesit-auto) (julia-ts-mode :recipe (:host github
           :repo ronisbr/julia-ts-mode)) (doom-nano-modeline :recipe (:host github
           :repo ronisbr/doom-nano-modeline)) (julia-mode :pin
           a20367f2826b26084abd2f403219218813007123)
unpin      julia-repl
```
  
</details>

### Doom master with my config

<img width="1052" alt="doom_master_unicode_math_glyphs_my_config" src="https://github.com/doomemacs/doomemacs/assets/16549651/1db073f6-90f8-4b2f-9dd2-655125243c22">

Then I followed your instructions to set up a `profiles.el` in `~/.config/doom`, cloned your doom fork/branch to `~/.config/emacs-doom-upstream/` and created an `init.el` and `config.el` in `~/.config/doom-sandbox/`. Following your steps 5 and 6, here is the result.

### hpfr fork with suggested config


<img width="1276" alt="hpfr_branch_unicode_math_glyphs_firamono_16" src="https://github.com/doomemacs/doomemacs/assets/16549651/45d826f3-e32c-47f6-8a8f-b695f2ad6ddb">

I then tried modifying your config with my fonts like this:

```
;;; config.el --- Doom sandbox -*- lexical-binding: t; -*-
(load-theme 'modus-operandi t)
;(setq doom-font (font-spec :family "Fira Mono" :size 16)
;      doom-variable-pitch-font (font-spec :family "Fira Sans"))

(setq doom-font (font-spec :family "TheSansMono" :size 14 :weight 'medium))
(setq doom-unicode-font (font-spec :family "JuliaMono" :size 16 :weight 'medium))
```

<img width="1024" alt="hpfr_branch_unicode_math_glyphs_sansmono_juliamono" src="https://github.com/doomemacs/doomemacs/assets/16549651/89c46c30-12b6-4e81-86ca-936347b0b759">

Last I tried appending my workaround after the lines above:

```
(when (display-graphic-p)
(dolist (charset '(unicode))
  (set-fontset-font (frame-parameter nil 'font)
    charset (font-spec :family "JuliaMono" :size 16 :weight 'medium))))
```

This had no effect. The most problematic glyphs are those in the first two lines: the "element of" symbol and the "ring operator" symbol used for function composition in Julia. The rendering is quite spindly or tiny using the hpfr branch and more robust on the current doom master branch. `describe-char` output [here](https://gist.github.com/George9000/4cc9186971b25fe6b9eb5beceafa68e0)

`describe-fontset` output for [my initial config](https://gist.github.com/George9000/8b38539937714ea2b73b87548cbc4146) and for the [hpfr config](https://gist.github.com/George9000/0bd7cec4070500e11a86a4fc420c4481).

In conclusion, I prefer the current doom master rendering over the proposed hpfr branch merge.

2023-09-25 17:48 UTC, George9000 commented
I've used the latest commit from your fork/branch. Then set fonts as directed:

![config_fonts](https://github.com/doomemacs/doomemacs/assets/16549651/f41c8590-6c07-4e43-9e63-c7175e84d43f)

Result:

![example_jl](https://github.com/doomemacs/doomemacs/assets/16549651/ed63bba3-41e1-4190-a792-f9f06b01dde5)

Note the continued problem with "element of" and "ring operator" symbols. The ring operator / compose symbol is particularly bad.

![epsilon_compose_symbol](https://github.com/doomemacs/doomemacs/assets/16549651/fe643457-8476-4587-b139-cede670971b7)

Even other symbols in that file seem to have better / bolder rendering in `doom master` as seen in the prior reply. Again, prefer doom master as it currently stands. Yes, this requires a couple lines of workaround but the result is pleasing.

2023-09-26 22:55 UTC, George9000 commented
Mea culpa. I was using `git clone --depth 1` with your repo and not getting the fix-font-fallbacks branch. Corrected that just now.

_Issues resolved_. Appreciate your considerable efforts to address problems raised.

[describe-fontset output](https://gist.github.com/George9000/cfdb93924592688ef696692ec0fcf6e6)

[describe-char output for three characters](https://gist.github.com/George9000/172d71d9f425e9e5303867d828e90272)

![example](https://github.com/doomemacs/doomemacs/assets/16549651/6b752336-e8bb-4442-a352-5db4173660ff)

![closeup](https://github.com/doomemacs/doomemacs/assets/16549651/f9d857b3-c81f-47db-93dd-6fea3478e669)

2023-09-27 20:03 UTC, vancleve commented
Hi @hpfr! Sorry, busy at work, but coming back to emacs now :-).

Thanks for all this hard work!

I followed your instructions to setup the sandbox using the most recent version of the PR.

Things are looking very good though there is one issue and one question with a few of the emoji I've just randomly put in this test file

[math_characters.txt](https://gist.github.com/vancleve/223a00e320423ba6d125d4cc97c41587)
<img width="961" alt="image" src="https://github.com/doomemacs/doomemacs/assets/1442334/c664204c-63a9-4901-9c17-a94b4bf4b2ec">

1.  🕳🗯 characters are not displayed despite being present in Apple Color Emoji
<img width="661" alt="image" src="https://github.com/doomemacs/doomemacs/assets/1442334/c70b405a-4b72-4659-b72e-c8b0a58b2ab3">

2. 🗨 character is represented by JuliaMono instead of Apple Color Emoji. I assume this is just going to happen when the symbol font specifies characters also specified by the emoji font?

[describe-char: 🕳🗨🗯](https://gist.github.com/vancleve/a56f189c9a0f9bc87992a5e1128c013f)
[(describe-fontset nil)](https://gist.github.com/vancleve/03fca8b3798e203028dd8a6cb49d23f2)
[init.el](https://gist.github.com/vancleve/67488575a64d9053a510954ee89bef4d)
[config.el](https://gist.github.com/vancleve/6d65f8771ac84ede1c61869bd908d724)
[doom/info](https://gist.github.com/vancleve/d8a77346cb618b7368bef977e6e32186)

2023-09-28 03:39 UTC, vancleve commented
Wow, very informative @hpfr! Thanks again and looking forward to seeing this in `doom` master!

2023-10-07 00:33 UTC, hlissner approved these changes

2023-10-07 00:33 UTC, merged

2023-10-07 00:33 UTC, hlissner commented
Great work! Thanks again for your help!