fix(org): make sure org-reveal is called in the right buffer
doomemacs/doomemacs pull request #7509
Opened 2023-10-17 14:45 UTC by Zetagon

Sometimes, `org-reveal` is called in the wrong buffer which throws an error.  For example, `org-link-open-from-string` creates an temporary org-mode buffer that gets killed very quickly which means that `org-reveal` gets called in a different buffer.  I have also had issues with org-reveal getting called in the org-roam buffer, which is why this commit also saves the buffer it was called in.

-----
- [X] I searched the issue tracker and this hasn't been PRed before.
- [X] My changes are not on [the do-not-PR list](https://doomemacs.org/d/do-not-pr) for this project.
- [X] My commits conform to [the git conventions](https://doomemacs.org/d/git-conventions).
- [X] Any relevant issues or PRs have been linked to.

2023-10-18 09:04 UTC, Zetagon commented
> I think you can drop the commented code though?

You saw nothing :eyes:

2023-10-22 22:09 UTC, hlissner requested changes

2023-10-22 22:09 UTC, hlissner commented on modules/lang/org/autoload/org.el
> +                                      (org-reveal '(4)))))))))
Please use `lambda` instead of `λ!`. 

`λ!` is an alias for `cmd!` which only exists for backwards compatibility in user elisp, and shouldn't be used within Doom's source. It also produces an interactive closure, which `run-at-time` does not benefit from.

2023-10-23 06:35 UTC, Zetagon commented on modules/lang/org/autoload/org.el
> +                                      (org-reveal '(4)))))))))
Fixed.

2023-11-23 22:26 UTC, hlissner approved these changes

2023-11-24 02:21 UTC, merged

2023-11-24 02:21 UTC, hlissner commented
LGTM. Thanks for your help!

2023-11-29 10:26 UTC, real-or-random reviewed
This breaks `org-roam-capture` (and `org-capture`) for me because this command uses multiple org buffers and the initial one will be dead when the timer runs.

2023-11-29 10:26 UTC, real-or-random commented on modules/lang/org/autoload/org.el
> +                                    (org-reveal '(4)))))))))
```suggestion

                                  (when (buffer-live-p buf)
                                    (with-current-buffer buf
                                      (org-reveal '(4))))))))))
```