docs: added +lsp flag to terraform module
doomemacs/doomemacs pull request #7553
Opened 2023-11-19 19:26 UTC by ponchoalv

Replace this with a summary of what you've changed and why, followed by a list of issues it affects, if any.

Fix: #0000
Ref: #0000
Close: #0000

-----
- [ ] I searched the issue tracker and this hasn't been PRed before.
- [ ] My changes are not on [the do-not-PR list](https://doomemacs.org/d/do-not-pr) for this project.
- [ ] My commits conform to [the git conventions](https://doomemacs.org/d/git-conventions).
- [ ] My changes are visual; I've included before and after screenshots.
- [ ] I am blindly checking these off.
- [ ] Any relevant issues or PRs have been linked to.
- [ ] This a draft PR; I need more time to finish it.

2023-11-23 21:23 UTC, hlissner requested changes
To conform to [our git conventions](https://doomemacs.org/d/git-conventions), please reword the commit to:

```
docs(terraform): mention +lsp flag
```

Side-note:

(¬‿¬) ![image](https://github.com/doomemacs/doomemacs/assets/510883/0fdf3a88-3d2f-4a71-8747-801229c8643a)

2023-11-23 21:23 UTC, hlissner commented on modules/tools/terraform/README.org
> +run Tearraform commands directly from Emacs.
Please revert this typo.

2023-11-24 18:36 UTC, ponchoalv commented on modules/tools/terraform/README.org
> +run Tearraform commands directly from Emacs.
done, thank you!

2023-11-24 18:37 UTC, ponchoalv commented
> Side-note:
> 
> (¬‿¬) ![image](https://user-images.githubusercontent.com/510883/285309250-0fdf3a88-3d2f-4a71-8747-801229c8643a.png)

:trollface:

2023-11-24 23:39 UTC, merged

2023-11-24 23:39 UTC, hlissner commented
Excellent! Thanks for your help!