docs(ivy): mention lowered `ivy-sort-max-size`
doomemacs/doomemacs pull request #7641
Opened 2024-01-30 15:49 UTC by 45mm

Depending on the system, this can cause sorting to be disabled long before the performance hit would be felt, and it's not obvious that this is the reason.

-----
- [x] I searched the issue tracker and this hasn't been PRed before.
- [x] My changes are not on [the do-not-PR list](https://doomemacs.org/d/do-not-pr) for this project.
- [x] My commits conform to [the git conventions](https://doomemacs.org/d/git-conventions).

2024-01-31 21:28 UTC, hlissner requested changes

2024-01-31 21:28 UTC, hlissner commented on modules/completion/ivy/README.org
> +If the number of candidates is greater than ~ivy-sort-max-size~, sorting will be disabled completely. Doom lowers the default value to prevent performance issues, so increasing the value may fix your
Could you run `M-x org-fill-paragraph` on this paragraph?

Also, please add an elisp snippet after it:

```org
#+begin_src elisp
;;; add to $DOOMDIR/config.el
(after! ivy
  (setq ivy-sort-max-size 30000))  ; Doom sets this to 7500, but Ivy's default is 30k
#+end_src
```

2024-02-01 12:33 UTC, 45mm commented on modules/completion/ivy/README.org
> +If the number of candidates is greater than ~ivy-sort-max-size~, sorting will be disabled completely. Doom lowers the default value to prevent performance issues, so increasing the value may fix your
done

2024-02-02 08:25 UTC, hlissner approved these changes

2024-02-02 08:25 UTC, merged

2024-02-02 08:25 UTC, hlissner commented
LGTM. Thanks for your help!