fix(vertico): mapping for embark open in workspace
doomemacs/doomemacs pull request #7651
Opened 2024-02-06 11:51 UTC by 45mm

Bind to both `TAB` and `<tab>` - if they have been mapped to different commands anywhere, Emacs will no longer treat them as equivalent, and this mapping will not work.

- [x] I searched the issue tracker and this hasn't been PRed before.
- [x] My changes are not on [the do-not-PR list](https://doomemacs.org/d/do-not-pr) for this project.
- [x] My commits conform to [the git conventions](https://doomemacs.org/d/git-conventions).

2024-02-10 21:21 UTC, hlissner requested changes

2024-02-10 21:21 UTC, hlissner commented on modules/completion/vertico/config.el
> +                                               "<tab>" #'+vertico/embark-open-in-new-workspace))))
The `:desc` needs to be repeated. I.e.

```diff
-           :desc "Open in new workspace"       "TAB" #'+vertico/embark-open-in-new-workspace))))
+           :desc "Open in new workspace"       "TAB" #'+vertico/embark-open-in-new-workspace
+           :desc "Open in new workspace"       "<tab>" #'+vertico/embark-open-in-new-workspace))))
```

2024-02-11 11:27 UTC, 45mm commented on modules/completion/vertico/config.el
> +                                               "<tab>" #'+vertico/embark-open-in-new-workspace))))
Whoops, my bad. Fixed.

2024-02-16 00:22 UTC, hlissner approved these changes

2024-03-05 06:13 UTC, merged

2024-03-05 06:13 UTC, hlissner commented
Thanks for your help!