feat(macos): osx-trash is only needed by emacs < 29
doomemacs/doomemacs pull request #7723
Opened 2024-03-12 17:14 UTC by seanfarley

As the title says, osx-trash is no longer needed nowadays for emacs so one less package to install :-)

2024-03-13 00:07 UTC, hlissner approved these changes

2024-03-13 04:20 UTC, hlissner requested changes

2024-03-13 04:20 UTC, hlissner commented on modules/os/macos/config.el
>    :commands osx-trash-move-file-to-trash
Even if the package isn't installed, we still need to set `delete-by-moving-to-trash`, so please make the following changes:

```diff
   :commands osx-trash-move-file-to-trash
   :init
-  ;; Delete files to trash on macOS, as an extra layer of precaution against
-  ;; accidentally deleting wanted files.
-  (setq delete-by-moving-to-trash t)
- 
   ;; Lazy load `osx-trash'
```

```diff
 ;; Integrate with Keychain
 (after! auth-source
   (pushnew! auth-sources 'macos-keychain-internet 'macos-keychain-generic))
+
+;; Delete files to trash on macOS, as an extra layer of precaution against
+;; accidentally deleting wanted files.
+(setq delete-by-moving-to-trash t)
+

 ;;
 ;;; Packages

```

2024-03-13 04:20 UTC, hlissner commented on modules/os/macos/config.el
> +  ;; fixed by https://debbugs.gnu.org/cgi/bugreport.cgi?bug=21340
Please make formatting consistent with other notices:

```diff
 (use-package! osx-trash
-  ;; DEPRECATED Not needed on Emacs 29+. Remove when dropping 28 support.
-  ;; fixed by https://debbugs.gnu.org/cgi/bugreport.cgi?bug=21340
+  ;; DEPRECATED: Not needed on Emacs 29+. Remove when dropping 28 support.
+  ;;   Fixed by https://debbugs.gnu.org/cgi/bugreport.cgi?bug=21340.
   :when (< emacs-major-version 29)
```

2024-03-13 15:33 UTC, seanfarley commented on modules/os/macos/config.el
>    :commands osx-trash-move-file-to-trash
Oh jeez, that completely slipped by me >_<

2024-03-13 15:46 UTC, seanfarley commented on modules/os/macos/config.el
> +  ;; fixed by https://debbugs.gnu.org/cgi/bugreport.cgi?bug=21340
I don't suppose there is a doom function to format these type of comments, is there? 😬

2024-03-13 17:27 UTC, hlissner approved these changes

2024-03-13 17:28 UTC, hlissner commented on modules/os/macos/config.el
> +  ;; fixed by https://debbugs.gnu.org/cgi/bugreport.cgi?bug=21340
Afraid not. The closest you'll get is `gq` (`evil-fill-and-move`) or `M-q` (`fill-paragraph`), but only handles line-width, not indentation or colon.

2024-03-14 10:13 UTC, merged

2024-03-14 10:13 UTC, hlissner commented
LGTM. Thanks again for your help!