fix(eval): warnings after eval error
doomemacs/doomemacs pull request #7753
Opened 2024-03-24 05:13 UTC by pysnow530

Replace this with a summary of what you've changed and why, followed by a list of issues it affects, if any.

Fix: #7752

-----
- [x] I searched the issue tracker and this hasn't been PRed before.
- [x] My changes are not on [the do-not-PR list](https://doomemacs.org/d/do-not-pr) for this project.
- [x] My commits conform to [the git conventions](https://doomemacs.org/d/git-conventions).
- [x] My changes are visual; I've included before and after screenshots.
- [x] Any relevant issues or PRs have been linked to.

2024-03-24 05:16 UTC, pysnow530 commented
* solution

fix(eval): warnings after eval error

This PR use solution 1

** Solution 1

Don't override ~major-mode~, use optional argument instead.

** Solution 2

Another solution is to =suppress the warning=, and =patch the code= in org mode.

But org source code may changed in the future, and introduce new bugs.

2024-04-01 15:07 UTC, hlissner requested changes

2024-04-01 15:07 UTC, hlissner commented on modules/tools/eval/autoload/eval.el
> +(defun +eval/region-as-major-mode (beg end &optional runner-major-mode)
Please rename this to `+eval--region-as-major-mode` and remove the `;;;###autoload` cookie.

2024-04-09 00:59 UTC, closed without merging

2024-04-09 01:00 UTC, hlissner commented
I made a few refactors and merged it into 21f6fb7, which should resolve your issue. Thanks for bringing it to my attention, in any case!