Switch to using opam-switch-mode for :lang ocaml
doomemacs/doomemacs pull request #7806
Opened 2024-04-10 12:36 UTC by punchagan

The PR adds configuration to install `opam-switch-mode` to manage OCaml's opam switches, instead of using a deprecated method in the `tuareg` package. 

Replace this with a summary of what you've changed and why, followed by a list of issues it affects, if any.

Fix: #0000
Ref: #0000
Close: #0000

-----
- [x] I searched the issue tracker and this hasn't been PRed before.
- [x] My changes are not on [the do-not-PR list](https://doomemacs.org/d/do-not-pr) for this project.
- [x] My commits conform to [the git conventions](https://doomemacs.org/d/git-conventions).

I'm not sure if the DNP on modules is still in place, since there's been no activity on the modules repository since the last comment on the DNP list.

2024-04-12 01:19 UTC, hlissner requested changes

2024-04-12 01:19 UTC, hlissner commented on modules/lang/ocaml/config.el
> +  (opam-switch-set-switch (tuareg-opam-current-compiler)))
Please move this into `opam-switch-mode`'s `use-package!` block (under `:config`). E.g.

```elisp
  (defun +ocaml-init-opam-switch-h ()
    "Activate `opam-switch-mode' if the opam executable exists."
    (when (executable-find "opam")
      (opam-switch-mode))))
  :config
  ;; Use opam to set environment
  (setq tuareg-opam-insinuate t)
  (opam-switch-set-switch (tuareg-opam-current-compiler)))
```

2024-04-16 04:22 UTC, punchagan commented on modules/lang/ocaml/config.el
> +  (opam-switch-set-switch (tuareg-opam-current-compiler)))
Fixed, thanks!

2024-06-19 08:38 UTC, punchagan commented
@hlissner Let me know if I need to make any more changes to the PR to make it merge-able.

2024-06-21 21:55 UTC, merged

2024-06-21 21:55 UTC, hlissner commented
LGTM! Thanks for your help and patience!

2024-06-22 09:46 UTC, punchagan commented
> LGTM! Thanks for your help and patience!

You're welcome! Thank you for merging it; and for all the hardwork with doom!