feat(file-templates): add apply method
doomemacs/doomemacs pull request #8133
Opened 2024-10-31 22:44 UTC by dradetsky

Factor template application code into command file-templates-apply. This allows it to be invoked by the user.

Personally, I find file templates very annoying, and 9/10 times I would end up just deleting the template boilerplate, so I disabled it. However, in some cases I might want to use it. Rather than having to reconfigure whether templates are enabled and re-create the file, we simply pull the couple of lines where the template is actually applied out into a function and add `(interactive)`. Now I can just `M-x file-templates-apply` in the buffer where I want to use the templates.

-----
- [x] I searched the issue tracker and this hasn't been PRed before.
- [x] My changes are not on [the do-not-PR list](https://doomemacs.org/donotpr) for this project.
- [x] My commits conform to [Doom's git conventions](https://doomemacs.org/d/git-conventions).
- [x] I am blindly checking these off.

2024-11-06 08:09 UTC, hlissner requested changes
Side-note: file templates are also simply yasnippet snippets with a name that starts with `__`, so they can expanded like any other snippet: e.g. `__` + `TAB`. This was the intended way folks would expand them, and why a command wasn't initially available.

![image](https://github.com/user-attachments/assets/6e9da3ed-68f2-4757-9e77-1cdb02491104)

2024-11-06 08:09 UTC, hlissner commented on modules/editor/file-templates/config.el
> +(defun file-templates-apply ()
To conform with our naming conventions, please rename this to `+file-templates/apply`.

2024-11-06 08:09 UTC, hlissner commented on modules/editor/file-templates/config.el
> +  (when-let (rule (cl-find-if #'+file-template-p +file-templates-alist))
`when-let` is deprecated in Emacs 31; replace this with `when-let*`. I.e.

```diff
   (interactive)
-  (when-let (rule (cl-find-if #'+file-template-p +file-templates-alist))
+  (when-let* ((rule (cl-find-if #'+file-template-p +file-templates-alist)))
    (apply #'+file-templates--expand rule)))

2024-11-06 10:16 UTC, dradetsky commented on modules/editor/file-templates/config.el
> +  (when-let (rule (cl-find-if #'+file-template-p +file-templates-alist))
Ironically, I noticed this & wanted to change it, but I was worried that you had too much to deal with already & didn't want to add cognitive load to what was a simple PR.

2024-12-01 16:23 UTC, merged

2024-12-01 16:23 UTC, hlissner commented
LGTM! Thanks for your help!